// Code generated by tools/gen/accessors from active_aero_zone.go. DO NOT EDIT.

package f12025

// GetZoneStart returns [ActiveAeroZone.ZoneStart]
func (data *ActiveAeroZone) GetZoneStart() float32 { return data.ZoneStart }

// SetZoneStart stores [ActiveAeroZone.ZoneStart]
func (data *ActiveAeroZone) SetZoneStart(v float32) { data.ZoneStart = v }

// GetZoneEnd returns [ActiveAeroZone.ZoneEnd]
func (data *ActiveAeroZone) GetZoneEnd() float32 { return data.ZoneEnd }

// SetZoneEnd stores [ActiveAeroZone.ZoneEnd]
func (data *ActiveAeroZone) SetZoneEnd(v float32) { data.ZoneEnd = v }
