// Code generated by tools/gen/accessors from drs_zone.go. DO NOT EDIT.

package f12025

// GetZoneStart returns the ZoneStart of [DRSZone]
func (data *DRSZone) GetZoneStart() float32 { return data.ZoneStart }

// SetZoneStart stores the ZoneStart of [DRSZone]
func (data *DRSZone) SetZoneStart(v float32) { data.ZoneStart = v }

// GetZoneEnd returns the ZoneEnd of [DRSZone]
func (data *DRSZone) GetZoneEnd() float32 { return data.ZoneEnd }

// SetZoneEnd stores the ZoneEnd of [DRSZone]
func (data *DRSZone) SetZoneEnd(v float32) { data.ZoneEnd = v }
