// Code generated by tools/gen/accessors from event_data_team_mate_in_pits.go. DO NOT EDIT.

package f12025

// GetVehicleIdx returns the VehicleIdx of [EventDataTeamMateInPits]
func (data *EventDataTeamMateInPits) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores the VehicleIdx of [EventDataTeamMateInPits]
func (data *EventDataTeamMateInPits) SetVehicleIdx(v uint8) { data.VehicleIdx = v }
