// Code generated by tools/gen/accessors from event_data_speed_trap.go. DO NOT EDIT.

package f12025

// GetVehicleIdx returns the VehicleIdx of [EventDataSpeedTrap]
func (data *EventDataSpeedTrap) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores the VehicleIdx of [EventDataSpeedTrap]
func (data *EventDataSpeedTrap) SetVehicleIdx(v uint8) { data.VehicleIdx = v }

// GetSpeed returns the Speed of [EventDataSpeedTrap]
func (data *EventDataSpeedTrap) GetSpeed() float32 { return data.Speed }

// SetSpeed stores the Speed of [EventDataSpeedTrap]
func (data *EventDataSpeedTrap) SetSpeed(v float32) { data.Speed = v }

// GetIsOverallFastestInSession returns the IsOverallFastestInSession of [EventDataSpeedTrap]
func (data *EventDataSpeedTrap) GetIsOverallFastestInSession() uint8 {
	return data.IsOverallFastestInSession
}

// SetIsOverallFastestInSession stores the IsOverallFastestInSession of [EventDataSpeedTrap]
func (data *EventDataSpeedTrap) SetIsOverallFastestInSession(v uint8) {
	data.IsOverallFastestInSession = v
}

// GetIsDriverFastestInSession returns the IsDriverFastestInSession of [EventDataSpeedTrap]
func (data *EventDataSpeedTrap) GetIsDriverFastestInSession() uint8 {
	return data.IsDriverFastestInSession
}

// SetIsDriverFastestInSession stores the IsDriverFastestInSession of [EventDataSpeedTrap]
func (data *EventDataSpeedTrap) SetIsDriverFastestInSession(v uint8) {
	data.IsDriverFastestInSession = v
}

// GetFastestVehicleIdxInSession returns the FastestVehicleIdxInSession of [EventDataSpeedTrap]
func (data *EventDataSpeedTrap) GetFastestVehicleIdxInSession() uint8 {
	return data.FastestVehicleIdxInSession
}

// SetFastestVehicleIdxInSession stores the FastestVehicleIdxInSession of [EventDataSpeedTrap]
func (data *EventDataSpeedTrap) SetFastestVehicleIdxInSession(v uint8) {
	data.FastestVehicleIdxInSession = v
}

// GetFastestSpeedInSession returns the FastestSpeedInSession of [EventDataSpeedTrap]
func (data *EventDataSpeedTrap) GetFastestSpeedInSession() float32 { return data.FastestSpeedInSession }

// SetFastestSpeedInSession stores the FastestSpeedInSession of [EventDataSpeedTrap]
func (data *EventDataSpeedTrap) SetFastestSpeedInSession(v float32) { data.FastestSpeedInSession = v }
