// Code generated by tools/gen/accessors from event_data_collision.go. DO NOT EDIT.

package f12025

// GetVehicle1Idx returns the Vehicle1Idx of [EventDataCollision]
func (data *EventDataCollision) GetVehicle1Idx() uint8 { return data.Vehicle1Idx }

// SetVehicle1Idx stores the Vehicle1Idx of [EventDataCollision]
func (data *EventDataCollision) SetVehicle1Idx(v uint8) { data.Vehicle1Idx = v }

// GetVehicle2Idx returns the Vehicle2Idx of [EventDataCollision]
func (data *EventDataCollision) GetVehicle2Idx() uint8 { return data.Vehicle2Idx }

// SetVehicle2Idx stores the Vehicle2Idx of [EventDataCollision]
func (data *EventDataCollision) SetVehicle2Idx(v uint8) { data.Vehicle2Idx = v }
