// Code generated by tools/gen/accessors from event_data_flashback.go. DO NOT EDIT.

package f12025

// GetFlashbackFrameIdentifier returns the FlashbackFrameIdentifier of [EventDataFlashback]
func (data *EventDataFlashback) GetFlashbackFrameIdentifier() uint32 {
	return data.FlashbackFrameIdentifier
}

// SetFlashbackFrameIdentifier stores the FlashbackFrameIdentifier of [EventDataFlashback]
func (data *EventDataFlashback) SetFlashbackFrameIdentifier(v uint32) {
	data.FlashbackFrameIdentifier = v
}

// GetFlashbackSessionTime returns the FlashbackSessionTime of [EventDataFlashback]
func (data *EventDataFlashback) GetFlashbackSessionTime() float32 { return data.FlashbackSessionTime }

// SetFlashbackSessionTime stores the FlashbackSessionTime of [EventDataFlashback]
func (data *EventDataFlashback) SetFlashbackSessionTime(v float32) { data.FlashbackSessionTime = v }
