// Code generated by tools/gen/accessors from event_data_drs_disabled.go. DO NOT EDIT.

package f12025

// GetReason returns [EventDataDRSDisabled.Reason]
func (data *EventDataDRSDisabled) GetReason() uint8 { return data.Reason }

// SetReason stores [EventDataDRSDisabled.Reason]
func (data *EventDataDRSDisabled) SetReason(v uint8) { data.Reason = v }
