// Code generated by tools/gen/accessors from event_data_race_winner.go. DO NOT EDIT.

package f12025

// GetVehicleIdx returns the VehicleIdx of [EventDataRaceWinner]
func (data *EventDataRaceWinner) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores the VehicleIdx of [EventDataRaceWinner]
func (data *EventDataRaceWinner) SetVehicleIdx(v uint8) { data.VehicleIdx = v }
