// Code generated by tools/gen/accessors from event_data_overtake.go. DO NOT EDIT.

package f12025

// GetOvertakingVehicleIdx returns the OvertakingVehicleIdx of [EventDataOvertake]
func (data *EventDataOvertake) GetOvertakingVehicleIdx() uint8 { return data.OvertakingVehicleIdx }

// SetOvertakingVehicleIdx stores the OvertakingVehicleIdx of [EventDataOvertake]
func (data *EventDataOvertake) SetOvertakingVehicleIdx(v uint8) { data.OvertakingVehicleIdx = v }

// GetBeingOvertakenVehicleIdx returns the BeingOvertakenVehicleIdx of [EventDataOvertake]
func (data *EventDataOvertake) GetBeingOvertakenVehicleIdx() uint8 {
	return data.BeingOvertakenVehicleIdx
}

// SetBeingOvertakenVehicleIdx stores the BeingOvertakenVehicleIdx of [EventDataOvertake]
func (data *EventDataOvertake) SetBeingOvertakenVehicleIdx(v uint8) {
	data.BeingOvertakenVehicleIdx = v
}
