// Code generated by tools/gen/accessors from event_data_safety_car.go. DO NOT EDIT.

package f12025

// GetSafetyCarType returns the SafetyCarType of [EventDataSafetyCar]
func (data *EventDataSafetyCar) GetSafetyCarType() uint8 { return data.SafetyCarType }

// SetSafetyCarType stores the SafetyCarType of [EventDataSafetyCar]
func (data *EventDataSafetyCar) SetSafetyCarType(v uint8) { data.SafetyCarType = v }

// GetEventType returns the EventType of [EventDataSafetyCar]
func (data *EventDataSafetyCar) GetEventType() uint8 { return data.EventType }

// SetEventType stores the EventType of [EventDataSafetyCar]
func (data *EventDataSafetyCar) SetEventType(v uint8) { data.EventType = v }
