// Code generated by tools/gen/accessors from final_classification_data.go. DO NOT EDIT.

package f12025

// GetPosition returns [FinalClassificationData.Position]
func (data *FinalClassificationData) GetPosition() uint8 { return data.Position }

// SetPosition stores [FinalClassificationData.Position]
func (data *FinalClassificationData) SetPosition(v uint8) { data.Position = v }

// GetNumLaps returns [FinalClassificationData.NumLaps]
func (data *FinalClassificationData) GetNumLaps() uint8 { return data.NumLaps }

// SetNumLaps stores [FinalClassificationData.NumLaps]
func (data *FinalClassificationData) SetNumLaps(v uint8) { data.NumLaps = v }

// GetGridPosition returns [FinalClassificationData.GridPosition]
func (data *FinalClassificationData) GetGridPosition() uint8 { return data.GridPosition }

// SetGridPosition stores [FinalClassificationData.GridPosition]
func (data *FinalClassificationData) SetGridPosition(v uint8) { data.GridPosition = v }

// GetPoints returns [FinalClassificationData.Points]
func (data *FinalClassificationData) GetPoints() uint8 { return data.Points }

// SetPoints stores [FinalClassificationData.Points]
func (data *FinalClassificationData) SetPoints(v uint8) { data.Points = v }

// GetNumPitStops returns [FinalClassificationData.NumPitStops]
func (data *FinalClassificationData) GetNumPitStops() uint8 { return data.NumPitStops }

// SetNumPitStops stores [FinalClassificationData.NumPitStops]
func (data *FinalClassificationData) SetNumPitStops(v uint8) { data.NumPitStops = v }

// GetResultStatus returns [FinalClassificationData.ResultStatus]
func (data *FinalClassificationData) GetResultStatus() uint8 { return data.ResultStatus }

// SetResultStatus stores [FinalClassificationData.ResultStatus]
func (data *FinalClassificationData) SetResultStatus(v uint8) { data.ResultStatus = v }

// GetResultReason returns [FinalClassificationData.ResultReason]
func (data *FinalClassificationData) GetResultReason() uint8 { return data.ResultReason }

// SetResultReason stores [FinalClassificationData.ResultReason]
func (data *FinalClassificationData) SetResultReason(v uint8) { data.ResultReason = v }

// GetBestLapTimeInMS returns [FinalClassificationData.BestLapTimeInMS]
func (data *FinalClassificationData) GetBestLapTimeInMS() uint32 { return data.BestLapTimeInMS }

// SetBestLapTimeInMS stores [FinalClassificationData.BestLapTimeInMS]
func (data *FinalClassificationData) SetBestLapTimeInMS(v uint32) { data.BestLapTimeInMS = v }

// GetTotalRaceTime returns [FinalClassificationData.TotalRaceTime]
func (data *FinalClassificationData) GetTotalRaceTime() float64 { return data.TotalRaceTime }

// SetTotalRaceTime stores [FinalClassificationData.TotalRaceTime]
func (data *FinalClassificationData) SetTotalRaceTime(v float64) { data.TotalRaceTime = v }

// GetPenaltiesTime returns [FinalClassificationData.PenaltiesTime]
func (data *FinalClassificationData) GetPenaltiesTime() uint8 { return data.PenaltiesTime }

// SetPenaltiesTime stores [FinalClassificationData.PenaltiesTime]
func (data *FinalClassificationData) SetPenaltiesTime(v uint8) { data.PenaltiesTime = v }

// GetNumPenalties returns [FinalClassificationData.NumPenalties]
func (data *FinalClassificationData) GetNumPenalties() uint8 { return data.NumPenalties }

// SetNumPenalties stores [FinalClassificationData.NumPenalties]
func (data *FinalClassificationData) SetNumPenalties(v uint8) { data.NumPenalties = v }

// GetNumTyreStints returns [FinalClassificationData.NumTyreStints]
func (data *FinalClassificationData) GetNumTyreStints() uint8 { return data.NumTyreStints }

// SetNumTyreStints stores [FinalClassificationData.NumTyreStints]
func (data *FinalClassificationData) SetNumTyreStints(v uint8) { data.NumTyreStints = v }

// GetTyreStintsActual returns the element of [FinalClassificationData.TyreStintsActual] at index
func (data *FinalClassificationData) GetTyreStintsActual(index int) uint8 {
	return data.TyreStintsActual[index]
}

// SetTyreStintsActual stores the element of [FinalClassificationData.TyreStintsActual] at index
func (data *FinalClassificationData) SetTyreStintsActual(index int, v uint8) {
	data.TyreStintsActual[index] = v
}

// GetTyreStintsVisual returns the element of [FinalClassificationData.TyreStintsVisual] at index
func (data *FinalClassificationData) GetTyreStintsVisual(index int) uint8 {
	return data.TyreStintsVisual[index]
}

// SetTyreStintsVisual stores the element of [FinalClassificationData.TyreStintsVisual] at index
func (data *FinalClassificationData) SetTyreStintsVisual(index int, v uint8) {
	data.TyreStintsVisual[index] = v
}

// GetTyreStintsEndLaps returns the element of [FinalClassificationData.TyreStintsEndLaps] at index
func (data *FinalClassificationData) GetTyreStintsEndLaps(index int) uint8 {
	return data.TyreStintsEndLaps[index]
}

// SetTyreStintsEndLaps stores the element of [FinalClassificationData.TyreStintsEndLaps] at index
func (data *FinalClassificationData) SetTyreStintsEndLaps(index int, v uint8) {
	data.TyreStintsEndLaps[index] = v
}
