// Code generated by tools/gen/accessors from lap_data.go. DO NOT EDIT.

package f12025

// GetLastLapTimeInMS returns the LastLapTimeInMS of [LapData]
func (data *LapData) GetLastLapTimeInMS() uint32 { return data.LastLapTimeInMS }

// SetLastLapTimeInMS stores the LastLapTimeInMS of [LapData]
func (data *LapData) SetLastLapTimeInMS(v uint32) { data.LastLapTimeInMS = v }

// GetCurrentLapTimeInMS returns the CurrentLapTimeInMS of [LapData]
func (data *LapData) GetCurrentLapTimeInMS() uint32 { return data.CurrentLapTimeInMS }

// SetCurrentLapTimeInMS stores the CurrentLapTimeInMS of [LapData]
func (data *LapData) SetCurrentLapTimeInMS(v uint32) { data.CurrentLapTimeInMS = v }

// GetSector1TimeMSPart returns the Sector1TimeMSPart of [LapData]
func (data *LapData) GetSector1TimeMSPart() uint16 { return data.Sector1TimeMSPart }

// SetSector1TimeMSPart stores the Sector1TimeMSPart of [LapData]
func (data *LapData) SetSector1TimeMSPart(v uint16) { data.Sector1TimeMSPart = v }

// GetSector1TimeMinutesPart returns the Sector1TimeMinutesPart of [LapData]
func (data *LapData) GetSector1TimeMinutesPart() uint8 { return data.Sector1TimeMinutesPart }

// SetSector1TimeMinutesPart stores the Sector1TimeMinutesPart of [LapData]
func (data *LapData) SetSector1TimeMinutesPart(v uint8) { data.Sector1TimeMinutesPart = v }

// GetSector2TimeMSPart returns the Sector2TimeMSPart of [LapData]
func (data *LapData) GetSector2TimeMSPart() uint16 { return data.Sector2TimeMSPart }

// SetSector2TimeMSPart stores the Sector2TimeMSPart of [LapData]
func (data *LapData) SetSector2TimeMSPart(v uint16) { data.Sector2TimeMSPart = v }

// GetSector2TimeMinutesPart returns the Sector2TimeMinutesPart of [LapData]
func (data *LapData) GetSector2TimeMinutesPart() uint8 { return data.Sector2TimeMinutesPart }

// SetSector2TimeMinutesPart stores the Sector2TimeMinutesPart of [LapData]
func (data *LapData) SetSector2TimeMinutesPart(v uint8) { data.Sector2TimeMinutesPart = v }

// GetDeltaToCarInFrontMSPart returns the DeltaToCarInFrontMSPart of [LapData]
func (data *LapData) GetDeltaToCarInFrontMSPart() uint16 { return data.DeltaToCarInFrontMSPart }

// SetDeltaToCarInFrontMSPart stores the DeltaToCarInFrontMSPart of [LapData]
func (data *LapData) SetDeltaToCarInFrontMSPart(v uint16) { data.DeltaToCarInFrontMSPart = v }

// GetDeltaToCarInFrontMinutesPart returns the DeltaToCarInFrontMinutesPart of [LapData]
func (data *LapData) GetDeltaToCarInFrontMinutesPart() uint8 {
	return data.DeltaToCarInFrontMinutesPart
}

// SetDeltaToCarInFrontMinutesPart stores the DeltaToCarInFrontMinutesPart of [LapData]
func (data *LapData) SetDeltaToCarInFrontMinutesPart(v uint8) { data.DeltaToCarInFrontMinutesPart = v }

// GetDeltaToRaceLeaderMSPart returns the DeltaToRaceLeaderMSPart of [LapData]
func (data *LapData) GetDeltaToRaceLeaderMSPart() uint16 { return data.DeltaToRaceLeaderMSPart }

// SetDeltaToRaceLeaderMSPart stores the DeltaToRaceLeaderMSPart of [LapData]
func (data *LapData) SetDeltaToRaceLeaderMSPart(v uint16) { data.DeltaToRaceLeaderMSPart = v }

// GetDeltaToRaceLeaderMinutesPart returns the DeltaToRaceLeaderMinutesPart of [LapData]
func (data *LapData) GetDeltaToRaceLeaderMinutesPart() uint8 {
	return data.DeltaToRaceLeaderMinutesPart
}

// SetDeltaToRaceLeaderMinutesPart stores the DeltaToRaceLeaderMinutesPart of [LapData]
func (data *LapData) SetDeltaToRaceLeaderMinutesPart(v uint8) { data.DeltaToRaceLeaderMinutesPart = v }

// GetLapDistance returns the LapDistance of [LapData]
func (data *LapData) GetLapDistance() float32 { return data.LapDistance }

// SetLapDistance stores the LapDistance of [LapData]
func (data *LapData) SetLapDistance(v float32) { data.LapDistance = v }

// GetTotalDistance returns the TotalDistance of [LapData]
func (data *LapData) GetTotalDistance() float32 { return data.TotalDistance }

// SetTotalDistance stores the TotalDistance of [LapData]
func (data *LapData) SetTotalDistance(v float32) { data.TotalDistance = v }

// GetSafetyCarDelta returns the SafetyCarDelta of [LapData]
func (data *LapData) GetSafetyCarDelta() float32 { return data.SafetyCarDelta }

// SetSafetyCarDelta stores the SafetyCarDelta of [LapData]
func (data *LapData) SetSafetyCarDelta(v float32) { data.SafetyCarDelta = v }

// GetCarPosition returns the CarPosition of [LapData]
func (data *LapData) GetCarPosition() uint8 { return data.CarPosition }

// SetCarPosition stores the CarPosition of [LapData]
func (data *LapData) SetCarPosition(v uint8) { data.CarPosition = v }

// GetCurrentLapNum returns the CurrentLapNum of [LapData]
func (data *LapData) GetCurrentLapNum() uint8 { return data.CurrentLapNum }

// SetCurrentLapNum stores the CurrentLapNum of [LapData]
func (data *LapData) SetCurrentLapNum(v uint8) { data.CurrentLapNum = v }

// GetPitStatus returns the PitStatus of [LapData]
func (data *LapData) GetPitStatus() uint8 { return data.PitStatus }

// SetPitStatus stores the PitStatus of [LapData]
func (data *LapData) SetPitStatus(v uint8) { data.PitStatus = v }

// GetNumPitStops returns the NumPitStops of [LapData]
func (data *LapData) GetNumPitStops() uint8 { return data.NumPitStops }

// SetNumPitStops stores the NumPitStops of [LapData]
func (data *LapData) SetNumPitStops(v uint8) { data.NumPitStops = v }

// GetSector returns the Sector of [LapData]
func (data *LapData) GetSector() uint8 { return data.Sector }

// SetSector stores the Sector of [LapData]
func (data *LapData) SetSector(v uint8) { data.Sector = v }

// GetCurrentLapInvalid returns the CurrentLapInvalid of [LapData]
func (data *LapData) GetCurrentLapInvalid() uint8 { return data.CurrentLapInvalid }

// SetCurrentLapInvalid stores the CurrentLapInvalid of [LapData]
func (data *LapData) SetCurrentLapInvalid(v uint8) { data.CurrentLapInvalid = v }

// GetPenalties returns the Penalties of [LapData]
func (data *LapData) GetPenalties() uint8 { return data.Penalties }

// SetPenalties stores the Penalties of [LapData]
func (data *LapData) SetPenalties(v uint8) { data.Penalties = v }

// GetTotalWarnings returns the TotalWarnings of [LapData]
func (data *LapData) GetTotalWarnings() uint8 { return data.TotalWarnings }

// SetTotalWarnings stores the TotalWarnings of [LapData]
func (data *LapData) SetTotalWarnings(v uint8) { data.TotalWarnings = v }

// GetCornerCuttingWarnings returns the CornerCuttingWarnings of [LapData]
func (data *LapData) GetCornerCuttingWarnings() uint8 { return data.CornerCuttingWarnings }

// SetCornerCuttingWarnings stores the CornerCuttingWarnings of [LapData]
func (data *LapData) SetCornerCuttingWarnings(v uint8) { data.CornerCuttingWarnings = v }

// GetNumUnservedDriveThroughPens returns the NumUnservedDriveThroughPens of [LapData]
func (data *LapData) GetNumUnservedDriveThroughPens() uint8 { return data.NumUnservedDriveThroughPens }

// SetNumUnservedDriveThroughPens stores the NumUnservedDriveThroughPens of [LapData]
func (data *LapData) SetNumUnservedDriveThroughPens(v uint8) { data.NumUnservedDriveThroughPens = v }

// GetNumUnservedStopGoPens returns the NumUnservedStopGoPens of [LapData]
func (data *LapData) GetNumUnservedStopGoPens() uint8 { return data.NumUnservedStopGoPens }

// SetNumUnservedStopGoPens stores the NumUnservedStopGoPens of [LapData]
func (data *LapData) SetNumUnservedStopGoPens(v uint8) { data.NumUnservedStopGoPens = v }

// GetGridPosition returns the GridPosition of [LapData]
func (data *LapData) GetGridPosition() uint8 { return data.GridPosition }

// SetGridPosition stores the GridPosition of [LapData]
func (data *LapData) SetGridPosition(v uint8) { data.GridPosition = v }

// GetDriverStatus returns the DriverStatus of [LapData]
func (data *LapData) GetDriverStatus() uint8 { return data.DriverStatus }

// SetDriverStatus stores the DriverStatus of [LapData]
func (data *LapData) SetDriverStatus(v uint8) { data.DriverStatus = v }

// GetResultStatus returns the ResultStatus of [LapData]
func (data *LapData) GetResultStatus() uint8 { return data.ResultStatus }

// SetResultStatus stores the ResultStatus of [LapData]
func (data *LapData) SetResultStatus(v uint8) { data.ResultStatus = v }

// GetPitLaneTimerActive returns the PitLaneTimerActive of [LapData]
func (data *LapData) GetPitLaneTimerActive() uint8 { return data.PitLaneTimerActive }

// SetPitLaneTimerActive stores the PitLaneTimerActive of [LapData]
func (data *LapData) SetPitLaneTimerActive(v uint8) { data.PitLaneTimerActive = v }

// GetPitLaneTimeInLaneInMS returns the PitLaneTimeInLaneInMS of [LapData]
func (data *LapData) GetPitLaneTimeInLaneInMS() uint16 { return data.PitLaneTimeInLaneInMS }

// SetPitLaneTimeInLaneInMS stores the PitLaneTimeInLaneInMS of [LapData]
func (data *LapData) SetPitLaneTimeInLaneInMS(v uint16) { data.PitLaneTimeInLaneInMS = v }

// GetPitStopTimerInMS returns the PitStopTimerInMS of [LapData]
func (data *LapData) GetPitStopTimerInMS() uint16 { return data.PitStopTimerInMS }

// SetPitStopTimerInMS stores the PitStopTimerInMS of [LapData]
func (data *LapData) SetPitStopTimerInMS(v uint16) { data.PitStopTimerInMS = v }

// GetPitStopShouldServePen returns the PitStopShouldServePen of [LapData]
func (data *LapData) GetPitStopShouldServePen() uint8 { return data.PitStopShouldServePen }

// SetPitStopShouldServePen stores the PitStopShouldServePen of [LapData]
func (data *LapData) SetPitStopShouldServePen(v uint8) { data.PitStopShouldServePen = v }

// GetSpeedTrapFastestSpeed returns the SpeedTrapFastestSpeed of [LapData]
func (data *LapData) GetSpeedTrapFastestSpeed() float32 { return data.SpeedTrapFastestSpeed }

// SetSpeedTrapFastestSpeed stores the SpeedTrapFastestSpeed of [LapData]
func (data *LapData) SetSpeedTrapFastestSpeed(v float32) { data.SpeedTrapFastestSpeed = v }

// GetSpeedTrapFastestLap returns the SpeedTrapFastestLap of [LapData]
func (data *LapData) GetSpeedTrapFastestLap() uint8 { return data.SpeedTrapFastestLap }

// SetSpeedTrapFastestLap stores the SpeedTrapFastestLap of [LapData]
func (data *LapData) SetSpeedTrapFastestLap(v uint8) { data.SpeedTrapFastestLap = v }
