// Code generated by tools/gen/accessors from livery_colour.go. DO NOT EDIT.

package f12025

// GetRed returns [LiveryColour.Red]
func (data *LiveryColour) GetRed() uint8 { return data.Red }

// SetRed stores [LiveryColour.Red]
func (data *LiveryColour) SetRed(v uint8) { data.Red = v }

// GetGreen returns [LiveryColour.Green]
func (data *LiveryColour) GetGreen() uint8 { return data.Green }

// SetGreen stores [LiveryColour.Green]
func (data *LiveryColour) SetGreen(v uint8) { data.Green = v }

// GetBlue returns [LiveryColour.Blue]
func (data *LiveryColour) GetBlue() uint8 { return data.Blue }

// SetBlue stores [LiveryColour.Blue]
func (data *LiveryColour) SetBlue(v uint8) { data.Blue = v }
