// Code generated by tools/gen/accessors from marshal_zone.go. DO NOT EDIT.

package f12025

// GetZoneStart returns the ZoneStart of [MarshalZone]
func (data *MarshalZone) GetZoneStart() float32 { return data.ZoneStart }

// SetZoneStart stores the ZoneStart of [MarshalZone]
func (data *MarshalZone) SetZoneStart(v float32) { data.ZoneStart = v }

// GetZoneFlag returns the ZoneFlag of [MarshalZone]
func (data *MarshalZone) GetZoneFlag() int8 { return data.ZoneFlag }

// SetZoneFlag stores the ZoneFlag of [MarshalZone]
func (data *MarshalZone) SetZoneFlag(v int8) { data.ZoneFlag = v }
