// Code generated by tools/gen/accessors from packet_event_data.go. DO NOT EDIT.

package f12025

// GetHeader returns [PacketEventData.Header]
func (data *PacketEventData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketEventData.Header]
func (data *PacketEventData) SetHeader(v PacketHeader) { data.Header = v }

// GetEventStringCode returns [PacketEventData.EventStringCode]
func (data *PacketEventData) GetEventStringCode() EventCode { return data.EventStringCode }

// SetEventStringCode stores [PacketEventData.EventStringCode]
func (data *PacketEventData) SetEventStringCode(v EventCode) { data.EventStringCode = v }

// GetEventDetails returns [PacketEventData.EventDetails]
func (data *PacketEventData) GetEventDetails() EventDataDetails { return data.EventDetails }

// SetEventDetails stores [PacketEventData.EventDetails]
func (data *PacketEventData) SetEventDetails(v EventDataDetails) { data.EventDetails = v }
