// Code generated by tools/gen/accessors from packet_participants_data.go. DO NOT EDIT.

package f12025

// GetHeader returns [PacketParticipantsData.Header]
func (data *PacketParticipantsData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketParticipantsData.Header]
func (data *PacketParticipantsData) SetHeader(v PacketHeader) { data.Header = v }

// GetNumActiveCars returns [PacketParticipantsData.NumActiveCars]
func (data *PacketParticipantsData) GetNumActiveCars() uint8 { return data.NumActiveCars }

// SetNumActiveCars stores [PacketParticipantsData.NumActiveCars]
func (data *PacketParticipantsData) SetNumActiveCars(v uint8) { data.NumActiveCars = v }
