// Code generated by tools/gen/accessors from packet_car_damage_data.go. DO NOT EDIT.

package f12025

// GetHeader returns [PacketCarDamageData.Header]
func (data *PacketCarDamageData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketCarDamageData.Header]
func (data *PacketCarDamageData) SetHeader(v PacketHeader) { data.Header = v }
