// Code generated by tools/gen/accessors from packet_motion_ex_data.go. DO NOT EDIT.

package f12025

// GetHeader returns [PacketMotionExData.Header]
func (data *PacketMotionExData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketMotionExData.Header]
func (data *PacketMotionExData) SetHeader(v PacketHeader) { data.Header = v }

// GetSuspensionPosition returns [PacketMotionExData.SuspensionPosition]
func (data *PacketMotionExData) GetSuspensionPosition() WheelMap[float32] {
	return data.SuspensionPosition
}

// SetSuspensionPosition stores [PacketMotionExData.SuspensionPosition]
func (data *PacketMotionExData) SetSuspensionPosition(v WheelMap[float32]) {
	data.SuspensionPosition = v
}

// GetSuspensionVelocity returns [PacketMotionExData.SuspensionVelocity]
func (data *PacketMotionExData) GetSuspensionVelocity() WheelMap[float32] {
	return data.SuspensionVelocity
}

// SetSuspensionVelocity stores [PacketMotionExData.SuspensionVelocity]
func (data *PacketMotionExData) SetSuspensionVelocity(v WheelMap[float32]) {
	data.SuspensionVelocity = v
}

// GetSuspensionAcceleration returns [PacketMotionExData.SuspensionAcceleration]
func (data *PacketMotionExData) GetSuspensionAcceleration() WheelMap[float32] {
	return data.SuspensionAcceleration
}

// SetSuspensionAcceleration stores [PacketMotionExData.SuspensionAcceleration]
func (data *PacketMotionExData) SetSuspensionAcceleration(v WheelMap[float32]) {
	data.SuspensionAcceleration = v
}

// GetWheelSpeed returns [PacketMotionExData.WheelSpeed]
func (data *PacketMotionExData) GetWheelSpeed() WheelMap[float32] { return data.WheelSpeed }

// SetWheelSpeed stores [PacketMotionExData.WheelSpeed]
func (data *PacketMotionExData) SetWheelSpeed(v WheelMap[float32]) { data.WheelSpeed = v }

// GetWheelSlipRatio returns [PacketMotionExData.WheelSlipRatio]
func (data *PacketMotionExData) GetWheelSlipRatio() WheelMap[float32] { return data.WheelSlipRatio }

// SetWheelSlipRatio stores [PacketMotionExData.WheelSlipRatio]
func (data *PacketMotionExData) SetWheelSlipRatio(v WheelMap[float32]) { data.WheelSlipRatio = v }

// GetWheelSlipAngle returns [PacketMotionExData.WheelSlipAngle]
func (data *PacketMotionExData) GetWheelSlipAngle() WheelMap[float32] { return data.WheelSlipAngle }

// SetWheelSlipAngle stores [PacketMotionExData.WheelSlipAngle]
func (data *PacketMotionExData) SetWheelSlipAngle(v WheelMap[float32]) { data.WheelSlipAngle = v }

// GetWheelLatForce returns [PacketMotionExData.WheelLatForce]
func (data *PacketMotionExData) GetWheelLatForce() WheelMap[float32] { return data.WheelLatForce }

// SetWheelLatForce stores [PacketMotionExData.WheelLatForce]
func (data *PacketMotionExData) SetWheelLatForce(v WheelMap[float32]) { data.WheelLatForce = v }

// GetWheelLongForce returns [PacketMotionExData.WheelLongForce]
func (data *PacketMotionExData) GetWheelLongForce() WheelMap[float32] { return data.WheelLongForce }

// SetWheelLongForce stores [PacketMotionExData.WheelLongForce]
func (data *PacketMotionExData) SetWheelLongForce(v WheelMap[float32]) { data.WheelLongForce = v }

// GetHeightOfCOGAboveGround returns [PacketMotionExData.HeightOfCOGAboveGround]
func (data *PacketMotionExData) GetHeightOfCOGAboveGround() float32 {
	return data.HeightOfCOGAboveGround
}

// SetHeightOfCOGAboveGround stores [PacketMotionExData.HeightOfCOGAboveGround]
func (data *PacketMotionExData) SetHeightOfCOGAboveGround(v float32) { data.HeightOfCOGAboveGround = v }

// GetLocalVelocityX returns [PacketMotionExData.LocalVelocityX]
func (data *PacketMotionExData) GetLocalVelocityX() float32 { return data.LocalVelocityX }

// SetLocalVelocityX stores [PacketMotionExData.LocalVelocityX]
func (data *PacketMotionExData) SetLocalVelocityX(v float32) { data.LocalVelocityX = v }

// GetLocalVelocityY returns [PacketMotionExData.LocalVelocityY]
func (data *PacketMotionExData) GetLocalVelocityY() float32 { return data.LocalVelocityY }

// SetLocalVelocityY stores [PacketMotionExData.LocalVelocityY]
func (data *PacketMotionExData) SetLocalVelocityY(v float32) { data.LocalVelocityY = v }

// GetLocalVelocityZ returns [PacketMotionExData.LocalVelocityZ]
func (data *PacketMotionExData) GetLocalVelocityZ() float32 { return data.LocalVelocityZ }

// SetLocalVelocityZ stores [PacketMotionExData.LocalVelocityZ]
func (data *PacketMotionExData) SetLocalVelocityZ(v float32) { data.LocalVelocityZ = v }

// GetAngularVelocityX returns [PacketMotionExData.AngularVelocityX]
func (data *PacketMotionExData) GetAngularVelocityX() float32 { return data.AngularVelocityX }

// SetAngularVelocityX stores [PacketMotionExData.AngularVelocityX]
func (data *PacketMotionExData) SetAngularVelocityX(v float32) { data.AngularVelocityX = v }

// GetAngularVelocityY returns [PacketMotionExData.AngularVelocityY]
func (data *PacketMotionExData) GetAngularVelocityY() float32 { return data.AngularVelocityY }

// SetAngularVelocityY stores [PacketMotionExData.AngularVelocityY]
func (data *PacketMotionExData) SetAngularVelocityY(v float32) { data.AngularVelocityY = v }

// GetAngularVelocityZ returns [PacketMotionExData.AngularVelocityZ]
func (data *PacketMotionExData) GetAngularVelocityZ() float32 { return data.AngularVelocityZ }

// SetAngularVelocityZ stores [PacketMotionExData.AngularVelocityZ]
func (data *PacketMotionExData) SetAngularVelocityZ(v float32) { data.AngularVelocityZ = v }

// GetAngularAccelerationX returns [PacketMotionExData.AngularAccelerationX]
func (data *PacketMotionExData) GetAngularAccelerationX() float32 { return data.AngularAccelerationX }

// SetAngularAccelerationX stores [PacketMotionExData.AngularAccelerationX]
func (data *PacketMotionExData) SetAngularAccelerationX(v float32) { data.AngularAccelerationX = v }

// GetAngularAccelerationY returns [PacketMotionExData.AngularAccelerationY]
func (data *PacketMotionExData) GetAngularAccelerationY() float32 { return data.AngularAccelerationY }

// SetAngularAccelerationY stores [PacketMotionExData.AngularAccelerationY]
func (data *PacketMotionExData) SetAngularAccelerationY(v float32) { data.AngularAccelerationY = v }

// GetAngularAccelerationZ returns [PacketMotionExData.AngularAccelerationZ]
func (data *PacketMotionExData) GetAngularAccelerationZ() float32 { return data.AngularAccelerationZ }

// SetAngularAccelerationZ stores [PacketMotionExData.AngularAccelerationZ]
func (data *PacketMotionExData) SetAngularAccelerationZ(v float32) { data.AngularAccelerationZ = v }

// GetFrontWheelsAngle returns [PacketMotionExData.FrontWheelsAngle]
func (data *PacketMotionExData) GetFrontWheelsAngle() float32 { return data.FrontWheelsAngle }

// SetFrontWheelsAngle stores [PacketMotionExData.FrontWheelsAngle]
func (data *PacketMotionExData) SetFrontWheelsAngle(v float32) { data.FrontWheelsAngle = v }

// GetWheelVertForce returns [PacketMotionExData.WheelVertForce]
func (data *PacketMotionExData) GetWheelVertForce() WheelMap[float32] { return data.WheelVertForce }

// SetWheelVertForce stores [PacketMotionExData.WheelVertForce]
func (data *PacketMotionExData) SetWheelVertForce(v WheelMap[float32]) { data.WheelVertForce = v }

// GetFrontAeroHeight returns [PacketMotionExData.FrontAeroHeight]
func (data *PacketMotionExData) GetFrontAeroHeight() float32 { return data.FrontAeroHeight }

// SetFrontAeroHeight stores [PacketMotionExData.FrontAeroHeight]
func (data *PacketMotionExData) SetFrontAeroHeight(v float32) { data.FrontAeroHeight = v }

// GetRearAeroHeight returns [PacketMotionExData.RearAeroHeight]
func (data *PacketMotionExData) GetRearAeroHeight() float32 { return data.RearAeroHeight }

// SetRearAeroHeight stores [PacketMotionExData.RearAeroHeight]
func (data *PacketMotionExData) SetRearAeroHeight(v float32) { data.RearAeroHeight = v }

// GetFrontRollAngle returns [PacketMotionExData.FrontRollAngle]
func (data *PacketMotionExData) GetFrontRollAngle() float32 { return data.FrontRollAngle }

// SetFrontRollAngle stores [PacketMotionExData.FrontRollAngle]
func (data *PacketMotionExData) SetFrontRollAngle(v float32) { data.FrontRollAngle = v }

// GetRearRollAngle returns [PacketMotionExData.RearRollAngle]
func (data *PacketMotionExData) GetRearRollAngle() float32 { return data.RearRollAngle }

// SetRearRollAngle stores [PacketMotionExData.RearRollAngle]
func (data *PacketMotionExData) SetRearRollAngle(v float32) { data.RearRollAngle = v }

// GetChassisYaw returns [PacketMotionExData.ChassisYaw]
func (data *PacketMotionExData) GetChassisYaw() float32 { return data.ChassisYaw }

// SetChassisYaw stores [PacketMotionExData.ChassisYaw]
func (data *PacketMotionExData) SetChassisYaw(v float32) { data.ChassisYaw = v }

// GetChassisPitch returns [PacketMotionExData.ChassisPitch]
func (data *PacketMotionExData) GetChassisPitch() float32 { return data.ChassisPitch }

// SetChassisPitch stores [PacketMotionExData.ChassisPitch]
func (data *PacketMotionExData) SetChassisPitch(v float32) { data.ChassisPitch = v }

// GetWheelCamber returns [PacketMotionExData.WheelCamber]
func (data *PacketMotionExData) GetWheelCamber() WheelMap[float32] { return data.WheelCamber }

// SetWheelCamber stores [PacketMotionExData.WheelCamber]
func (data *PacketMotionExData) SetWheelCamber(v WheelMap[float32]) { data.WheelCamber = v }

// GetWheelCamberGain returns [PacketMotionExData.WheelCamberGain]
func (data *PacketMotionExData) GetWheelCamberGain() WheelMap[float32] { return data.WheelCamberGain }

// SetWheelCamberGain stores [PacketMotionExData.WheelCamberGain]
func (data *PacketMotionExData) SetWheelCamberGain(v WheelMap[float32]) { data.WheelCamberGain = v }
