// Code generated by tools/gen/accessors from packet_lap_positions_data.go. DO NOT EDIT.

package f12025

// GetHeader returns the Header of [PacketLapPositionsData]
func (data *PacketLapPositionsData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketLapPositionsData]
func (data *PacketLapPositionsData) SetHeader(v PacketHeader) { data.Header = v }

// GetNumLaps returns the NumLaps of [PacketLapPositionsData]
func (data *PacketLapPositionsData) GetNumLaps() uint8 { return data.NumLaps }

// SetNumLaps stores the NumLaps of [PacketLapPositionsData]
func (data *PacketLapPositionsData) SetNumLaps(v uint8) { data.NumLaps = v }

// GetLapStart returns the LapStart of [PacketLapPositionsData]
func (data *PacketLapPositionsData) GetLapStart() uint8 { return data.LapStart }

// SetLapStart stores the LapStart of [PacketLapPositionsData]
func (data *PacketLapPositionsData) SetLapStart(v uint8) { data.LapStart = v }
