// Code generated by tools/gen/accessors from packet_motion_data.go. DO NOT EDIT.

package f12025

// GetHeader returns [PacketMotionData.Header]
func (data *PacketMotionData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketMotionData.Header]
func (data *PacketMotionData) SetHeader(v PacketHeader) { data.Header = v }
