// Code generated by tools/gen/accessors from packet_participants_data.go. DO NOT EDIT.

package f12025

// GetHeader returns the Header of [PacketParticipantsData]
func (data *PacketParticipantsData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketParticipantsData]
func (data *PacketParticipantsData) SetHeader(v PacketHeader) { data.Header = v }

// GetNumActiveCars returns the NumActiveCars of [PacketParticipantsData]
func (data *PacketParticipantsData) GetNumActiveCars() uint8 { return data.NumActiveCars }

// SetNumActiveCars stores the NumActiveCars of [PacketParticipantsData]
func (data *PacketParticipantsData) SetNumActiveCars(v uint8) { data.NumActiveCars = v }
