// Code generated by tools/gen/accessors from packet_session_history_data.go. DO NOT EDIT.

package f12025

// GetHeader returns the Header of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) SetHeader(v PacketHeader) { data.Header = v }

// GetCarIdx returns the CarIdx of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) GetCarIdx() uint8 { return data.CarIdx }

// SetCarIdx stores the CarIdx of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) SetCarIdx(v uint8) { data.CarIdx = v }

// GetNumLaps returns the NumLaps of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) GetNumLaps() uint8 { return data.NumLaps }

// SetNumLaps stores the NumLaps of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) SetNumLaps(v uint8) { data.NumLaps = v }

// GetNumTyreStints returns the NumTyreStints of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) GetNumTyreStints() uint8 { return data.NumTyreStints }

// SetNumTyreStints stores the NumTyreStints of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) SetNumTyreStints(v uint8) { data.NumTyreStints = v }

// GetBestLapTimeLapNum returns the BestLapTimeLapNum of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) GetBestLapTimeLapNum() uint8 { return data.BestLapTimeLapNum }

// SetBestLapTimeLapNum stores the BestLapTimeLapNum of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) SetBestLapTimeLapNum(v uint8) { data.BestLapTimeLapNum = v }

// GetBestSector1LapNum returns the BestSector1LapNum of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) GetBestSector1LapNum() uint8 { return data.BestSector1LapNum }

// SetBestSector1LapNum stores the BestSector1LapNum of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) SetBestSector1LapNum(v uint8) { data.BestSector1LapNum = v }

// GetBestSector2LapNum returns the BestSector2LapNum of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) GetBestSector2LapNum() uint8 { return data.BestSector2LapNum }

// SetBestSector2LapNum stores the BestSector2LapNum of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) SetBestSector2LapNum(v uint8) { data.BestSector2LapNum = v }

// GetBestSector3LapNum returns the BestSector3LapNum of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) GetBestSector3LapNum() uint8 { return data.BestSector3LapNum }

// SetBestSector3LapNum stores the BestSector3LapNum of [PacketSessionHistoryData]
func (data *PacketSessionHistoryData) SetBestSector3LapNum(v uint8) { data.BestSector3LapNum = v }

// GetTyreStintsHistoryData returns the TyreStintsHistoryData element of [PacketSessionHistoryData] at index
func (data *PacketSessionHistoryData) GetTyreStintsHistoryData(index int) TyreStintHistoryData {
	return data.TyreStintsHistoryData[index]
}

// SetTyreStintsHistoryData stores the TyreStintsHistoryData element of [PacketSessionHistoryData] at index
func (data *PacketSessionHistoryData) SetTyreStintsHistoryData(index int, v TyreStintHistoryData) {
	data.TyreStintsHistoryData[index] = v
}
