// Code generated by tools/gen/accessors from packet_lobby_info_data.go. DO NOT EDIT.

package f12025

// GetHeader returns [PacketLobbyInfoData.Header]
func (data *PacketLobbyInfoData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketLobbyInfoData.Header]
func (data *PacketLobbyInfoData) SetHeader(v PacketHeader) { data.Header = v }

// GetNumPlayers returns [PacketLobbyInfoData.NumPlayers]
func (data *PacketLobbyInfoData) GetNumPlayers() uint8 { return data.NumPlayers }

// SetNumPlayers stores [PacketLobbyInfoData.NumPlayers]
func (data *PacketLobbyInfoData) SetNumPlayers(v uint8) { data.NumPlayers = v }
