// Code generated by tools/gen/accessors from packet_lap_positions_data.go. DO NOT EDIT.

package f12025

// GetHeader returns [PacketLapPositionsData.Header]
func (data *PacketLapPositionsData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketLapPositionsData.Header]
func (data *PacketLapPositionsData) SetHeader(v PacketHeader) { data.Header = v }

// GetNumLaps returns [PacketLapPositionsData.NumLaps]
func (data *PacketLapPositionsData) GetNumLaps() uint8 { return data.NumLaps }

// SetNumLaps stores [PacketLapPositionsData.NumLaps]
func (data *PacketLapPositionsData) SetNumLaps(v uint8) { data.NumLaps = v }

// GetLapStart returns [PacketLapPositionsData.LapStart]
func (data *PacketLapPositionsData) GetLapStart() uint8 { return data.LapStart }

// SetLapStart stores [PacketLapPositionsData.LapStart]
func (data *PacketLapPositionsData) SetLapStart(v uint8) { data.LapStart = v }
