// Code generated by tools/gen/accessors from packet_car_setup_data.go. DO NOT EDIT.

package f12025

// GetHeader returns the Header of [PacketCarSetupData]
func (data *PacketCarSetupData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketCarSetupData]
func (data *PacketCarSetupData) SetHeader(v PacketHeader) { data.Header = v }

// GetNextFrontWingValue returns the NextFrontWingValue of [PacketCarSetupData]
func (data *PacketCarSetupData) GetNextFrontWingValue() float32 { return data.NextFrontWingValue }

// SetNextFrontWingValue stores the NextFrontWingValue of [PacketCarSetupData]
func (data *PacketCarSetupData) SetNextFrontWingValue(v float32) { data.NextFrontWingValue = v }
