// Code generated by tools/gen/accessors from tyre_stint_history_data.go. DO NOT EDIT.

package f12025

// GetEndLap returns [TyreStintHistoryData.EndLap]
func (data *TyreStintHistoryData) GetEndLap() uint8 { return data.EndLap }

// SetEndLap stores [TyreStintHistoryData.EndLap]
func (data *TyreStintHistoryData) SetEndLap(v uint8) { data.EndLap = v }

// GetTyreActualCompound returns [TyreStintHistoryData.TyreActualCompound]
func (data *TyreStintHistoryData) GetTyreActualCompound() uint8 { return data.TyreActualCompound }

// SetTyreActualCompound stores [TyreStintHistoryData.TyreActualCompound]
func (data *TyreStintHistoryData) SetTyreActualCompound(v uint8) { data.TyreActualCompound = v }

// GetTyreVisualCompound returns [TyreStintHistoryData.TyreVisualCompound]
func (data *TyreStintHistoryData) GetTyreVisualCompound() uint8 { return data.TyreVisualCompound }

// SetTyreVisualCompound stores [TyreStintHistoryData.TyreVisualCompound]
func (data *TyreStintHistoryData) SetTyreVisualCompound(v uint8) { data.TyreVisualCompound = v }
