// Code generated by tools/gen/accessors from weather_forecast_sample.go. DO NOT EDIT.

package f12025

// GetSessionType returns [WeatherForecastSample.SessionType]
func (data *WeatherForecastSample) GetSessionType() uint8 { return data.SessionType }

// SetSessionType stores [WeatherForecastSample.SessionType]
func (data *WeatherForecastSample) SetSessionType(v uint8) { data.SessionType = v }

// GetTimeOffset returns [WeatherForecastSample.TimeOffset]
func (data *WeatherForecastSample) GetTimeOffset() uint8 { return data.TimeOffset }

// SetTimeOffset stores [WeatherForecastSample.TimeOffset]
func (data *WeatherForecastSample) SetTimeOffset(v uint8) { data.TimeOffset = v }

// GetWeather returns [WeatherForecastSample.Weather]
func (data *WeatherForecastSample) GetWeather() uint8 { return data.Weather }

// SetWeather stores [WeatherForecastSample.Weather]
func (data *WeatherForecastSample) SetWeather(v uint8) { data.Weather = v }

// GetTrackTemperature returns [WeatherForecastSample.TrackTemperature]
func (data *WeatherForecastSample) GetTrackTemperature() int8 { return data.TrackTemperature }

// SetTrackTemperature stores [WeatherForecastSample.TrackTemperature]
func (data *WeatherForecastSample) SetTrackTemperature(v int8) { data.TrackTemperature = v }

// GetTrackTemperatureChange returns [WeatherForecastSample.TrackTemperatureChange]
func (data *WeatherForecastSample) GetTrackTemperatureChange() int8 {
	return data.TrackTemperatureChange
}

// SetTrackTemperatureChange stores [WeatherForecastSample.TrackTemperatureChange]
func (data *WeatherForecastSample) SetTrackTemperatureChange(v int8) { data.TrackTemperatureChange = v }

// GetAirTemperature returns [WeatherForecastSample.AirTemperature]
func (data *WeatherForecastSample) GetAirTemperature() int8 { return data.AirTemperature }

// SetAirTemperature stores [WeatherForecastSample.AirTemperature]
func (data *WeatherForecastSample) SetAirTemperature(v int8) { data.AirTemperature = v }

// GetAirTemperatureChange returns [WeatherForecastSample.AirTemperatureChange]
func (data *WeatherForecastSample) GetAirTemperatureChange() int8 { return data.AirTemperatureChange }

// SetAirTemperatureChange stores [WeatherForecastSample.AirTemperatureChange]
func (data *WeatherForecastSample) SetAirTemperatureChange(v int8) { data.AirTemperatureChange = v }

// GetRainPercentage returns [WeatherForecastSample.RainPercentage]
func (data *WeatherForecastSample) GetRainPercentage() uint8 { return data.RainPercentage }

// SetRainPercentage stores [WeatherForecastSample.RainPercentage]
func (data *WeatherForecastSample) SetRainPercentage(v uint8) { data.RainPercentage = v }
