// Code generated by tools/gen/accessors from car_telemetry_data.go. DO NOT EDIT.

package f12024

// GetSpeed returns [CarTelemetryData.Speed]
func (data *CarTelemetryData) GetSpeed() uint16 { return data.Speed }

// SetSpeed stores [CarTelemetryData.Speed]
func (data *CarTelemetryData) SetSpeed(v uint16) { data.Speed = v }

// GetThrottle returns [CarTelemetryData.Throttle]
func (data *CarTelemetryData) GetThrottle() float32 { return data.Throttle }

// SetThrottle stores [CarTelemetryData.Throttle]
func (data *CarTelemetryData) SetThrottle(v float32) { data.Throttle = v }

// GetSteer returns [CarTelemetryData.Steer]
func (data *CarTelemetryData) GetSteer() float32 { return data.Steer }

// SetSteer stores [CarTelemetryData.Steer]
func (data *CarTelemetryData) SetSteer(v float32) { data.Steer = v }

// GetBrake returns [CarTelemetryData.Brake]
func (data *CarTelemetryData) GetBrake() float32 { return data.Brake }

// SetBrake stores [CarTelemetryData.Brake]
func (data *CarTelemetryData) SetBrake(v float32) { data.Brake = v }

// GetClutch returns [CarTelemetryData.Clutch]
func (data *CarTelemetryData) GetClutch() uint8 { return data.Clutch }

// SetClutch stores [CarTelemetryData.Clutch]
func (data *CarTelemetryData) SetClutch(v uint8) { data.Clutch = v }

// GetGear returns [CarTelemetryData.Gear]
func (data *CarTelemetryData) GetGear() int8 { return data.Gear }

// SetGear stores [CarTelemetryData.Gear]
func (data *CarTelemetryData) SetGear(v int8) { data.Gear = v }

// GetEngineRPM returns [CarTelemetryData.EngineRPM]
func (data *CarTelemetryData) GetEngineRPM() uint16 { return data.EngineRPM }

// SetEngineRPM stores [CarTelemetryData.EngineRPM]
func (data *CarTelemetryData) SetEngineRPM(v uint16) { data.EngineRPM = v }

// GetDRS returns [CarTelemetryData.DRS]
func (data *CarTelemetryData) GetDRS() uint8 { return data.DRS }

// SetDRS stores [CarTelemetryData.DRS]
func (data *CarTelemetryData) SetDRS(v uint8) { data.DRS = v }

// GetRevLightsPercent returns [CarTelemetryData.RevLightsPercent]
func (data *CarTelemetryData) GetRevLightsPercent() uint8 { return data.RevLightsPercent }

// SetRevLightsPercent stores [CarTelemetryData.RevLightsPercent]
func (data *CarTelemetryData) SetRevLightsPercent(v uint8) { data.RevLightsPercent = v }

// GetRevLightsBitValue returns [CarTelemetryData.RevLightsBitValue]
func (data *CarTelemetryData) GetRevLightsBitValue() uint16 { return data.RevLightsBitValue }

// SetRevLightsBitValue stores [CarTelemetryData.RevLightsBitValue]
func (data *CarTelemetryData) SetRevLightsBitValue(v uint16) { data.RevLightsBitValue = v }

// GetBrakesTemperature returns [CarTelemetryData.BrakesTemperature]
func (data *CarTelemetryData) GetBrakesTemperature() WheelMap[uint16] { return data.BrakesTemperature }

// SetBrakesTemperature stores [CarTelemetryData.BrakesTemperature]
func (data *CarTelemetryData) SetBrakesTemperature(v WheelMap[uint16]) { data.BrakesTemperature = v }

// GetTyresSurfaceTemperature returns [CarTelemetryData.TyresSurfaceTemperature]
func (data *CarTelemetryData) GetTyresSurfaceTemperature() WheelMap[uint8] {
	return data.TyresSurfaceTemperature
}

// SetTyresSurfaceTemperature stores [CarTelemetryData.TyresSurfaceTemperature]
func (data *CarTelemetryData) SetTyresSurfaceTemperature(v WheelMap[uint8]) {
	data.TyresSurfaceTemperature = v
}

// GetTyresInnerTemperature returns [CarTelemetryData.TyresInnerTemperature]
func (data *CarTelemetryData) GetTyresInnerTemperature() WheelMap[uint8] {
	return data.TyresInnerTemperature
}

// SetTyresInnerTemperature stores [CarTelemetryData.TyresInnerTemperature]
func (data *CarTelemetryData) SetTyresInnerTemperature(v WheelMap[uint8]) {
	data.TyresInnerTemperature = v
}

// GetEngineTemperature returns [CarTelemetryData.EngineTemperature]
func (data *CarTelemetryData) GetEngineTemperature() uint16 { return data.EngineTemperature }

// SetEngineTemperature stores [CarTelemetryData.EngineTemperature]
func (data *CarTelemetryData) SetEngineTemperature(v uint16) { data.EngineTemperature = v }

// GetTyresPressure returns [CarTelemetryData.TyresPressure]
func (data *CarTelemetryData) GetTyresPressure() WheelMap[float32] { return data.TyresPressure }

// SetTyresPressure stores [CarTelemetryData.TyresPressure]
func (data *CarTelemetryData) SetTyresPressure(v WheelMap[float32]) { data.TyresPressure = v }

// GetSurfaceType returns [CarTelemetryData.SurfaceType]
func (data *CarTelemetryData) GetSurfaceType() WheelMap[uint8] { return data.SurfaceType }

// SetSurfaceType stores [CarTelemetryData.SurfaceType]
func (data *CarTelemetryData) SetSurfaceType(v WheelMap[uint8]) { data.SurfaceType = v }
