// Code generated by tools/gen/accessors from car_motion_data.go. DO NOT EDIT.

package f12024

// GetWorldPositionX returns [CarMotionData.WorldPositionX]
func (data *CarMotionData) GetWorldPositionX() float32 { return data.WorldPositionX }

// SetWorldPositionX stores [CarMotionData.WorldPositionX]
func (data *CarMotionData) SetWorldPositionX(v float32) { data.WorldPositionX = v }

// GetWorldPositionY returns [CarMotionData.WorldPositionY]
func (data *CarMotionData) GetWorldPositionY() float32 { return data.WorldPositionY }

// SetWorldPositionY stores [CarMotionData.WorldPositionY]
func (data *CarMotionData) SetWorldPositionY(v float32) { data.WorldPositionY = v }

// GetWorldPositionZ returns [CarMotionData.WorldPositionZ]
func (data *CarMotionData) GetWorldPositionZ() float32 { return data.WorldPositionZ }

// SetWorldPositionZ stores [CarMotionData.WorldPositionZ]
func (data *CarMotionData) SetWorldPositionZ(v float32) { data.WorldPositionZ = v }

// GetWorldVelocityX returns [CarMotionData.WorldVelocityX]
func (data *CarMotionData) GetWorldVelocityX() float32 { return data.WorldVelocityX }

// SetWorldVelocityX stores [CarMotionData.WorldVelocityX]
func (data *CarMotionData) SetWorldVelocityX(v float32) { data.WorldVelocityX = v }

// GetWorldVelocityY returns [CarMotionData.WorldVelocityY]
func (data *CarMotionData) GetWorldVelocityY() float32 { return data.WorldVelocityY }

// SetWorldVelocityY stores [CarMotionData.WorldVelocityY]
func (data *CarMotionData) SetWorldVelocityY(v float32) { data.WorldVelocityY = v }

// GetWorldVelocityZ returns [CarMotionData.WorldVelocityZ]
func (data *CarMotionData) GetWorldVelocityZ() float32 { return data.WorldVelocityZ }

// SetWorldVelocityZ stores [CarMotionData.WorldVelocityZ]
func (data *CarMotionData) SetWorldVelocityZ(v float32) { data.WorldVelocityZ = v }

// GetWorldForwardDirX returns [CarMotionData.WorldForwardDirX]
func (data *CarMotionData) GetWorldForwardDirX() int16 { return data.WorldForwardDirX }

// SetWorldForwardDirX stores [CarMotionData.WorldForwardDirX]
func (data *CarMotionData) SetWorldForwardDirX(v int16) { data.WorldForwardDirX = v }

// GetWorldForwardDirY returns [CarMotionData.WorldForwardDirY]
func (data *CarMotionData) GetWorldForwardDirY() int16 { return data.WorldForwardDirY }

// SetWorldForwardDirY stores [CarMotionData.WorldForwardDirY]
func (data *CarMotionData) SetWorldForwardDirY(v int16) { data.WorldForwardDirY = v }

// GetWorldForwardDirZ returns [CarMotionData.WorldForwardDirZ]
func (data *CarMotionData) GetWorldForwardDirZ() int16 { return data.WorldForwardDirZ }

// SetWorldForwardDirZ stores [CarMotionData.WorldForwardDirZ]
func (data *CarMotionData) SetWorldForwardDirZ(v int16) { data.WorldForwardDirZ = v }

// GetWorldRightDirX returns [CarMotionData.WorldRightDirX]
func (data *CarMotionData) GetWorldRightDirX() int16 { return data.WorldRightDirX }

// SetWorldRightDirX stores [CarMotionData.WorldRightDirX]
func (data *CarMotionData) SetWorldRightDirX(v int16) { data.WorldRightDirX = v }

// GetWorldRightDirY returns [CarMotionData.WorldRightDirY]
func (data *CarMotionData) GetWorldRightDirY() int16 { return data.WorldRightDirY }

// SetWorldRightDirY stores [CarMotionData.WorldRightDirY]
func (data *CarMotionData) SetWorldRightDirY(v int16) { data.WorldRightDirY = v }

// GetWorldRightDirZ returns [CarMotionData.WorldRightDirZ]
func (data *CarMotionData) GetWorldRightDirZ() int16 { return data.WorldRightDirZ }

// SetWorldRightDirZ stores [CarMotionData.WorldRightDirZ]
func (data *CarMotionData) SetWorldRightDirZ(v int16) { data.WorldRightDirZ = v }

// GetGForceLateral returns [CarMotionData.GForceLateral]
func (data *CarMotionData) GetGForceLateral() float32 { return data.GForceLateral }

// SetGForceLateral stores [CarMotionData.GForceLateral]
func (data *CarMotionData) SetGForceLateral(v float32) { data.GForceLateral = v }

// GetGForceLongitudinal returns [CarMotionData.GForceLongitudinal]
func (data *CarMotionData) GetGForceLongitudinal() float32 { return data.GForceLongitudinal }

// SetGForceLongitudinal stores [CarMotionData.GForceLongitudinal]
func (data *CarMotionData) SetGForceLongitudinal(v float32) { data.GForceLongitudinal = v }

// GetGForceVertical returns [CarMotionData.GForceVertical]
func (data *CarMotionData) GetGForceVertical() float32 { return data.GForceVertical }

// SetGForceVertical stores [CarMotionData.GForceVertical]
func (data *CarMotionData) SetGForceVertical(v float32) { data.GForceVertical = v }

// GetYaw returns [CarMotionData.Yaw]
func (data *CarMotionData) GetYaw() float32 { return data.Yaw }

// SetYaw stores [CarMotionData.Yaw]
func (data *CarMotionData) SetYaw(v float32) { data.Yaw = v }

// GetPitch returns [CarMotionData.Pitch]
func (data *CarMotionData) GetPitch() float32 { return data.Pitch }

// SetPitch stores [CarMotionData.Pitch]
func (data *CarMotionData) SetPitch(v float32) { data.Pitch = v }

// GetRoll returns [CarMotionData.Roll]
func (data *CarMotionData) GetRoll() float32 { return data.Roll }

// SetRoll stores [CarMotionData.Roll]
func (data *CarMotionData) SetRoll(v float32) { data.Roll = v }
