// Code generated by tools/gen/accessors from event_data_retirement.go. DO NOT EDIT.

package f12024

// GetVehicleIdx returns [EventDataRetirement.VehicleIdx]
func (data *EventDataRetirement) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores [EventDataRetirement.VehicleIdx]
func (data *EventDataRetirement) SetVehicleIdx(v uint8) { data.VehicleIdx = v }
