// Code generated by tools/gen/accessors from event_data_drive_through_penalty_served.go. DO NOT EDIT.

package f12024

// GetVehicleIdx returns [EventDataDriveThroughPenaltyServed.VehicleIdx]
func (data *EventDataDriveThroughPenaltyServed) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores [EventDataDriveThroughPenaltyServed.VehicleIdx]
func (data *EventDataDriveThroughPenaltyServed) SetVehicleIdx(v uint8) { data.VehicleIdx = v }
