// Code generated by tools/gen/accessors from event_data_overtake.go. DO NOT EDIT.

package f12024

// GetOvertakingVehicleIdx returns [EventDataOvertake.OvertakingVehicleIdx]
func (data *EventDataOvertake) GetOvertakingVehicleIdx() uint8 { return data.OvertakingVehicleIdx }

// SetOvertakingVehicleIdx stores [EventDataOvertake.OvertakingVehicleIdx]
func (data *EventDataOvertake) SetOvertakingVehicleIdx(v uint8) { data.OvertakingVehicleIdx = v }

// GetBeingOvertakenVehicleIdx returns [EventDataOvertake.BeingOvertakenVehicleIdx]
func (data *EventDataOvertake) GetBeingOvertakenVehicleIdx() uint8 {
	return data.BeingOvertakenVehicleIdx
}

// SetBeingOvertakenVehicleIdx stores [EventDataOvertake.BeingOvertakenVehicleIdx]
func (data *EventDataOvertake) SetBeingOvertakenVehicleIdx(v uint8) {
	data.BeingOvertakenVehicleIdx = v
}
