// Code generated by tools/gen/accessors from event_data_stop_go_penalty_served.go. DO NOT EDIT.

package f12024

// GetVehicleIdx returns [EventDataStopGoPenaltyServed.VehicleIdx]
func (data *EventDataStopGoPenaltyServed) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores [EventDataStopGoPenaltyServed.VehicleIdx]
func (data *EventDataStopGoPenaltyServed) SetVehicleIdx(v uint8) { data.VehicleIdx = v }
