// Code generated by tools/gen/accessors from event_data_start_lights.go. DO NOT EDIT.

package f12024

// GetNumLights returns [EventDataStartLights.NumLights]
func (data *EventDataStartLights) GetNumLights() uint8 { return data.NumLights }

// SetNumLights stores [EventDataStartLights.NumLights]
func (data *EventDataStartLights) SetNumLights(v uint8) { data.NumLights = v }
