// Code generated by tools/gen/accessors from event_data_safety_car.go. DO NOT EDIT.

package f12024

// GetSafetyCarType returns [EventDataSafetyCar.SafetyCarType]
func (data *EventDataSafetyCar) GetSafetyCarType() uint8 { return data.SafetyCarType }

// SetSafetyCarType stores [EventDataSafetyCar.SafetyCarType]
func (data *EventDataSafetyCar) SetSafetyCarType(v uint8) { data.SafetyCarType = v }

// GetEventType returns [EventDataSafetyCar.EventType]
func (data *EventDataSafetyCar) GetEventType() uint8 { return data.EventType }

// SetEventType stores [EventDataSafetyCar.EventType]
func (data *EventDataSafetyCar) SetEventType(v uint8) { data.EventType = v }
