// Code generated by tools/gen/accessors from event_data_penalty.go. DO NOT EDIT.

package f12024

// GetPenaltyType returns [EventDataPenalty.PenaltyType]
func (data *EventDataPenalty) GetPenaltyType() uint8 { return data.PenaltyType }

// SetPenaltyType stores [EventDataPenalty.PenaltyType]
func (data *EventDataPenalty) SetPenaltyType(v uint8) { data.PenaltyType = v }

// GetInfringementType returns [EventDataPenalty.InfringementType]
func (data *EventDataPenalty) GetInfringementType() uint8 { return data.InfringementType }

// SetInfringementType stores [EventDataPenalty.InfringementType]
func (data *EventDataPenalty) SetInfringementType(v uint8) { data.InfringementType = v }

// GetVehicleIdx returns [EventDataPenalty.VehicleIdx]
func (data *EventDataPenalty) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores [EventDataPenalty.VehicleIdx]
func (data *EventDataPenalty) SetVehicleIdx(v uint8) { data.VehicleIdx = v }

// GetOtherVehicleIdx returns [EventDataPenalty.OtherVehicleIdx]
func (data *EventDataPenalty) GetOtherVehicleIdx() uint8 { return data.OtherVehicleIdx }

// SetOtherVehicleIdx stores [EventDataPenalty.OtherVehicleIdx]
func (data *EventDataPenalty) SetOtherVehicleIdx(v uint8) { data.OtherVehicleIdx = v }

// GetTime returns [EventDataPenalty.Time]
func (data *EventDataPenalty) GetTime() uint8 { return data.Time }

// SetTime stores [EventDataPenalty.Time]
func (data *EventDataPenalty) SetTime(v uint8) { data.Time = v }

// GetLapNum returns [EventDataPenalty.LapNum]
func (data *EventDataPenalty) GetLapNum() uint8 { return data.LapNum }

// SetLapNum stores [EventDataPenalty.LapNum]
func (data *EventDataPenalty) SetLapNum(v uint8) { data.LapNum = v }

// GetPlacesGained returns [EventDataPenalty.PlacesGained]
func (data *EventDataPenalty) GetPlacesGained() uint8 { return data.PlacesGained }

// SetPlacesGained stores [EventDataPenalty.PlacesGained]
func (data *EventDataPenalty) SetPlacesGained(v uint8) { data.PlacesGained = v }
