// Code generated by tools/gen/accessors from marshal_zone.go. DO NOT EDIT.

package f12024

// GetZoneStart returns [MarshalZone.ZoneStart]
func (data *MarshalZone) GetZoneStart() float32 { return data.ZoneStart }

// SetZoneStart stores [MarshalZone.ZoneStart]
func (data *MarshalZone) SetZoneStart(v float32) { data.ZoneStart = v }

// GetZoneFlag returns [MarshalZone.ZoneFlag]
func (data *MarshalZone) GetZoneFlag() int8 { return data.ZoneFlag }

// SetZoneFlag stores [MarshalZone.ZoneFlag]
func (data *MarshalZone) SetZoneFlag(v int8) { data.ZoneFlag = v }
