// Code generated by tools/gen/accessors from packet_car_setup_data.go. DO NOT EDIT.

package f12024

// GetHeader returns [PacketCarSetupData.Header]
func (data *PacketCarSetupData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketCarSetupData.Header]
func (data *PacketCarSetupData) SetHeader(v PacketHeader) { data.Header = v }

// GetNextFrontWingValue returns [PacketCarSetupData.NextFrontWingValue]
func (data *PacketCarSetupData) GetNextFrontWingValue() float32 { return data.NextFrontWingValue }

// SetNextFrontWingValue stores [PacketCarSetupData.NextFrontWingValue]
func (data *PacketCarSetupData) SetNextFrontWingValue(v float32) { data.NextFrontWingValue = v }
