// Code generated by tools/gen/accessors from packet_car_telemetry_data.go. DO NOT EDIT.

package f12024

// GetHeader returns [PacketCarTelemetryData.Header]
func (data *PacketCarTelemetryData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketCarTelemetryData.Header]
func (data *PacketCarTelemetryData) SetHeader(v PacketHeader) { data.Header = v }

// GetMfdPanelIndex returns [PacketCarTelemetryData.MfdPanelIndex]
func (data *PacketCarTelemetryData) GetMfdPanelIndex() uint8 { return data.MfdPanelIndex }

// SetMfdPanelIndex stores [PacketCarTelemetryData.MfdPanelIndex]
func (data *PacketCarTelemetryData) SetMfdPanelIndex(v uint8) { data.MfdPanelIndex = v }

// GetMfdPanelIndexSecondaryPlayer returns [PacketCarTelemetryData.MfdPanelIndexSecondaryPlayer]
func (data *PacketCarTelemetryData) GetMfdPanelIndexSecondaryPlayer() uint8 {
	return data.MfdPanelIndexSecondaryPlayer
}

// SetMfdPanelIndexSecondaryPlayer stores [PacketCarTelemetryData.MfdPanelIndexSecondaryPlayer]
func (data *PacketCarTelemetryData) SetMfdPanelIndexSecondaryPlayer(v uint8) {
	data.MfdPanelIndexSecondaryPlayer = v
}

// GetSuggestedGear returns [PacketCarTelemetryData.SuggestedGear]
func (data *PacketCarTelemetryData) GetSuggestedGear() int8 { return data.SuggestedGear }

// SetSuggestedGear stores [PacketCarTelemetryData.SuggestedGear]
func (data *PacketCarTelemetryData) SetSuggestedGear(v int8) { data.SuggestedGear = v }
