// Code generated by tools/gen/accessors from packet_car_status_data.go. DO NOT EDIT.

package f12024

// GetHeader returns [PacketCarStatusData.Header]
func (data *PacketCarStatusData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketCarStatusData.Header]
func (data *PacketCarStatusData) SetHeader(v PacketHeader) { data.Header = v }
