// Code generated by tools/gen/accessors from packet_tyre_sets_data.go. DO NOT EDIT.

package f12024

// GetHeader returns [PacketTyreSetsData.Header]
func (data *PacketTyreSetsData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketTyreSetsData.Header]
func (data *PacketTyreSetsData) SetHeader(v PacketHeader) { data.Header = v }

// GetCarIdx returns [PacketTyreSetsData.CarIdx]
func (data *PacketTyreSetsData) GetCarIdx() uint8 { return data.CarIdx }

// SetCarIdx stores [PacketTyreSetsData.CarIdx]
func (data *PacketTyreSetsData) SetCarIdx(v uint8) { data.CarIdx = v }

// GetFittedIdx returns [PacketTyreSetsData.FittedIdx]
func (data *PacketTyreSetsData) GetFittedIdx() uint8 { return data.FittedIdx }

// SetFittedIdx stores [PacketTyreSetsData.FittedIdx]
func (data *PacketTyreSetsData) SetFittedIdx(v uint8) { data.FittedIdx = v }
