// Code generated by tools/gen/accessors from packet_lap_data.go. DO NOT EDIT.

package f12024

// GetHeader returns [PacketLapData.Header]
func (data *PacketLapData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketLapData.Header]
func (data *PacketLapData) SetHeader(v PacketHeader) { data.Header = v }

// GetTimeTrialPBCarIdx returns [PacketLapData.TimeTrialPBCarIdx]
func (data *PacketLapData) GetTimeTrialPBCarIdx() uint8 { return data.TimeTrialPBCarIdx }

// SetTimeTrialPBCarIdx stores [PacketLapData.TimeTrialPBCarIdx]
func (data *PacketLapData) SetTimeTrialPBCarIdx(v uint8) { data.TimeTrialPBCarIdx = v }

// GetTimeTrialRivalCarIdx returns [PacketLapData.TimeTrialRivalCarIdx]
func (data *PacketLapData) GetTimeTrialRivalCarIdx() uint8 { return data.TimeTrialRivalCarIdx }

// SetTimeTrialRivalCarIdx stores [PacketLapData.TimeTrialRivalCarIdx]
func (data *PacketLapData) SetTimeTrialRivalCarIdx(v uint8) { data.TimeTrialRivalCarIdx = v }
