// Code generated by tools/gen/accessors from participant_data.go. DO NOT EDIT.

package f12024

import (
	"github.com/daanv2/race-game-dashboard/pkg/f1game/f1common"
)

// GetAiControlled returns [ParticipantData.AiControlled]
func (data *ParticipantData) GetAiControlled() uint8 { return data.AiControlled }

// SetAiControlled stores [ParticipantData.AiControlled]
func (data *ParticipantData) SetAiControlled(v uint8) { data.AiControlled = v }

// GetDriverId returns [ParticipantData.DriverId]
func (data *ParticipantData) GetDriverId() f1common.DriverID { return data.DriverId }

// SetDriverId stores [ParticipantData.DriverId]
func (data *ParticipantData) SetDriverId(v f1common.DriverID) { data.DriverId = v }

// GetNetworkId returns [ParticipantData.NetworkId]
func (data *ParticipantData) GetNetworkId() uint8 { return data.NetworkId }

// SetNetworkId stores [ParticipantData.NetworkId]
func (data *ParticipantData) SetNetworkId(v uint8) { data.NetworkId = v }

// GetTeamId returns [ParticipantData.TeamId]
func (data *ParticipantData) GetTeamId() f1common.TeamID { return data.TeamId }

// SetTeamId stores [ParticipantData.TeamId]
func (data *ParticipantData) SetTeamId(v f1common.TeamID) { data.TeamId = v }

// GetMyTeam returns [ParticipantData.MyTeam]
func (data *ParticipantData) GetMyTeam() uint8 { return data.MyTeam }

// SetMyTeam stores [ParticipantData.MyTeam]
func (data *ParticipantData) SetMyTeam(v uint8) { data.MyTeam = v }

// GetRaceNumber returns [ParticipantData.RaceNumber]
func (data *ParticipantData) GetRaceNumber() uint8 { return data.RaceNumber }

// SetRaceNumber stores [ParticipantData.RaceNumber]
func (data *ParticipantData) SetRaceNumber(v uint8) { data.RaceNumber = v }

// GetNationality returns [ParticipantData.Nationality]
func (data *ParticipantData) GetNationality() uint8 { return data.Nationality }

// SetNationality stores [ParticipantData.Nationality]
func (data *ParticipantData) SetNationality(v uint8) { data.Nationality = v }

// GetYourTelemetry returns [ParticipantData.YourTelemetry]
func (data *ParticipantData) GetYourTelemetry() uint8 { return data.YourTelemetry }

// SetYourTelemetry stores [ParticipantData.YourTelemetry]
func (data *ParticipantData) SetYourTelemetry(v uint8) { data.YourTelemetry = v }

// GetShowOnlineNames returns [ParticipantData.ShowOnlineNames]
func (data *ParticipantData) GetShowOnlineNames() uint8 { return data.ShowOnlineNames }

// SetShowOnlineNames stores [ParticipantData.ShowOnlineNames]
func (data *ParticipantData) SetShowOnlineNames(v uint8) { data.ShowOnlineNames = v }

// GetTechLevel returns [ParticipantData.TechLevel]
func (data *ParticipantData) GetTechLevel() uint16 { return data.TechLevel }

// SetTechLevel stores [ParticipantData.TechLevel]
func (data *ParticipantData) SetTechLevel(v uint16) { data.TechLevel = v }

// GetPlatform returns [ParticipantData.Platform]
func (data *ParticipantData) GetPlatform() uint8 { return data.Platform }

// SetPlatform stores [ParticipantData.Platform]
func (data *ParticipantData) SetPlatform(v uint8) { data.Platform = v }
