// Code generated by tools/gen/accessors from tyre_set_data.go. DO NOT EDIT.

package f12024

// GetActualTyreCompound returns [TyreSetData.ActualTyreCompound]
func (data *TyreSetData) GetActualTyreCompound() uint8 { return data.ActualTyreCompound }

// SetActualTyreCompound stores [TyreSetData.ActualTyreCompound]
func (data *TyreSetData) SetActualTyreCompound(v uint8) { data.ActualTyreCompound = v }

// GetVisualTyreCompound returns [TyreSetData.VisualTyreCompound]
func (data *TyreSetData) GetVisualTyreCompound() uint8 { return data.VisualTyreCompound }

// SetVisualTyreCompound stores [TyreSetData.VisualTyreCompound]
func (data *TyreSetData) SetVisualTyreCompound(v uint8) { data.VisualTyreCompound = v }

// GetWear returns [TyreSetData.Wear]
func (data *TyreSetData) GetWear() uint8 { return data.Wear }

// SetWear stores [TyreSetData.Wear]
func (data *TyreSetData) SetWear(v uint8) { data.Wear = v }

// GetAvailable returns [TyreSetData.Available]
func (data *TyreSetData) GetAvailable() uint8 { return data.Available }

// SetAvailable stores [TyreSetData.Available]
func (data *TyreSetData) SetAvailable(v uint8) { data.Available = v }

// GetRecommendedSession returns [TyreSetData.RecommendedSession]
func (data *TyreSetData) GetRecommendedSession() uint8 { return data.RecommendedSession }

// SetRecommendedSession stores [TyreSetData.RecommendedSession]
func (data *TyreSetData) SetRecommendedSession(v uint8) { data.RecommendedSession = v }

// GetLifeSpan returns [TyreSetData.LifeSpan]
func (data *TyreSetData) GetLifeSpan() uint8 { return data.LifeSpan }

// SetLifeSpan stores [TyreSetData.LifeSpan]
func (data *TyreSetData) SetLifeSpan(v uint8) { data.LifeSpan = v }

// GetUsableLife returns [TyreSetData.UsableLife]
func (data *TyreSetData) GetUsableLife() uint8 { return data.UsableLife }

// SetUsableLife stores [TyreSetData.UsableLife]
func (data *TyreSetData) SetUsableLife(v uint8) { data.UsableLife = v }

// GetLapDeltaTime returns [TyreSetData.LapDeltaTime]
func (data *TyreSetData) GetLapDeltaTime() int16 { return data.LapDeltaTime }

// SetLapDeltaTime stores [TyreSetData.LapDeltaTime]
func (data *TyreSetData) SetLapDeltaTime(v int16) { data.LapDeltaTime = v }

// GetFitted returns [TyreSetData.Fitted]
func (data *TyreSetData) GetFitted() uint8 { return data.Fitted }

// SetFitted stores [TyreSetData.Fitted]
func (data *TyreSetData) SetFitted(v uint8) { data.Fitted = v }
