// Code generated by tools/gen/accessors from active_aero_zone.go. DO NOT EDIT.

package f12026s

// GetZoneStart returns the ZoneStart of [ActiveAeroZone]
func (data *ActiveAeroZone) GetZoneStart() float32 { return data.ZoneStart }

// SetZoneStart stores the ZoneStart of [ActiveAeroZone]
func (data *ActiveAeroZone) SetZoneStart(v float32) { data.ZoneStart = v }

// GetZoneEnd returns the ZoneEnd of [ActiveAeroZone]
func (data *ActiveAeroZone) GetZoneEnd() float32 { return data.ZoneEnd }

// SetZoneEnd stores the ZoneEnd of [ActiveAeroZone]
func (data *ActiveAeroZone) SetZoneEnd(v float32) { data.ZoneEnd = v }
