// Code generated by tools/gen/accessors from car_telemetry_data.go. DO NOT EDIT.

package f12026s

// GetSpeed returns the Speed of [CarTelemetryData]
func (data *CarTelemetryData) GetSpeed() uint16 { return data.Speed }

// SetSpeed stores the Speed of [CarTelemetryData]
func (data *CarTelemetryData) SetSpeed(v uint16) { data.Speed = v }

// GetThrottle returns the Throttle of [CarTelemetryData]
func (data *CarTelemetryData) GetThrottle() float32 { return data.Throttle }

// SetThrottle stores the Throttle of [CarTelemetryData]
func (data *CarTelemetryData) SetThrottle(v float32) { data.Throttle = v }

// GetSteer returns the Steer of [CarTelemetryData]
func (data *CarTelemetryData) GetSteer() float32 { return data.Steer }

// SetSteer stores the Steer of [CarTelemetryData]
func (data *CarTelemetryData) SetSteer(v float32) { data.Steer = v }

// GetBrake returns the Brake of [CarTelemetryData]
func (data *CarTelemetryData) GetBrake() float32 { return data.Brake }

// SetBrake stores the Brake of [CarTelemetryData]
func (data *CarTelemetryData) SetBrake(v float32) { data.Brake = v }

// GetClutch returns the Clutch of [CarTelemetryData]
func (data *CarTelemetryData) GetClutch() uint8 { return data.Clutch }

// SetClutch stores the Clutch of [CarTelemetryData]
func (data *CarTelemetryData) SetClutch(v uint8) { data.Clutch = v }

// GetGear returns the Gear of [CarTelemetryData]
func (data *CarTelemetryData) GetGear() int8 { return data.Gear }

// SetGear stores the Gear of [CarTelemetryData]
func (data *CarTelemetryData) SetGear(v int8) { data.Gear = v }

// GetEngineRPM returns the EngineRPM of [CarTelemetryData]
func (data *CarTelemetryData) GetEngineRPM() uint16 { return data.EngineRPM }

// SetEngineRPM stores the EngineRPM of [CarTelemetryData]
func (data *CarTelemetryData) SetEngineRPM(v uint16) { data.EngineRPM = v }

// GetDRS returns the DRS of [CarTelemetryData]
func (data *CarTelemetryData) GetDRS() uint8 { return data.DRS }

// SetDRS stores the DRS of [CarTelemetryData]
func (data *CarTelemetryData) SetDRS(v uint8) { data.DRS = v }

// GetRevLightsPercent returns the RevLightsPercent of [CarTelemetryData]
func (data *CarTelemetryData) GetRevLightsPercent() uint8 { return data.RevLightsPercent }

// SetRevLightsPercent stores the RevLightsPercent of [CarTelemetryData]
func (data *CarTelemetryData) SetRevLightsPercent(v uint8) { data.RevLightsPercent = v }

// GetRevLightsBitValue returns the RevLightsBitValue of [CarTelemetryData]
func (data *CarTelemetryData) GetRevLightsBitValue() uint16 { return data.RevLightsBitValue }

// SetRevLightsBitValue stores the RevLightsBitValue of [CarTelemetryData]
func (data *CarTelemetryData) SetRevLightsBitValue(v uint16) { data.RevLightsBitValue = v }

// GetBrakesTemperature returns the BrakesTemperature of [CarTelemetryData]
func (data *CarTelemetryData) GetBrakesTemperature() WheelMap[uint16] { return data.BrakesTemperature }

// SetBrakesTemperature stores the BrakesTemperature of [CarTelemetryData]
func (data *CarTelemetryData) SetBrakesTemperature(v WheelMap[uint16]) { data.BrakesTemperature = v }

// GetTyresSurfaceTemperature returns the TyresSurfaceTemperature of [CarTelemetryData]
func (data *CarTelemetryData) GetTyresSurfaceTemperature() WheelMap[uint8] {
	return data.TyresSurfaceTemperature
}

// SetTyresSurfaceTemperature stores the TyresSurfaceTemperature of [CarTelemetryData]
func (data *CarTelemetryData) SetTyresSurfaceTemperature(v WheelMap[uint8]) {
	data.TyresSurfaceTemperature = v
}

// GetTyresInnerTemperature returns the TyresInnerTemperature of [CarTelemetryData]
func (data *CarTelemetryData) GetTyresInnerTemperature() WheelMap[uint8] {
	return data.TyresInnerTemperature
}

// SetTyresInnerTemperature stores the TyresInnerTemperature of [CarTelemetryData]
func (data *CarTelemetryData) SetTyresInnerTemperature(v WheelMap[uint8]) {
	data.TyresInnerTemperature = v
}

// GetEngineTemperature returns the EngineTemperature of [CarTelemetryData]
func (data *CarTelemetryData) GetEngineTemperature() uint8 { return data.EngineTemperature }

// SetEngineTemperature stores the EngineTemperature of [CarTelemetryData]
func (data *CarTelemetryData) SetEngineTemperature(v uint8) { data.EngineTemperature = v }

// GetTyresPressure returns the TyresPressure of [CarTelemetryData]
func (data *CarTelemetryData) GetTyresPressure() WheelMap[float32] { return data.TyresPressure }

// SetTyresPressure stores the TyresPressure of [CarTelemetryData]
func (data *CarTelemetryData) SetTyresPressure(v WheelMap[float32]) { data.TyresPressure = v }

// GetSurfaceType returns the SurfaceType of [CarTelemetryData]
func (data *CarTelemetryData) GetSurfaceType() WheelMap[uint8] { return data.SurfaceType }

// SetSurfaceType stores the SurfaceType of [CarTelemetryData]
func (data *CarTelemetryData) SetSurfaceType(v WheelMap[uint8]) { data.SurfaceType = v }
