// Code generated by tools/gen/accessors from car_damage_data.go. DO NOT EDIT.

package f12026s

// GetTyresWear returns [CarDamageData.TyresWear]
func (data *CarDamageData) GetTyresWear() WheelMap[float32] { return data.TyresWear }

// SetTyresWear stores [CarDamageData.TyresWear]
func (data *CarDamageData) SetTyresWear(v WheelMap[float32]) { data.TyresWear = v }

// GetTyresDamage returns [CarDamageData.TyresDamage]
func (data *CarDamageData) GetTyresDamage() WheelMap[uint8] { return data.TyresDamage }

// SetTyresDamage stores [CarDamageData.TyresDamage]
func (data *CarDamageData) SetTyresDamage(v WheelMap[uint8]) { data.TyresDamage = v }

// GetBrakesDamage returns [CarDamageData.BrakesDamage]
func (data *CarDamageData) GetBrakesDamage() WheelMap[uint8] { return data.BrakesDamage }

// SetBrakesDamage stores [CarDamageData.BrakesDamage]
func (data *CarDamageData) SetBrakesDamage(v WheelMap[uint8]) { data.BrakesDamage = v }

// GetTyreBlisters returns [CarDamageData.TyreBlisters]
func (data *CarDamageData) GetTyreBlisters() WheelMap[uint8] { return data.TyreBlisters }

// SetTyreBlisters stores [CarDamageData.TyreBlisters]
func (data *CarDamageData) SetTyreBlisters(v WheelMap[uint8]) { data.TyreBlisters = v }

// GetFrontLeftWingDamage returns [CarDamageData.FrontLeftWingDamage]
func (data *CarDamageData) GetFrontLeftWingDamage() uint8 { return data.FrontLeftWingDamage }

// SetFrontLeftWingDamage stores [CarDamageData.FrontLeftWingDamage]
func (data *CarDamageData) SetFrontLeftWingDamage(v uint8) { data.FrontLeftWingDamage = v }

// GetFrontRightWingDamage returns [CarDamageData.FrontRightWingDamage]
func (data *CarDamageData) GetFrontRightWingDamage() uint8 { return data.FrontRightWingDamage }

// SetFrontRightWingDamage stores [CarDamageData.FrontRightWingDamage]
func (data *CarDamageData) SetFrontRightWingDamage(v uint8) { data.FrontRightWingDamage = v }

// GetRearWingDamage returns [CarDamageData.RearWingDamage]
func (data *CarDamageData) GetRearWingDamage() uint8 { return data.RearWingDamage }

// SetRearWingDamage stores [CarDamageData.RearWingDamage]
func (data *CarDamageData) SetRearWingDamage(v uint8) { data.RearWingDamage = v }

// GetFloorDamage returns [CarDamageData.FloorDamage]
func (data *CarDamageData) GetFloorDamage() uint8 { return data.FloorDamage }

// SetFloorDamage stores [CarDamageData.FloorDamage]
func (data *CarDamageData) SetFloorDamage(v uint8) { data.FloorDamage = v }

// GetDiffuserDamage returns [CarDamageData.DiffuserDamage]
func (data *CarDamageData) GetDiffuserDamage() uint8 { return data.DiffuserDamage }

// SetDiffuserDamage stores [CarDamageData.DiffuserDamage]
func (data *CarDamageData) SetDiffuserDamage(v uint8) { data.DiffuserDamage = v }

// GetSidepodDamage returns [CarDamageData.SidepodDamage]
func (data *CarDamageData) GetSidepodDamage() uint8 { return data.SidepodDamage }

// SetSidepodDamage stores [CarDamageData.SidepodDamage]
func (data *CarDamageData) SetSidepodDamage(v uint8) { data.SidepodDamage = v }

// GetDrsFault returns [CarDamageData.DrsFault]
func (data *CarDamageData) GetDrsFault() uint8 { return data.DrsFault }

// SetDrsFault stores [CarDamageData.DrsFault]
func (data *CarDamageData) SetDrsFault(v uint8) { data.DrsFault = v }

// GetErsFault returns [CarDamageData.ErsFault]
func (data *CarDamageData) GetErsFault() uint8 { return data.ErsFault }

// SetErsFault stores [CarDamageData.ErsFault]
func (data *CarDamageData) SetErsFault(v uint8) { data.ErsFault = v }

// GetGearBoxDamage returns [CarDamageData.GearBoxDamage]
func (data *CarDamageData) GetGearBoxDamage() uint8 { return data.GearBoxDamage }

// SetGearBoxDamage stores [CarDamageData.GearBoxDamage]
func (data *CarDamageData) SetGearBoxDamage(v uint8) { data.GearBoxDamage = v }

// GetEngineDamage returns [CarDamageData.EngineDamage]
func (data *CarDamageData) GetEngineDamage() uint8 { return data.EngineDamage }

// SetEngineDamage stores [CarDamageData.EngineDamage]
func (data *CarDamageData) SetEngineDamage(v uint8) { data.EngineDamage = v }

// GetEngineMGUHWear returns [CarDamageData.EngineMGUHWear]
func (data *CarDamageData) GetEngineMGUHWear() uint8 { return data.EngineMGUHWear }

// SetEngineMGUHWear stores [CarDamageData.EngineMGUHWear]
func (data *CarDamageData) SetEngineMGUHWear(v uint8) { data.EngineMGUHWear = v }

// GetEngineESWear returns [CarDamageData.EngineESWear]
func (data *CarDamageData) GetEngineESWear() uint8 { return data.EngineESWear }

// SetEngineESWear stores [CarDamageData.EngineESWear]
func (data *CarDamageData) SetEngineESWear(v uint8) { data.EngineESWear = v }

// GetEngineCEWear returns [CarDamageData.EngineCEWear]
func (data *CarDamageData) GetEngineCEWear() uint8 { return data.EngineCEWear }

// SetEngineCEWear stores [CarDamageData.EngineCEWear]
func (data *CarDamageData) SetEngineCEWear(v uint8) { data.EngineCEWear = v }

// GetEngineICEWear returns [CarDamageData.EngineICEWear]
func (data *CarDamageData) GetEngineICEWear() uint8 { return data.EngineICEWear }

// SetEngineICEWear stores [CarDamageData.EngineICEWear]
func (data *CarDamageData) SetEngineICEWear(v uint8) { data.EngineICEWear = v }

// GetEngineMGUKWear returns [CarDamageData.EngineMGUKWear]
func (data *CarDamageData) GetEngineMGUKWear() uint8 { return data.EngineMGUKWear }

// SetEngineMGUKWear stores [CarDamageData.EngineMGUKWear]
func (data *CarDamageData) SetEngineMGUKWear(v uint8) { data.EngineMGUKWear = v }

// GetEngineTCWear returns [CarDamageData.EngineTCWear]
func (data *CarDamageData) GetEngineTCWear() uint8 { return data.EngineTCWear }

// SetEngineTCWear stores [CarDamageData.EngineTCWear]
func (data *CarDamageData) SetEngineTCWear(v uint8) { data.EngineTCWear = v }

// GetEngineBlown returns [CarDamageData.EngineBlown]
func (data *CarDamageData) GetEngineBlown() uint8 { return data.EngineBlown }

// SetEngineBlown stores [CarDamageData.EngineBlown]
func (data *CarDamageData) SetEngineBlown(v uint8) { data.EngineBlown = v }

// GetEngineSeized returns [CarDamageData.EngineSeized]
func (data *CarDamageData) GetEngineSeized() uint8 { return data.EngineSeized }

// SetEngineSeized stores [CarDamageData.EngineSeized]
func (data *CarDamageData) SetEngineSeized(v uint8) { data.EngineSeized = v }
