// Code generated by tools/gen/accessors from car_setup_data.go. DO NOT EDIT.

package f12026s

// GetFrontWing returns [CarSetupData.FrontWing]
func (data *CarSetupData) GetFrontWing() uint8 { return data.FrontWing }

// SetFrontWing stores [CarSetupData.FrontWing]
func (data *CarSetupData) SetFrontWing(v uint8) { data.FrontWing = v }

// GetRearWing returns [CarSetupData.RearWing]
func (data *CarSetupData) GetRearWing() uint8 { return data.RearWing }

// SetRearWing stores [CarSetupData.RearWing]
func (data *CarSetupData) SetRearWing(v uint8) { data.RearWing = v }

// GetOnThrottle returns [CarSetupData.OnThrottle]
func (data *CarSetupData) GetOnThrottle() uint8 { return data.OnThrottle }

// SetOnThrottle stores [CarSetupData.OnThrottle]
func (data *CarSetupData) SetOnThrottle(v uint8) { data.OnThrottle = v }

// GetOffThrottle returns [CarSetupData.OffThrottle]
func (data *CarSetupData) GetOffThrottle() uint8 { return data.OffThrottle }

// SetOffThrottle stores [CarSetupData.OffThrottle]
func (data *CarSetupData) SetOffThrottle(v uint8) { data.OffThrottle = v }

// GetFrontCamber returns [CarSetupData.FrontCamber]
func (data *CarSetupData) GetFrontCamber() float32 { return data.FrontCamber }

// SetFrontCamber stores [CarSetupData.FrontCamber]
func (data *CarSetupData) SetFrontCamber(v float32) { data.FrontCamber = v }

// GetRearCamber returns [CarSetupData.RearCamber]
func (data *CarSetupData) GetRearCamber() float32 { return data.RearCamber }

// SetRearCamber stores [CarSetupData.RearCamber]
func (data *CarSetupData) SetRearCamber(v float32) { data.RearCamber = v }

// GetFrontToe returns [CarSetupData.FrontToe]
func (data *CarSetupData) GetFrontToe() float32 { return data.FrontToe }

// SetFrontToe stores [CarSetupData.FrontToe]
func (data *CarSetupData) SetFrontToe(v float32) { data.FrontToe = v }

// GetRearToe returns [CarSetupData.RearToe]
func (data *CarSetupData) GetRearToe() float32 { return data.RearToe }

// SetRearToe stores [CarSetupData.RearToe]
func (data *CarSetupData) SetRearToe(v float32) { data.RearToe = v }

// GetFrontSuspension returns [CarSetupData.FrontSuspension]
func (data *CarSetupData) GetFrontSuspension() uint8 { return data.FrontSuspension }

// SetFrontSuspension stores [CarSetupData.FrontSuspension]
func (data *CarSetupData) SetFrontSuspension(v uint8) { data.FrontSuspension = v }

// GetRearSuspension returns [CarSetupData.RearSuspension]
func (data *CarSetupData) GetRearSuspension() uint8 { return data.RearSuspension }

// SetRearSuspension stores [CarSetupData.RearSuspension]
func (data *CarSetupData) SetRearSuspension(v uint8) { data.RearSuspension = v }

// GetFrontAntiRollBar returns [CarSetupData.FrontAntiRollBar]
func (data *CarSetupData) GetFrontAntiRollBar() uint8 { return data.FrontAntiRollBar }

// SetFrontAntiRollBar stores [CarSetupData.FrontAntiRollBar]
func (data *CarSetupData) SetFrontAntiRollBar(v uint8) { data.FrontAntiRollBar = v }

// GetRearAntiRollBar returns [CarSetupData.RearAntiRollBar]
func (data *CarSetupData) GetRearAntiRollBar() uint8 { return data.RearAntiRollBar }

// SetRearAntiRollBar stores [CarSetupData.RearAntiRollBar]
func (data *CarSetupData) SetRearAntiRollBar(v uint8) { data.RearAntiRollBar = v }

// GetFrontSuspensionHeight returns [CarSetupData.FrontSuspensionHeight]
func (data *CarSetupData) GetFrontSuspensionHeight() uint8 { return data.FrontSuspensionHeight }

// SetFrontSuspensionHeight stores [CarSetupData.FrontSuspensionHeight]
func (data *CarSetupData) SetFrontSuspensionHeight(v uint8) { data.FrontSuspensionHeight = v }

// GetRearSuspensionHeight returns [CarSetupData.RearSuspensionHeight]
func (data *CarSetupData) GetRearSuspensionHeight() uint8 { return data.RearSuspensionHeight }

// SetRearSuspensionHeight stores [CarSetupData.RearSuspensionHeight]
func (data *CarSetupData) SetRearSuspensionHeight(v uint8) { data.RearSuspensionHeight = v }

// GetBrakePressure returns [CarSetupData.BrakePressure]
func (data *CarSetupData) GetBrakePressure() uint8 { return data.BrakePressure }

// SetBrakePressure stores [CarSetupData.BrakePressure]
func (data *CarSetupData) SetBrakePressure(v uint8) { data.BrakePressure = v }

// GetBrakeBias returns [CarSetupData.BrakeBias]
func (data *CarSetupData) GetBrakeBias() uint8 { return data.BrakeBias }

// SetBrakeBias stores [CarSetupData.BrakeBias]
func (data *CarSetupData) SetBrakeBias(v uint8) { data.BrakeBias = v }

// GetEngineBraking returns [CarSetupData.EngineBraking]
func (data *CarSetupData) GetEngineBraking() uint8 { return data.EngineBraking }

// SetEngineBraking stores [CarSetupData.EngineBraking]
func (data *CarSetupData) SetEngineBraking(v uint8) { data.EngineBraking = v }

// GetRearLeftTyrePressure returns [CarSetupData.RearLeftTyrePressure]
func (data *CarSetupData) GetRearLeftTyrePressure() float32 { return data.RearLeftTyrePressure }

// SetRearLeftTyrePressure stores [CarSetupData.RearLeftTyrePressure]
func (data *CarSetupData) SetRearLeftTyrePressure(v float32) { data.RearLeftTyrePressure = v }

// GetRearRightTyrePressure returns [CarSetupData.RearRightTyrePressure]
func (data *CarSetupData) GetRearRightTyrePressure() float32 { return data.RearRightTyrePressure }

// SetRearRightTyrePressure stores [CarSetupData.RearRightTyrePressure]
func (data *CarSetupData) SetRearRightTyrePressure(v float32) { data.RearRightTyrePressure = v }

// GetFrontLeftTyrePressure returns [CarSetupData.FrontLeftTyrePressure]
func (data *CarSetupData) GetFrontLeftTyrePressure() float32 { return data.FrontLeftTyrePressure }

// SetFrontLeftTyrePressure stores [CarSetupData.FrontLeftTyrePressure]
func (data *CarSetupData) SetFrontLeftTyrePressure(v float32) { data.FrontLeftTyrePressure = v }

// GetFrontRightTyrePressure returns [CarSetupData.FrontRightTyrePressure]
func (data *CarSetupData) GetFrontRightTyrePressure() float32 { return data.FrontRightTyrePressure }

// SetFrontRightTyrePressure stores [CarSetupData.FrontRightTyrePressure]
func (data *CarSetupData) SetFrontRightTyrePressure(v float32) { data.FrontRightTyrePressure = v }

// GetBallast returns [CarSetupData.Ballast]
func (data *CarSetupData) GetBallast() uint8 { return data.Ballast }

// SetBallast stores [CarSetupData.Ballast]
func (data *CarSetupData) SetBallast(v uint8) { data.Ballast = v }

// GetFuelLoad returns [CarSetupData.FuelLoad]
func (data *CarSetupData) GetFuelLoad() float32 { return data.FuelLoad }

// SetFuelLoad stores [CarSetupData.FuelLoad]
func (data *CarSetupData) SetFuelLoad(v float32) { data.FuelLoad = v }
