// Code generated by tools/gen/accessors from car_telemetry2_data.go. DO NOT EDIT.

package f12026s

// GetActiveAeroMode returns [CarTelemetry2Data.ActiveAeroMode]
func (data *CarTelemetry2Data) GetActiveAeroMode() uint8 { return data.ActiveAeroMode }

// SetActiveAeroMode stores [CarTelemetry2Data.ActiveAeroMode]
func (data *CarTelemetry2Data) SetActiveAeroMode(v uint8) { data.ActiveAeroMode = v }

// GetActiveAeroAvailable returns [CarTelemetry2Data.ActiveAeroAvailable]
func (data *CarTelemetry2Data) GetActiveAeroAvailable() uint8 { return data.ActiveAeroAvailable }

// SetActiveAeroAvailable stores [CarTelemetry2Data.ActiveAeroAvailable]
func (data *CarTelemetry2Data) SetActiveAeroAvailable(v uint8) { data.ActiveAeroAvailable = v }

// GetActiveAeroActivationDistance returns [CarTelemetry2Data.ActiveAeroActivationDistance]
func (data *CarTelemetry2Data) GetActiveAeroActivationDistance() uint16 {
	return data.ActiveAeroActivationDistance
}

// SetActiveAeroActivationDistance stores [CarTelemetry2Data.ActiveAeroActivationDistance]
func (data *CarTelemetry2Data) SetActiveAeroActivationDistance(v uint16) {
	data.ActiveAeroActivationDistance = v
}

// GetOvertakeAvailable returns [CarTelemetry2Data.OvertakeAvailable]
func (data *CarTelemetry2Data) GetOvertakeAvailable() uint8 { return data.OvertakeAvailable }

// SetOvertakeAvailable stores [CarTelemetry2Data.OvertakeAvailable]
func (data *CarTelemetry2Data) SetOvertakeAvailable(v uint8) { data.OvertakeAvailable = v }

// GetOvertakeActive returns [CarTelemetry2Data.OvertakeActive]
func (data *CarTelemetry2Data) GetOvertakeActive() uint8 { return data.OvertakeActive }

// SetOvertakeActive stores [CarTelemetry2Data.OvertakeActive]
func (data *CarTelemetry2Data) SetOvertakeActive(v uint8) { data.OvertakeActive = v }

// GetOvertakeActivationDistance returns [CarTelemetry2Data.OvertakeActivationDistance]
func (data *CarTelemetry2Data) GetOvertakeActivationDistance() uint16 {
	return data.OvertakeActivationDistance
}

// SetOvertakeActivationDistance stores [CarTelemetry2Data.OvertakeActivationDistance]
func (data *CarTelemetry2Data) SetOvertakeActivationDistance(v uint16) {
	data.OvertakeActivationDistance = v
}

// GetRegulations2026 returns [CarTelemetry2Data.Regulations2026]
func (data *CarTelemetry2Data) GetRegulations2026() uint8 { return data.Regulations2026 }

// SetRegulations2026 stores [CarTelemetry2Data.Regulations2026]
func (data *CarTelemetry2Data) SetRegulations2026(v uint8) { data.Regulations2026 = v }

// GetDrivingWrongWay returns [CarTelemetry2Data.DrivingWrongWay]
func (data *CarTelemetry2Data) GetDrivingWrongWay() uint8 { return data.DrivingWrongWay }

// SetDrivingWrongWay stores [CarTelemetry2Data.DrivingWrongWay]
func (data *CarTelemetry2Data) SetDrivingWrongWay(v uint8) { data.DrivingWrongWay = v }
