// Code generated by tools/gen/accessors from car_status_data.go. DO NOT EDIT.

package f12026s

// GetTractionControl returns the TractionControl of [CarStatusData]
func (data *CarStatusData) GetTractionControl() uint8 { return data.TractionControl }

// SetTractionControl stores the TractionControl of [CarStatusData]
func (data *CarStatusData) SetTractionControl(v uint8) { data.TractionControl = v }

// GetAntiLockBrakes returns the AntiLockBrakes of [CarStatusData]
func (data *CarStatusData) GetAntiLockBrakes() uint8 { return data.AntiLockBrakes }

// SetAntiLockBrakes stores the AntiLockBrakes of [CarStatusData]
func (data *CarStatusData) SetAntiLockBrakes(v uint8) { data.AntiLockBrakes = v }

// GetFuelMix returns the FuelMix of [CarStatusData]
func (data *CarStatusData) GetFuelMix() uint8 { return data.FuelMix }

// SetFuelMix stores the FuelMix of [CarStatusData]
func (data *CarStatusData) SetFuelMix(v uint8) { data.FuelMix = v }

// GetFrontBrakeBias returns the FrontBrakeBias of [CarStatusData]
func (data *CarStatusData) GetFrontBrakeBias() uint8 { return data.FrontBrakeBias }

// SetFrontBrakeBias stores the FrontBrakeBias of [CarStatusData]
func (data *CarStatusData) SetFrontBrakeBias(v uint8) { data.FrontBrakeBias = v }

// GetPitLimiterStatus returns the PitLimiterStatus of [CarStatusData]
func (data *CarStatusData) GetPitLimiterStatus() uint8 { return data.PitLimiterStatus }

// SetPitLimiterStatus stores the PitLimiterStatus of [CarStatusData]
func (data *CarStatusData) SetPitLimiterStatus(v uint8) { data.PitLimiterStatus = v }

// GetFuelInTank returns the FuelInTank of [CarStatusData]
func (data *CarStatusData) GetFuelInTank() float32 { return data.FuelInTank }

// SetFuelInTank stores the FuelInTank of [CarStatusData]
func (data *CarStatusData) SetFuelInTank(v float32) { data.FuelInTank = v }

// GetFuelCapacity returns the FuelCapacity of [CarStatusData]
func (data *CarStatusData) GetFuelCapacity() float32 { return data.FuelCapacity }

// SetFuelCapacity stores the FuelCapacity of [CarStatusData]
func (data *CarStatusData) SetFuelCapacity(v float32) { data.FuelCapacity = v }

// GetFuelRemainingLaps returns the FuelRemainingLaps of [CarStatusData]
func (data *CarStatusData) GetFuelRemainingLaps() float32 { return data.FuelRemainingLaps }

// SetFuelRemainingLaps stores the FuelRemainingLaps of [CarStatusData]
func (data *CarStatusData) SetFuelRemainingLaps(v float32) { data.FuelRemainingLaps = v }

// GetMaxRPM returns the MaxRPM of [CarStatusData]
func (data *CarStatusData) GetMaxRPM() uint16 { return data.MaxRPM }

// SetMaxRPM stores the MaxRPM of [CarStatusData]
func (data *CarStatusData) SetMaxRPM(v uint16) { data.MaxRPM = v }

// GetIdleRPM returns the IdleRPM of [CarStatusData]
func (data *CarStatusData) GetIdleRPM() uint16 { return data.IdleRPM }

// SetIdleRPM stores the IdleRPM of [CarStatusData]
func (data *CarStatusData) SetIdleRPM(v uint16) { data.IdleRPM = v }

// GetMaxGears returns the MaxGears of [CarStatusData]
func (data *CarStatusData) GetMaxGears() uint8 { return data.MaxGears }

// SetMaxGears stores the MaxGears of [CarStatusData]
func (data *CarStatusData) SetMaxGears(v uint8) { data.MaxGears = v }

// GetDrsAllowed returns the DrsAllowed of [CarStatusData]
func (data *CarStatusData) GetDrsAllowed() uint8 { return data.DrsAllowed }

// SetDrsAllowed stores the DrsAllowed of [CarStatusData]
func (data *CarStatusData) SetDrsAllowed(v uint8) { data.DrsAllowed = v }

// GetDrsActivationDistance returns the DrsActivationDistance of [CarStatusData]
func (data *CarStatusData) GetDrsActivationDistance() uint16 { return data.DrsActivationDistance }

// SetDrsActivationDistance stores the DrsActivationDistance of [CarStatusData]
func (data *CarStatusData) SetDrsActivationDistance(v uint16) { data.DrsActivationDistance = v }

// GetActualTyreCompound returns the ActualTyreCompound of [CarStatusData]
func (data *CarStatusData) GetActualTyreCompound() uint8 { return data.ActualTyreCompound }

// SetActualTyreCompound stores the ActualTyreCompound of [CarStatusData]
func (data *CarStatusData) SetActualTyreCompound(v uint8) { data.ActualTyreCompound = v }

// GetVisualTyreCompound returns the VisualTyreCompound of [CarStatusData]
func (data *CarStatusData) GetVisualTyreCompound() uint8 { return data.VisualTyreCompound }

// SetVisualTyreCompound stores the VisualTyreCompound of [CarStatusData]
func (data *CarStatusData) SetVisualTyreCompound(v uint8) { data.VisualTyreCompound = v }

// GetTyresAgeLaps returns the TyresAgeLaps of [CarStatusData]
func (data *CarStatusData) GetTyresAgeLaps() uint8 { return data.TyresAgeLaps }

// SetTyresAgeLaps stores the TyresAgeLaps of [CarStatusData]
func (data *CarStatusData) SetTyresAgeLaps(v uint8) { data.TyresAgeLaps = v }

// GetVehicleFiaFlags returns the VehicleFiaFlags of [CarStatusData]
func (data *CarStatusData) GetVehicleFiaFlags() int8 { return data.VehicleFiaFlags }

// SetVehicleFiaFlags stores the VehicleFiaFlags of [CarStatusData]
func (data *CarStatusData) SetVehicleFiaFlags(v int8) { data.VehicleFiaFlags = v }

// GetEnginePowerICE returns the EnginePowerICE of [CarStatusData]
func (data *CarStatusData) GetEnginePowerICE() float32 { return data.EnginePowerICE }

// SetEnginePowerICE stores the EnginePowerICE of [CarStatusData]
func (data *CarStatusData) SetEnginePowerICE(v float32) { data.EnginePowerICE = v }

// GetEnginePowerMGUK returns the EnginePowerMGUK of [CarStatusData]
func (data *CarStatusData) GetEnginePowerMGUK() float32 { return data.EnginePowerMGUK }

// SetEnginePowerMGUK stores the EnginePowerMGUK of [CarStatusData]
func (data *CarStatusData) SetEnginePowerMGUK(v float32) { data.EnginePowerMGUK = v }

// GetErsStoreEnergy returns the ErsStoreEnergy of [CarStatusData]
func (data *CarStatusData) GetErsStoreEnergy() float32 { return data.ErsStoreEnergy }

// SetErsStoreEnergy stores the ErsStoreEnergy of [CarStatusData]
func (data *CarStatusData) SetErsStoreEnergy(v float32) { data.ErsStoreEnergy = v }

// GetErsDeployMode returns the ErsDeployMode of [CarStatusData]
func (data *CarStatusData) GetErsDeployMode() uint8 { return data.ErsDeployMode }

// SetErsDeployMode stores the ErsDeployMode of [CarStatusData]
func (data *CarStatusData) SetErsDeployMode(v uint8) { data.ErsDeployMode = v }

// GetErsHarvestedThisLapMGUK returns the ErsHarvestedThisLapMGUK of [CarStatusData]
func (data *CarStatusData) GetErsHarvestedThisLapMGUK() float32 { return data.ErsHarvestedThisLapMGUK }

// SetErsHarvestedThisLapMGUK stores the ErsHarvestedThisLapMGUK of [CarStatusData]
func (data *CarStatusData) SetErsHarvestedThisLapMGUK(v float32) { data.ErsHarvestedThisLapMGUK = v }

// GetErsHarvestedThisLapMGUH returns the ErsHarvestedThisLapMGUH of [CarStatusData]
func (data *CarStatusData) GetErsHarvestedThisLapMGUH() float32 { return data.ErsHarvestedThisLapMGUH }

// SetErsHarvestedThisLapMGUH stores the ErsHarvestedThisLapMGUH of [CarStatusData]
func (data *CarStatusData) SetErsHarvestedThisLapMGUH(v float32) { data.ErsHarvestedThisLapMGUH = v }

// GetErsHarvestedLimitPerLap returns the ErsHarvestedLimitPerLap of [CarStatusData]
func (data *CarStatusData) GetErsHarvestedLimitPerLap() float32 { return data.ErsHarvestedLimitPerLap }

// SetErsHarvestedLimitPerLap stores the ErsHarvestedLimitPerLap of [CarStatusData]
func (data *CarStatusData) SetErsHarvestedLimitPerLap(v float32) { data.ErsHarvestedLimitPerLap = v }

// GetErsDeployedThisLap returns the ErsDeployedThisLap of [CarStatusData]
func (data *CarStatusData) GetErsDeployedThisLap() float32 { return data.ErsDeployedThisLap }

// SetErsDeployedThisLap stores the ErsDeployedThisLap of [CarStatusData]
func (data *CarStatusData) SetErsDeployedThisLap(v float32) { data.ErsDeployedThisLap = v }

// GetNetworkPaused returns the NetworkPaused of [CarStatusData]
func (data *CarStatusData) GetNetworkPaused() uint8 { return data.NetworkPaused }

// SetNetworkPaused stores the NetworkPaused of [CarStatusData]
func (data *CarStatusData) SetNetworkPaused(v uint8) { data.NetworkPaused = v }
