// Code generated by tools/gen/accessors from car_motion_data.go. DO NOT EDIT.

package f12026s

// GetWorldPositionX returns the WorldPositionX of [CarMotionData]
func (data *CarMotionData) GetWorldPositionX() float32 { return data.WorldPositionX }

// SetWorldPositionX stores the WorldPositionX of [CarMotionData]
func (data *CarMotionData) SetWorldPositionX(v float32) { data.WorldPositionX = v }

// GetWorldPositionY returns the WorldPositionY of [CarMotionData]
func (data *CarMotionData) GetWorldPositionY() float32 { return data.WorldPositionY }

// SetWorldPositionY stores the WorldPositionY of [CarMotionData]
func (data *CarMotionData) SetWorldPositionY(v float32) { data.WorldPositionY = v }

// GetWorldPositionZ returns the WorldPositionZ of [CarMotionData]
func (data *CarMotionData) GetWorldPositionZ() float32 { return data.WorldPositionZ }

// SetWorldPositionZ stores the WorldPositionZ of [CarMotionData]
func (data *CarMotionData) SetWorldPositionZ(v float32) { data.WorldPositionZ = v }

// GetWorldVelocityX returns the WorldVelocityX of [CarMotionData]
func (data *CarMotionData) GetWorldVelocityX() float32 { return data.WorldVelocityX }

// SetWorldVelocityX stores the WorldVelocityX of [CarMotionData]
func (data *CarMotionData) SetWorldVelocityX(v float32) { data.WorldVelocityX = v }

// GetWorldVelocityY returns the WorldVelocityY of [CarMotionData]
func (data *CarMotionData) GetWorldVelocityY() float32 { return data.WorldVelocityY }

// SetWorldVelocityY stores the WorldVelocityY of [CarMotionData]
func (data *CarMotionData) SetWorldVelocityY(v float32) { data.WorldVelocityY = v }

// GetWorldVelocityZ returns the WorldVelocityZ of [CarMotionData]
func (data *CarMotionData) GetWorldVelocityZ() float32 { return data.WorldVelocityZ }

// SetWorldVelocityZ stores the WorldVelocityZ of [CarMotionData]
func (data *CarMotionData) SetWorldVelocityZ(v float32) { data.WorldVelocityZ = v }

// GetWorldForwardDirX returns the WorldForwardDirX of [CarMotionData]
func (data *CarMotionData) GetWorldForwardDirX() int16 { return data.WorldForwardDirX }

// SetWorldForwardDirX stores the WorldForwardDirX of [CarMotionData]
func (data *CarMotionData) SetWorldForwardDirX(v int16) { data.WorldForwardDirX = v }

// GetWorldForwardDirY returns the WorldForwardDirY of [CarMotionData]
func (data *CarMotionData) GetWorldForwardDirY() int16 { return data.WorldForwardDirY }

// SetWorldForwardDirY stores the WorldForwardDirY of [CarMotionData]
func (data *CarMotionData) SetWorldForwardDirY(v int16) { data.WorldForwardDirY = v }

// GetWorldForwardDirZ returns the WorldForwardDirZ of [CarMotionData]
func (data *CarMotionData) GetWorldForwardDirZ() int16 { return data.WorldForwardDirZ }

// SetWorldForwardDirZ stores the WorldForwardDirZ of [CarMotionData]
func (data *CarMotionData) SetWorldForwardDirZ(v int16) { data.WorldForwardDirZ = v }

// GetWorldRightDirX returns the WorldRightDirX of [CarMotionData]
func (data *CarMotionData) GetWorldRightDirX() int16 { return data.WorldRightDirX }

// SetWorldRightDirX stores the WorldRightDirX of [CarMotionData]
func (data *CarMotionData) SetWorldRightDirX(v int16) { data.WorldRightDirX = v }

// GetWorldRightDirY returns the WorldRightDirY of [CarMotionData]
func (data *CarMotionData) GetWorldRightDirY() int16 { return data.WorldRightDirY }

// SetWorldRightDirY stores the WorldRightDirY of [CarMotionData]
func (data *CarMotionData) SetWorldRightDirY(v int16) { data.WorldRightDirY = v }

// GetWorldRightDirZ returns the WorldRightDirZ of [CarMotionData]
func (data *CarMotionData) GetWorldRightDirZ() int16 { return data.WorldRightDirZ }

// SetWorldRightDirZ stores the WorldRightDirZ of [CarMotionData]
func (data *CarMotionData) SetWorldRightDirZ(v int16) { data.WorldRightDirZ = v }

// GetGForceLateral returns the GForceLateral of [CarMotionData]
func (data *CarMotionData) GetGForceLateral() int16 { return data.GForceLateral }

// SetGForceLateral stores the GForceLateral of [CarMotionData]
func (data *CarMotionData) SetGForceLateral(v int16) { data.GForceLateral = v }

// GetGForceLongitudinal returns the GForceLongitudinal of [CarMotionData]
func (data *CarMotionData) GetGForceLongitudinal() int16 { return data.GForceLongitudinal }

// SetGForceLongitudinal stores the GForceLongitudinal of [CarMotionData]
func (data *CarMotionData) SetGForceLongitudinal(v int16) { data.GForceLongitudinal = v }

// GetGForceVertical returns the GForceVertical of [CarMotionData]
func (data *CarMotionData) GetGForceVertical() int16 { return data.GForceVertical }

// SetGForceVertical stores the GForceVertical of [CarMotionData]
func (data *CarMotionData) SetGForceVertical(v int16) { data.GForceVertical = v }

// GetYaw returns the Yaw of [CarMotionData]
func (data *CarMotionData) GetYaw() float32 { return data.Yaw }

// SetYaw stores the Yaw of [CarMotionData]
func (data *CarMotionData) SetYaw(v float32) { data.Yaw = v }

// GetPitch returns the Pitch of [CarMotionData]
func (data *CarMotionData) GetPitch() float32 { return data.Pitch }

// SetPitch stores the Pitch of [CarMotionData]
func (data *CarMotionData) SetPitch(v float32) { data.Pitch = v }

// GetRoll returns the Roll of [CarMotionData]
func (data *CarMotionData) GetRoll() float32 { return data.Roll }

// SetRoll stores the Roll of [CarMotionData]
func (data *CarMotionData) SetRoll(v float32) { data.Roll = v }
