// Code generated by tools/gen/accessors from car_telemetry2_data.go. DO NOT EDIT.

package f12026s

// GetActiveAeroMode returns the ActiveAeroMode of [CarTelemetry2Data]
func (data *CarTelemetry2Data) GetActiveAeroMode() uint8 { return data.ActiveAeroMode }

// SetActiveAeroMode stores the ActiveAeroMode of [CarTelemetry2Data]
func (data *CarTelemetry2Data) SetActiveAeroMode(v uint8) { data.ActiveAeroMode = v }

// GetActiveAeroAvailable returns the ActiveAeroAvailable of [CarTelemetry2Data]
func (data *CarTelemetry2Data) GetActiveAeroAvailable() uint8 { return data.ActiveAeroAvailable }

// SetActiveAeroAvailable stores the ActiveAeroAvailable of [CarTelemetry2Data]
func (data *CarTelemetry2Data) SetActiveAeroAvailable(v uint8) { data.ActiveAeroAvailable = v }

// GetActiveAeroActivationDistance returns the ActiveAeroActivationDistance of [CarTelemetry2Data]
func (data *CarTelemetry2Data) GetActiveAeroActivationDistance() uint16 {
	return data.ActiveAeroActivationDistance
}

// SetActiveAeroActivationDistance stores the ActiveAeroActivationDistance of [CarTelemetry2Data]
func (data *CarTelemetry2Data) SetActiveAeroActivationDistance(v uint16) {
	data.ActiveAeroActivationDistance = v
}

// GetOvertakeAvailable returns the OvertakeAvailable of [CarTelemetry2Data]
func (data *CarTelemetry2Data) GetOvertakeAvailable() uint8 { return data.OvertakeAvailable }

// SetOvertakeAvailable stores the OvertakeAvailable of [CarTelemetry2Data]
func (data *CarTelemetry2Data) SetOvertakeAvailable(v uint8) { data.OvertakeAvailable = v }

// GetOvertakeActive returns the OvertakeActive of [CarTelemetry2Data]
func (data *CarTelemetry2Data) GetOvertakeActive() uint8 { return data.OvertakeActive }

// SetOvertakeActive stores the OvertakeActive of [CarTelemetry2Data]
func (data *CarTelemetry2Data) SetOvertakeActive(v uint8) { data.OvertakeActive = v }

// GetOvertakeActivationDistance returns the OvertakeActivationDistance of [CarTelemetry2Data]
func (data *CarTelemetry2Data) GetOvertakeActivationDistance() uint16 {
	return data.OvertakeActivationDistance
}

// SetOvertakeActivationDistance stores the OvertakeActivationDistance of [CarTelemetry2Data]
func (data *CarTelemetry2Data) SetOvertakeActivationDistance(v uint16) {
	data.OvertakeActivationDistance = v
}

// GetRegulations2026 returns the Regulations2026 of [CarTelemetry2Data]
func (data *CarTelemetry2Data) GetRegulations2026() uint8 { return data.Regulations2026 }

// SetRegulations2026 stores the Regulations2026 of [CarTelemetry2Data]
func (data *CarTelemetry2Data) SetRegulations2026(v uint8) { data.Regulations2026 = v }

// GetDrivingWrongWay returns the DrivingWrongWay of [CarTelemetry2Data]
func (data *CarTelemetry2Data) GetDrivingWrongWay() uint8 { return data.DrivingWrongWay }

// SetDrivingWrongWay stores the DrivingWrongWay of [CarTelemetry2Data]
func (data *CarTelemetry2Data) SetDrivingWrongWay(v uint8) { data.DrivingWrongWay = v }
