// Code generated by tools/gen/accessors from drs_zone.go. DO NOT EDIT.

package f12026s

// GetZoneStart returns [DRSZone.ZoneStart]
func (data *DRSZone) GetZoneStart() float32 { return data.ZoneStart }

// SetZoneStart stores [DRSZone.ZoneStart]
func (data *DRSZone) SetZoneStart(v float32) { data.ZoneStart = v }

// GetZoneEnd returns [DRSZone.ZoneEnd]
func (data *DRSZone) GetZoneEnd() float32 { return data.ZoneEnd }

// SetZoneEnd stores [DRSZone.ZoneEnd]
func (data *DRSZone) SetZoneEnd(v float32) { data.ZoneEnd = v }
