// Code generated by tools/gen/accessors from event_data_race_winner.go. DO NOT EDIT.

package f12026s

// GetVehicleIdx returns [EventDataRaceWinner.VehicleIdx]
func (data *EventDataRaceWinner) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores [EventDataRaceWinner.VehicleIdx]
func (data *EventDataRaceWinner) SetVehicleIdx(v uint8) { data.VehicleIdx = v }
