// Code generated by tools/gen/accessors from event_data_collision.go. DO NOT EDIT.

package f12026s

// GetVehicle1Idx returns the Vehicle1Idx of [EventDataCollision]
func (data *EventDataCollision) GetVehicle1Idx() uint8 { return data.Vehicle1Idx }

// SetVehicle1Idx stores the Vehicle1Idx of [EventDataCollision]
func (data *EventDataCollision) SetVehicle1Idx(v uint8) { data.Vehicle1Idx = v }

// GetVehicle2Idx returns the Vehicle2Idx of [EventDataCollision]
func (data *EventDataCollision) GetVehicle2Idx() uint8 { return data.Vehicle2Idx }

// SetVehicle2Idx stores the Vehicle2Idx of [EventDataCollision]
func (data *EventDataCollision) SetVehicle2Idx(v uint8) { data.Vehicle2Idx = v }

// GetSeverity returns the Severity of [EventDataCollision]
func (data *EventDataCollision) GetSeverity() uint8 { return data.Severity }

// SetSeverity stores the Severity of [EventDataCollision]
func (data *EventDataCollision) SetSeverity(v uint8) { data.Severity = v }
