// Code generated by tools/gen/accessors from event_data_penalty.go. DO NOT EDIT.

package f12026s

// GetPenaltyType returns the PenaltyType of [EventDataPenalty]
func (data *EventDataPenalty) GetPenaltyType() uint8 { return data.PenaltyType }

// SetPenaltyType stores the PenaltyType of [EventDataPenalty]
func (data *EventDataPenalty) SetPenaltyType(v uint8) { data.PenaltyType = v }

// GetInfringementType returns the InfringementType of [EventDataPenalty]
func (data *EventDataPenalty) GetInfringementType() uint8 { return data.InfringementType }

// SetInfringementType stores the InfringementType of [EventDataPenalty]
func (data *EventDataPenalty) SetInfringementType(v uint8) { data.InfringementType = v }

// GetVehicleIdx returns the VehicleIdx of [EventDataPenalty]
func (data *EventDataPenalty) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores the VehicleIdx of [EventDataPenalty]
func (data *EventDataPenalty) SetVehicleIdx(v uint8) { data.VehicleIdx = v }

// GetOtherVehicleIdx returns the OtherVehicleIdx of [EventDataPenalty]
func (data *EventDataPenalty) GetOtherVehicleIdx() uint8 { return data.OtherVehicleIdx }

// SetOtherVehicleIdx stores the OtherVehicleIdx of [EventDataPenalty]
func (data *EventDataPenalty) SetOtherVehicleIdx(v uint8) { data.OtherVehicleIdx = v }

// GetTime returns the Time of [EventDataPenalty]
func (data *EventDataPenalty) GetTime() uint8 { return data.Time }

// SetTime stores the Time of [EventDataPenalty]
func (data *EventDataPenalty) SetTime(v uint8) { data.Time = v }

// GetLapNum returns the LapNum of [EventDataPenalty]
func (data *EventDataPenalty) GetLapNum() uint8 { return data.LapNum }

// SetLapNum stores the LapNum of [EventDataPenalty]
func (data *EventDataPenalty) SetLapNum(v uint8) { data.LapNum = v }

// GetPlacesGained returns the PlacesGained of [EventDataPenalty]
func (data *EventDataPenalty) GetPlacesGained() uint8 { return data.PlacesGained }

// SetPlacesGained stores the PlacesGained of [EventDataPenalty]
func (data *EventDataPenalty) SetPlacesGained(v uint8) { data.PlacesGained = v }
