// Code generated by tools/gen/accessors from event_data_stop_go_penalty_served.go. DO NOT EDIT.

package f12026s

// GetVehicleIdx returns the VehicleIdx of [EventDataStopGoPenaltyServed]
func (data *EventDataStopGoPenaltyServed) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores the VehicleIdx of [EventDataStopGoPenaltyServed]
func (data *EventDataStopGoPenaltyServed) SetVehicleIdx(v uint8) { data.VehicleIdx = v }

// GetStopTime returns the StopTime of [EventDataStopGoPenaltyServed]
func (data *EventDataStopGoPenaltyServed) GetStopTime() float32 { return data.StopTime }

// SetStopTime stores the StopTime of [EventDataStopGoPenaltyServed]
func (data *EventDataStopGoPenaltyServed) SetStopTime(v float32) { data.StopTime = v }
