// Code generated by tools/gen/accessors from event_data_fastest_lap.go. DO NOT EDIT.

package f12026s

// GetVehicleIdx returns the VehicleIdx of [EventDataFastestLap]
func (data *EventDataFastestLap) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores the VehicleIdx of [EventDataFastestLap]
func (data *EventDataFastestLap) SetVehicleIdx(v uint8) { data.VehicleIdx = v }

// GetLapTime returns the LapTime of [EventDataFastestLap]
func (data *EventDataFastestLap) GetLapTime() float32 { return data.LapTime }

// SetLapTime stores the LapTime of [EventDataFastestLap]
func (data *EventDataFastestLap) SetLapTime(v float32) { data.LapTime = v }
