// Code generated by tools/gen/accessors from event_data_speed_trap.go. DO NOT EDIT.

package f12026s

// GetVehicleIdx returns [EventDataSpeedTrap.VehicleIdx]
func (data *EventDataSpeedTrap) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores [EventDataSpeedTrap.VehicleIdx]
func (data *EventDataSpeedTrap) SetVehicleIdx(v uint8) { data.VehicleIdx = v }

// GetSpeed returns [EventDataSpeedTrap.Speed]
func (data *EventDataSpeedTrap) GetSpeed() float32 { return data.Speed }

// SetSpeed stores [EventDataSpeedTrap.Speed]
func (data *EventDataSpeedTrap) SetSpeed(v float32) { data.Speed = v }

// GetIsOverallFastestInSession returns [EventDataSpeedTrap.IsOverallFastestInSession]
func (data *EventDataSpeedTrap) GetIsOverallFastestInSession() uint8 {
	return data.IsOverallFastestInSession
}

// SetIsOverallFastestInSession stores [EventDataSpeedTrap.IsOverallFastestInSession]
func (data *EventDataSpeedTrap) SetIsOverallFastestInSession(v uint8) {
	data.IsOverallFastestInSession = v
}

// GetIsDriverFastestInSession returns [EventDataSpeedTrap.IsDriverFastestInSession]
func (data *EventDataSpeedTrap) GetIsDriverFastestInSession() uint8 {
	return data.IsDriverFastestInSession
}

// SetIsDriverFastestInSession stores [EventDataSpeedTrap.IsDriverFastestInSession]
func (data *EventDataSpeedTrap) SetIsDriverFastestInSession(v uint8) {
	data.IsDriverFastestInSession = v
}

// GetFastestVehicleIdxInSession returns [EventDataSpeedTrap.FastestVehicleIdxInSession]
func (data *EventDataSpeedTrap) GetFastestVehicleIdxInSession() uint8 {
	return data.FastestVehicleIdxInSession
}

// SetFastestVehicleIdxInSession stores [EventDataSpeedTrap.FastestVehicleIdxInSession]
func (data *EventDataSpeedTrap) SetFastestVehicleIdxInSession(v uint8) {
	data.FastestVehicleIdxInSession = v
}

// GetFastestSpeedInSession returns [EventDataSpeedTrap.FastestSpeedInSession]
func (data *EventDataSpeedTrap) GetFastestSpeedInSession() float32 { return data.FastestSpeedInSession }

// SetFastestSpeedInSession stores [EventDataSpeedTrap.FastestSpeedInSession]
func (data *EventDataSpeedTrap) SetFastestSpeedInSession(v float32) { data.FastestSpeedInSession = v }
