// Code generated by tools/gen/accessors from event_data_fastest_lap.go. DO NOT EDIT.

package f12026s

// GetVehicleIdx returns [EventDataFastestLap.VehicleIdx]
func (data *EventDataFastestLap) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores [EventDataFastestLap.VehicleIdx]
func (data *EventDataFastestLap) SetVehicleIdx(v uint8) { data.VehicleIdx = v }

// GetLapTime returns [EventDataFastestLap.LapTime]
func (data *EventDataFastestLap) GetLapTime() float32 { return data.LapTime }

// SetLapTime stores [EventDataFastestLap.LapTime]
func (data *EventDataFastestLap) SetLapTime(v float32) { data.LapTime = v }
