// Code generated by tools/gen/accessors from event_data_retirement.go. DO NOT EDIT.

package f12026s

// GetVehicleIdx returns [EventDataRetirement.VehicleIdx]
func (data *EventDataRetirement) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores [EventDataRetirement.VehicleIdx]
func (data *EventDataRetirement) SetVehicleIdx(v uint8) { data.VehicleIdx = v }

// GetReason returns [EventDataRetirement.Reason]
func (data *EventDataRetirement) GetReason() uint8 { return data.Reason }

// SetReason stores [EventDataRetirement.Reason]
func (data *EventDataRetirement) SetReason(v uint8) { data.Reason = v }
