// Code generated by tools/gen/accessors from event_data_stop_go_penalty_served.go. DO NOT EDIT.

package f12026s

// GetVehicleIdx returns [EventDataStopGoPenaltyServed.VehicleIdx]
func (data *EventDataStopGoPenaltyServed) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores [EventDataStopGoPenaltyServed.VehicleIdx]
func (data *EventDataStopGoPenaltyServed) SetVehicleIdx(v uint8) { data.VehicleIdx = v }

// GetStopTime returns [EventDataStopGoPenaltyServed.StopTime]
func (data *EventDataStopGoPenaltyServed) GetStopTime() float32 { return data.StopTime }

// SetStopTime stores [EventDataStopGoPenaltyServed.StopTime]
func (data *EventDataStopGoPenaltyServed) SetStopTime(v float32) { data.StopTime = v }
