// Code generated by tools/gen/accessors from event_data_retirement.go. DO NOT EDIT.

package f12026s

// GetVehicleIdx returns the VehicleIdx of [EventDataRetirement]
func (data *EventDataRetirement) GetVehicleIdx() uint8 { return data.VehicleIdx }

// SetVehicleIdx stores the VehicleIdx of [EventDataRetirement]
func (data *EventDataRetirement) SetVehicleIdx(v uint8) { data.VehicleIdx = v }

// GetReason returns the Reason of [EventDataRetirement]
func (data *EventDataRetirement) GetReason() uint8 { return data.Reason }

// SetReason stores the Reason of [EventDataRetirement]
func (data *EventDataRetirement) SetReason(v uint8) { data.Reason = v }
