// Code generated by tools/gen/accessors from event_data_start_lights.go. DO NOT EDIT.

package f12026s

// GetNumLights returns the NumLights of [EventDataStartLights]
func (data *EventDataStartLights) GetNumLights() uint8 { return data.NumLights }

// SetNumLights stores the NumLights of [EventDataStartLights]
func (data *EventDataStartLights) SetNumLights(v uint8) { data.NumLights = v }
