// Code generated by tools/gen/accessors from event_data_flashback.go. DO NOT EDIT.

package f12026s

// GetFlashbackFrameIdentifier returns [EventDataFlashback.FlashbackFrameIdentifier]
func (data *EventDataFlashback) GetFlashbackFrameIdentifier() uint32 {
	return data.FlashbackFrameIdentifier
}

// SetFlashbackFrameIdentifier stores [EventDataFlashback.FlashbackFrameIdentifier]
func (data *EventDataFlashback) SetFlashbackFrameIdentifier(v uint32) {
	data.FlashbackFrameIdentifier = v
}

// GetFlashbackSessionTime returns [EventDataFlashback.FlashbackSessionTime]
func (data *EventDataFlashback) GetFlashbackSessionTime() float32 { return data.FlashbackSessionTime }

// SetFlashbackSessionTime stores [EventDataFlashback.FlashbackSessionTime]
func (data *EventDataFlashback) SetFlashbackSessionTime(v float32) { data.FlashbackSessionTime = v }
