// Code generated by tools/gen/accessors from final_classification_data.go. DO NOT EDIT.

package f12026s

// GetPosition returns the Position of [FinalClassificationData]
func (data *FinalClassificationData) GetPosition() uint8 { return data.Position }

// SetPosition stores the Position of [FinalClassificationData]
func (data *FinalClassificationData) SetPosition(v uint8) { data.Position = v }

// GetNumLaps returns the NumLaps of [FinalClassificationData]
func (data *FinalClassificationData) GetNumLaps() uint8 { return data.NumLaps }

// SetNumLaps stores the NumLaps of [FinalClassificationData]
func (data *FinalClassificationData) SetNumLaps(v uint8) { data.NumLaps = v }

// GetGridPosition returns the GridPosition of [FinalClassificationData]
func (data *FinalClassificationData) GetGridPosition() uint8 { return data.GridPosition }

// SetGridPosition stores the GridPosition of [FinalClassificationData]
func (data *FinalClassificationData) SetGridPosition(v uint8) { data.GridPosition = v }

// GetPoints returns the Points of [FinalClassificationData]
func (data *FinalClassificationData) GetPoints() uint8 { return data.Points }

// SetPoints stores the Points of [FinalClassificationData]
func (data *FinalClassificationData) SetPoints(v uint8) { data.Points = v }

// GetNumPitStops returns the NumPitStops of [FinalClassificationData]
func (data *FinalClassificationData) GetNumPitStops() uint8 { return data.NumPitStops }

// SetNumPitStops stores the NumPitStops of [FinalClassificationData]
func (data *FinalClassificationData) SetNumPitStops(v uint8) { data.NumPitStops = v }

// GetResultStatus returns the ResultStatus of [FinalClassificationData]
func (data *FinalClassificationData) GetResultStatus() uint8 { return data.ResultStatus }

// SetResultStatus stores the ResultStatus of [FinalClassificationData]
func (data *FinalClassificationData) SetResultStatus(v uint8) { data.ResultStatus = v }

// GetResultReason returns the ResultReason of [FinalClassificationData]
func (data *FinalClassificationData) GetResultReason() uint8 { return data.ResultReason }

// SetResultReason stores the ResultReason of [FinalClassificationData]
func (data *FinalClassificationData) SetResultReason(v uint8) { data.ResultReason = v }

// GetBestLapTimeInMS returns the BestLapTimeInMS of [FinalClassificationData]
func (data *FinalClassificationData) GetBestLapTimeInMS() uint32 { return data.BestLapTimeInMS }

// SetBestLapTimeInMS stores the BestLapTimeInMS of [FinalClassificationData]
func (data *FinalClassificationData) SetBestLapTimeInMS(v uint32) { data.BestLapTimeInMS = v }

// GetTotalRaceTime returns the TotalRaceTime of [FinalClassificationData]
func (data *FinalClassificationData) GetTotalRaceTime() float64 { return data.TotalRaceTime }

// SetTotalRaceTime stores the TotalRaceTime of [FinalClassificationData]
func (data *FinalClassificationData) SetTotalRaceTime(v float64) { data.TotalRaceTime = v }

// GetPenaltiesTime returns the PenaltiesTime of [FinalClassificationData]
func (data *FinalClassificationData) GetPenaltiesTime() uint8 { return data.PenaltiesTime }

// SetPenaltiesTime stores the PenaltiesTime of [FinalClassificationData]
func (data *FinalClassificationData) SetPenaltiesTime(v uint8) { data.PenaltiesTime = v }

// GetNumPenalties returns the NumPenalties of [FinalClassificationData]
func (data *FinalClassificationData) GetNumPenalties() uint8 { return data.NumPenalties }

// SetNumPenalties stores the NumPenalties of [FinalClassificationData]
func (data *FinalClassificationData) SetNumPenalties(v uint8) { data.NumPenalties = v }

// GetNumTyreStints returns the NumTyreStints of [FinalClassificationData]
func (data *FinalClassificationData) GetNumTyreStints() uint8 { return data.NumTyreStints }

// SetNumTyreStints stores the NumTyreStints of [FinalClassificationData]
func (data *FinalClassificationData) SetNumTyreStints(v uint8) { data.NumTyreStints = v }

// GetTyreStintsActual returns the TyreStintsActual element of [FinalClassificationData] at index
func (data *FinalClassificationData) GetTyreStintsActual(index int) uint8 {
	return data.TyreStintsActual[index]
}

// SetTyreStintsActual stores the TyreStintsActual element of [FinalClassificationData] at index
func (data *FinalClassificationData) SetTyreStintsActual(index int, v uint8) {
	data.TyreStintsActual[index] = v
}

// GetTyreStintsVisual returns the TyreStintsVisual element of [FinalClassificationData] at index
func (data *FinalClassificationData) GetTyreStintsVisual(index int) uint8 {
	return data.TyreStintsVisual[index]
}

// SetTyreStintsVisual stores the TyreStintsVisual element of [FinalClassificationData] at index
func (data *FinalClassificationData) SetTyreStintsVisual(index int, v uint8) {
	data.TyreStintsVisual[index] = v
}

// GetTyreStintsEndLaps returns the TyreStintsEndLaps element of [FinalClassificationData] at index
func (data *FinalClassificationData) GetTyreStintsEndLaps(index int) uint8 {
	return data.TyreStintsEndLaps[index]
}

// SetTyreStintsEndLaps stores the TyreStintsEndLaps element of [FinalClassificationData] at index
func (data *FinalClassificationData) SetTyreStintsEndLaps(index int, v uint8) {
	data.TyreStintsEndLaps[index] = v
}
