// Code generated by tools/gen/accessors from livery_colour.go. DO NOT EDIT.

package f12026s

// GetRed returns the Red of [LiveryColour]
func (data *LiveryColour) GetRed() uint8 { return data.Red }

// SetRed stores the Red of [LiveryColour]
func (data *LiveryColour) SetRed(v uint8) { data.Red = v }

// GetGreen returns the Green of [LiveryColour]
func (data *LiveryColour) GetGreen() uint8 { return data.Green }

// SetGreen stores the Green of [LiveryColour]
func (data *LiveryColour) SetGreen(v uint8) { data.Green = v }

// GetBlue returns the Blue of [LiveryColour]
func (data *LiveryColour) GetBlue() uint8 { return data.Blue }

// SetBlue stores the Blue of [LiveryColour]
func (data *LiveryColour) SetBlue(v uint8) { data.Blue = v }
