// Code generated by tools/gen/accessors from lobby_info_data.go. DO NOT EDIT.

package f12026s

// GetAiControlled returns the AiControlled of [LobbyInfoData]
func (data *LobbyInfoData) GetAiControlled() uint8 { return data.AiControlled }

// SetAiControlled stores the AiControlled of [LobbyInfoData]
func (data *LobbyInfoData) SetAiControlled(v uint8) { data.AiControlled = v }

// GetTeamId returns the TeamId of [LobbyInfoData]
func (data *LobbyInfoData) GetTeamId() uint16 { return data.TeamId }

// SetTeamId stores the TeamId of [LobbyInfoData]
func (data *LobbyInfoData) SetTeamId(v uint16) { data.TeamId = v }

// GetNationality returns the Nationality of [LobbyInfoData]
func (data *LobbyInfoData) GetNationality() uint8 { return data.Nationality }

// SetNationality stores the Nationality of [LobbyInfoData]
func (data *LobbyInfoData) SetNationality(v uint8) { data.Nationality = v }

// GetPlatform returns the Platform of [LobbyInfoData]
func (data *LobbyInfoData) GetPlatform() uint8 { return data.Platform }

// SetPlatform stores the Platform of [LobbyInfoData]
func (data *LobbyInfoData) SetPlatform(v uint8) { data.Platform = v }

// GetCarNumber returns the CarNumber of [LobbyInfoData]
func (data *LobbyInfoData) GetCarNumber() uint8 { return data.CarNumber }

// SetCarNumber stores the CarNumber of [LobbyInfoData]
func (data *LobbyInfoData) SetCarNumber(v uint8) { data.CarNumber = v }

// GetYourTelemetry returns the YourTelemetry of [LobbyInfoData]
func (data *LobbyInfoData) GetYourTelemetry() uint8 { return data.YourTelemetry }

// SetYourTelemetry stores the YourTelemetry of [LobbyInfoData]
func (data *LobbyInfoData) SetYourTelemetry(v uint8) { data.YourTelemetry = v }

// GetShowOnlineNames returns the ShowOnlineNames of [LobbyInfoData]
func (data *LobbyInfoData) GetShowOnlineNames() uint8 { return data.ShowOnlineNames }

// SetShowOnlineNames stores the ShowOnlineNames of [LobbyInfoData]
func (data *LobbyInfoData) SetShowOnlineNames(v uint8) { data.ShowOnlineNames = v }

// GetTechLevel returns the TechLevel of [LobbyInfoData]
func (data *LobbyInfoData) GetTechLevel() uint16 { return data.TechLevel }

// SetTechLevel stores the TechLevel of [LobbyInfoData]
func (data *LobbyInfoData) SetTechLevel(v uint16) { data.TechLevel = v }

// GetReadyStatus returns the ReadyStatus of [LobbyInfoData]
func (data *LobbyInfoData) GetReadyStatus() uint8 { return data.ReadyStatus }

// SetReadyStatus stores the ReadyStatus of [LobbyInfoData]
func (data *LobbyInfoData) SetReadyStatus(v uint8) { data.ReadyStatus = v }
