// Code generated by tools/gen/accessors from lobby_info_data.go. DO NOT EDIT.

package f12026s

// GetAiControlled returns [LobbyInfoData.AiControlled]
func (data *LobbyInfoData) GetAiControlled() uint8 { return data.AiControlled }

// SetAiControlled stores [LobbyInfoData.AiControlled]
func (data *LobbyInfoData) SetAiControlled(v uint8) { data.AiControlled = v }

// GetTeamId returns [LobbyInfoData.TeamId]
func (data *LobbyInfoData) GetTeamId() uint16 { return data.TeamId }

// SetTeamId stores [LobbyInfoData.TeamId]
func (data *LobbyInfoData) SetTeamId(v uint16) { data.TeamId = v }

// GetNationality returns [LobbyInfoData.Nationality]
func (data *LobbyInfoData) GetNationality() uint8 { return data.Nationality }

// SetNationality stores [LobbyInfoData.Nationality]
func (data *LobbyInfoData) SetNationality(v uint8) { data.Nationality = v }

// GetPlatform returns [LobbyInfoData.Platform]
func (data *LobbyInfoData) GetPlatform() uint8 { return data.Platform }

// SetPlatform stores [LobbyInfoData.Platform]
func (data *LobbyInfoData) SetPlatform(v uint8) { data.Platform = v }

// GetCarNumber returns [LobbyInfoData.CarNumber]
func (data *LobbyInfoData) GetCarNumber() uint8 { return data.CarNumber }

// SetCarNumber stores [LobbyInfoData.CarNumber]
func (data *LobbyInfoData) SetCarNumber(v uint8) { data.CarNumber = v }

// GetYourTelemetry returns [LobbyInfoData.YourTelemetry]
func (data *LobbyInfoData) GetYourTelemetry() uint8 { return data.YourTelemetry }

// SetYourTelemetry stores [LobbyInfoData.YourTelemetry]
func (data *LobbyInfoData) SetYourTelemetry(v uint8) { data.YourTelemetry = v }

// GetShowOnlineNames returns [LobbyInfoData.ShowOnlineNames]
func (data *LobbyInfoData) GetShowOnlineNames() uint8 { return data.ShowOnlineNames }

// SetShowOnlineNames stores [LobbyInfoData.ShowOnlineNames]
func (data *LobbyInfoData) SetShowOnlineNames(v uint8) { data.ShowOnlineNames = v }

// GetTechLevel returns [LobbyInfoData.TechLevel]
func (data *LobbyInfoData) GetTechLevel() uint16 { return data.TechLevel }

// SetTechLevel stores [LobbyInfoData.TechLevel]
func (data *LobbyInfoData) SetTechLevel(v uint16) { data.TechLevel = v }

// GetReadyStatus returns [LobbyInfoData.ReadyStatus]
func (data *LobbyInfoData) GetReadyStatus() uint8 { return data.ReadyStatus }

// SetReadyStatus stores [LobbyInfoData.ReadyStatus]
func (data *LobbyInfoData) SetReadyStatus(v uint8) { data.ReadyStatus = v }
