// Code generated by tools/gen/accessors from packet_lap_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns the Header of [PacketLapData]
func (data *PacketLapData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketLapData]
func (data *PacketLapData) SetHeader(v PacketHeader) { data.Header = v }

// GetTimeTrialPBCarIdx returns the TimeTrialPBCarIdx of [PacketLapData]
func (data *PacketLapData) GetTimeTrialPBCarIdx() uint8 { return data.TimeTrialPBCarIdx }

// SetTimeTrialPBCarIdx stores the TimeTrialPBCarIdx of [PacketLapData]
func (data *PacketLapData) SetTimeTrialPBCarIdx(v uint8) { data.TimeTrialPBCarIdx = v }

// GetTimeTrialRivalCarIdx returns the TimeTrialRivalCarIdx of [PacketLapData]
func (data *PacketLapData) GetTimeTrialRivalCarIdx() uint8 { return data.TimeTrialRivalCarIdx }

// SetTimeTrialRivalCarIdx stores the TimeTrialRivalCarIdx of [PacketLapData]
func (data *PacketLapData) SetTimeTrialRivalCarIdx(v uint8) { data.TimeTrialRivalCarIdx = v }
