// Code generated by tools/gen/accessors from packet_event_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns the Header of [PacketEventData]
func (data *PacketEventData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketEventData]
func (data *PacketEventData) SetHeader(v PacketHeader) { data.Header = v }

// GetEventStringCode returns the EventStringCode of [PacketEventData]
func (data *PacketEventData) GetEventStringCode() EventCode { return data.EventStringCode }

// SetEventStringCode stores the EventStringCode of [PacketEventData]
func (data *PacketEventData) SetEventStringCode(v EventCode) { data.EventStringCode = v }

// GetEventDetails returns the EventDetails of [PacketEventData]
func (data *PacketEventData) GetEventDetails() EventDataDetails { return data.EventDetails }

// SetEventDetails stores the EventDetails of [PacketEventData]
func (data *PacketEventData) SetEventDetails(v EventDataDetails) { data.EventDetails = v }
