// Code generated by tools/gen/accessors from packet_tyre_sets_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns the Header of [PacketTyreSetsData]
func (data *PacketTyreSetsData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketTyreSetsData]
func (data *PacketTyreSetsData) SetHeader(v PacketHeader) { data.Header = v }

// GetCarIdx returns the CarIdx of [PacketTyreSetsData]
func (data *PacketTyreSetsData) GetCarIdx() uint8 { return data.CarIdx }

// SetCarIdx stores the CarIdx of [PacketTyreSetsData]
func (data *PacketTyreSetsData) SetCarIdx(v uint8) { data.CarIdx = v }

// GetFittedIdx returns the FittedIdx of [PacketTyreSetsData]
func (data *PacketTyreSetsData) GetFittedIdx() uint8 { return data.FittedIdx }

// SetFittedIdx stores the FittedIdx of [PacketTyreSetsData]
func (data *PacketTyreSetsData) SetFittedIdx(v uint8) { data.FittedIdx = v }
