// Code generated by tools/gen/accessors from packet_final_classification_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns [PacketFinalClassificationData.Header]
func (data *PacketFinalClassificationData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketFinalClassificationData.Header]
func (data *PacketFinalClassificationData) SetHeader(v PacketHeader) { data.Header = v }

// GetNumCars returns [PacketFinalClassificationData.NumCars]
func (data *PacketFinalClassificationData) GetNumCars() uint8 { return data.NumCars }

// SetNumCars stores [PacketFinalClassificationData.NumCars]
func (data *PacketFinalClassificationData) SetNumCars(v uint8) { data.NumCars = v }
