// Code generated by tools/gen/accessors from packet_time_trial_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns [PacketTimeTrialData.Header]
func (data *PacketTimeTrialData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketTimeTrialData.Header]
func (data *PacketTimeTrialData) SetHeader(v PacketHeader) { data.Header = v }

// GetPlayerSessionBestDataSet returns [PacketTimeTrialData.PlayerSessionBestDataSet]
func (data *PacketTimeTrialData) GetPlayerSessionBestDataSet() TimeTrialDataSet {
	return data.PlayerSessionBestDataSet
}

// SetPlayerSessionBestDataSet stores [PacketTimeTrialData.PlayerSessionBestDataSet]
func (data *PacketTimeTrialData) SetPlayerSessionBestDataSet(v TimeTrialDataSet) {
	data.PlayerSessionBestDataSet = v
}

// GetPersonalBestDataSet returns [PacketTimeTrialData.PersonalBestDataSet]
func (data *PacketTimeTrialData) GetPersonalBestDataSet() TimeTrialDataSet {
	return data.PersonalBestDataSet
}

// SetPersonalBestDataSet stores [PacketTimeTrialData.PersonalBestDataSet]
func (data *PacketTimeTrialData) SetPersonalBestDataSet(v TimeTrialDataSet) {
	data.PersonalBestDataSet = v
}

// GetRivalDataSet returns [PacketTimeTrialData.RivalDataSet]
func (data *PacketTimeTrialData) GetRivalDataSet() TimeTrialDataSet { return data.RivalDataSet }

// SetRivalDataSet stores [PacketTimeTrialData.RivalDataSet]
func (data *PacketTimeTrialData) SetRivalDataSet(v TimeTrialDataSet) { data.RivalDataSet = v }
