// Code generated by tools/gen/accessors from packet_time_trial_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns the Header of [PacketTimeTrialData]
func (data *PacketTimeTrialData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketTimeTrialData]
func (data *PacketTimeTrialData) SetHeader(v PacketHeader) { data.Header = v }

// GetPlayerSessionBestDataSet returns the PlayerSessionBestDataSet of [PacketTimeTrialData]
func (data *PacketTimeTrialData) GetPlayerSessionBestDataSet() TimeTrialDataSet {
	return data.PlayerSessionBestDataSet
}

// SetPlayerSessionBestDataSet stores the PlayerSessionBestDataSet of [PacketTimeTrialData]
func (data *PacketTimeTrialData) SetPlayerSessionBestDataSet(v TimeTrialDataSet) {
	data.PlayerSessionBestDataSet = v
}

// GetPersonalBestDataSet returns the PersonalBestDataSet of [PacketTimeTrialData]
func (data *PacketTimeTrialData) GetPersonalBestDataSet() TimeTrialDataSet {
	return data.PersonalBestDataSet
}

// SetPersonalBestDataSet stores the PersonalBestDataSet of [PacketTimeTrialData]
func (data *PacketTimeTrialData) SetPersonalBestDataSet(v TimeTrialDataSet) {
	data.PersonalBestDataSet = v
}

// GetRivalDataSet returns the RivalDataSet of [PacketTimeTrialData]
func (data *PacketTimeTrialData) GetRivalDataSet() TimeTrialDataSet { return data.RivalDataSet }

// SetRivalDataSet stores the RivalDataSet of [PacketTimeTrialData]
func (data *PacketTimeTrialData) SetRivalDataSet(v TimeTrialDataSet) { data.RivalDataSet = v }
