// Code generated by tools/gen/accessors from packet_car_damage_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns the Header of [PacketCarDamageData]
func (data *PacketCarDamageData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketCarDamageData]
func (data *PacketCarDamageData) SetHeader(v PacketHeader) { data.Header = v }
