// Code generated by tools/gen/accessors from packet_car_status_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns the Header of [PacketCarStatusData]
func (data *PacketCarStatusData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketCarStatusData]
func (data *PacketCarStatusData) SetHeader(v PacketHeader) { data.Header = v }
