// Code generated by tools/gen/accessors from packet_session_history_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns [PacketSessionHistoryData.Header]
func (data *PacketSessionHistoryData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketSessionHistoryData.Header]
func (data *PacketSessionHistoryData) SetHeader(v PacketHeader) { data.Header = v }

// GetCarIdx returns [PacketSessionHistoryData.CarIdx]
func (data *PacketSessionHistoryData) GetCarIdx() uint8 { return data.CarIdx }

// SetCarIdx stores [PacketSessionHistoryData.CarIdx]
func (data *PacketSessionHistoryData) SetCarIdx(v uint8) { data.CarIdx = v }

// GetNumLaps returns [PacketSessionHistoryData.NumLaps]
func (data *PacketSessionHistoryData) GetNumLaps() uint8 { return data.NumLaps }

// SetNumLaps stores [PacketSessionHistoryData.NumLaps]
func (data *PacketSessionHistoryData) SetNumLaps(v uint8) { data.NumLaps = v }

// GetNumTyreStints returns [PacketSessionHistoryData.NumTyreStints]
func (data *PacketSessionHistoryData) GetNumTyreStints() uint8 { return data.NumTyreStints }

// SetNumTyreStints stores [PacketSessionHistoryData.NumTyreStints]
func (data *PacketSessionHistoryData) SetNumTyreStints(v uint8) { data.NumTyreStints = v }

// GetBestLapTimeLapNum returns [PacketSessionHistoryData.BestLapTimeLapNum]
func (data *PacketSessionHistoryData) GetBestLapTimeLapNum() uint8 { return data.BestLapTimeLapNum }

// SetBestLapTimeLapNum stores [PacketSessionHistoryData.BestLapTimeLapNum]
func (data *PacketSessionHistoryData) SetBestLapTimeLapNum(v uint8) { data.BestLapTimeLapNum = v }

// GetBestSector1LapNum returns [PacketSessionHistoryData.BestSector1LapNum]
func (data *PacketSessionHistoryData) GetBestSector1LapNum() uint8 { return data.BestSector1LapNum }

// SetBestSector1LapNum stores [PacketSessionHistoryData.BestSector1LapNum]
func (data *PacketSessionHistoryData) SetBestSector1LapNum(v uint8) { data.BestSector1LapNum = v }

// GetBestSector2LapNum returns [PacketSessionHistoryData.BestSector2LapNum]
func (data *PacketSessionHistoryData) GetBestSector2LapNum() uint8 { return data.BestSector2LapNum }

// SetBestSector2LapNum stores [PacketSessionHistoryData.BestSector2LapNum]
func (data *PacketSessionHistoryData) SetBestSector2LapNum(v uint8) { data.BestSector2LapNum = v }

// GetBestSector3LapNum returns [PacketSessionHistoryData.BestSector3LapNum]
func (data *PacketSessionHistoryData) GetBestSector3LapNum() uint8 { return data.BestSector3LapNum }

// SetBestSector3LapNum stores [PacketSessionHistoryData.BestSector3LapNum]
func (data *PacketSessionHistoryData) SetBestSector3LapNum(v uint8) { data.BestSector3LapNum = v }

// GetTyreStintsHistoryData returns the element of [PacketSessionHistoryData.TyreStintsHistoryData] at index
func (data *PacketSessionHistoryData) GetTyreStintsHistoryData(index int) TyreStintHistoryData {
	return data.TyreStintsHistoryData[index]
}

// SetTyreStintsHistoryData stores the element of [PacketSessionHistoryData.TyreStintsHistoryData] at index
func (data *PacketSessionHistoryData) SetTyreStintsHistoryData(index int, v TyreStintHistoryData) {
	data.TyreStintsHistoryData[index] = v
}
