// Code generated by tools/gen/accessors from packet_motion_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns the Header of [PacketMotionData]
func (data *PacketMotionData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketMotionData]
func (data *PacketMotionData) SetHeader(v PacketHeader) { data.Header = v }
