// Code generated by tools/gen/accessors from packet_car_telemetry2_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns [PacketCarTelemetry2Data.Header]
func (data *PacketCarTelemetry2Data) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketCarTelemetry2Data.Header]
func (data *PacketCarTelemetry2Data) SetHeader(v PacketHeader) { data.Header = v }
