// Code generated by tools/gen/accessors from packet_header.go. DO NOT EDIT.

package f12026s

// GetPacketFormat returns [PacketHeader.PacketFormat]
func (data *PacketHeader) GetPacketFormat() uint16 { return data.PacketFormat }

// SetPacketFormat stores [PacketHeader.PacketFormat]
func (data *PacketHeader) SetPacketFormat(v uint16) { data.PacketFormat = v }

// GetGameYear returns [PacketHeader.GameYear]
func (data *PacketHeader) GetGameYear() uint8 { return data.GameYear }

// SetGameYear stores [PacketHeader.GameYear]
func (data *PacketHeader) SetGameYear(v uint8) { data.GameYear = v }

// GetGameMajorVersion returns [PacketHeader.GameMajorVersion]
func (data *PacketHeader) GetGameMajorVersion() uint8 { return data.GameMajorVersion }

// SetGameMajorVersion stores [PacketHeader.GameMajorVersion]
func (data *PacketHeader) SetGameMajorVersion(v uint8) { data.GameMajorVersion = v }

// GetGameMinorVersion returns [PacketHeader.GameMinorVersion]
func (data *PacketHeader) GetGameMinorVersion() uint8 { return data.GameMinorVersion }

// SetGameMinorVersion stores [PacketHeader.GameMinorVersion]
func (data *PacketHeader) SetGameMinorVersion(v uint8) { data.GameMinorVersion = v }

// GetPacketVersion returns [PacketHeader.PacketVersion]
func (data *PacketHeader) GetPacketVersion() uint8 { return data.PacketVersion }

// SetPacketVersion stores [PacketHeader.PacketVersion]
func (data *PacketHeader) SetPacketVersion(v uint8) { data.PacketVersion = v }

// GetPacketId returns [PacketHeader.PacketId]
func (data *PacketHeader) GetPacketId() PacketID { return data.PacketId }

// SetPacketId stores [PacketHeader.PacketId]
func (data *PacketHeader) SetPacketId(v PacketID) { data.PacketId = v }

// GetSessionUID returns [PacketHeader.SessionUID]
func (data *PacketHeader) GetSessionUID() uint64 { return data.SessionUID }

// SetSessionUID stores [PacketHeader.SessionUID]
func (data *PacketHeader) SetSessionUID(v uint64) { data.SessionUID = v }

// GetSessionTime returns [PacketHeader.SessionTime]
func (data *PacketHeader) GetSessionTime() float32 { return data.SessionTime }

// SetSessionTime stores [PacketHeader.SessionTime]
func (data *PacketHeader) SetSessionTime(v float32) { data.SessionTime = v }

// GetFrameIdentifier returns [PacketHeader.FrameIdentifier]
func (data *PacketHeader) GetFrameIdentifier() uint32 { return data.FrameIdentifier }

// SetFrameIdentifier stores [PacketHeader.FrameIdentifier]
func (data *PacketHeader) SetFrameIdentifier(v uint32) { data.FrameIdentifier = v }

// GetOverallFrameIdentifier returns [PacketHeader.OverallFrameIdentifier]
func (data *PacketHeader) GetOverallFrameIdentifier() uint32 { return data.OverallFrameIdentifier }

// SetOverallFrameIdentifier stores [PacketHeader.OverallFrameIdentifier]
func (data *PacketHeader) SetOverallFrameIdentifier(v uint32) { data.OverallFrameIdentifier = v }

// GetPlayerCarIndex returns [PacketHeader.PlayerCarIndex]
func (data *PacketHeader) GetPlayerCarIndex() uint8 { return data.PlayerCarIndex }

// SetPlayerCarIndex stores [PacketHeader.PlayerCarIndex]
func (data *PacketHeader) SetPlayerCarIndex(v uint8) { data.PlayerCarIndex = v }

// GetSecondaryPlayerCarIndex returns [PacketHeader.SecondaryPlayerCarIndex]
func (data *PacketHeader) GetSecondaryPlayerCarIndex() uint8 { return data.SecondaryPlayerCarIndex }

// SetSecondaryPlayerCarIndex stores [PacketHeader.SecondaryPlayerCarIndex]
func (data *PacketHeader) SetSecondaryPlayerCarIndex(v uint8) { data.SecondaryPlayerCarIndex = v }
