// Code generated by tools/gen/accessors from packet_session_data.go. DO NOT EDIT.

package f12026s

import (
	"github.com/daanv2/race-game-dashboard/pkg/f1game/f1common"
)

// GetHeader returns [PacketSessionData.Header]
func (data *PacketSessionData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores [PacketSessionData.Header]
func (data *PacketSessionData) SetHeader(v PacketHeader) { data.Header = v }

// GetWeather returns [PacketSessionData.Weather]
func (data *PacketSessionData) GetWeather() uint8 { return data.Weather }

// SetWeather stores [PacketSessionData.Weather]
func (data *PacketSessionData) SetWeather(v uint8) { data.Weather = v }

// GetTrackTemperature returns [PacketSessionData.TrackTemperature]
func (data *PacketSessionData) GetTrackTemperature() int8 { return data.TrackTemperature }

// SetTrackTemperature stores [PacketSessionData.TrackTemperature]
func (data *PacketSessionData) SetTrackTemperature(v int8) { data.TrackTemperature = v }

// GetAirTemperature returns [PacketSessionData.AirTemperature]
func (data *PacketSessionData) GetAirTemperature() int8 { return data.AirTemperature }

// SetAirTemperature stores [PacketSessionData.AirTemperature]
func (data *PacketSessionData) SetAirTemperature(v int8) { data.AirTemperature = v }

// GetTotalLaps returns [PacketSessionData.TotalLaps]
func (data *PacketSessionData) GetTotalLaps() uint8 { return data.TotalLaps }

// SetTotalLaps stores [PacketSessionData.TotalLaps]
func (data *PacketSessionData) SetTotalLaps(v uint8) { data.TotalLaps = v }

// GetTrackLength returns [PacketSessionData.TrackLength]
func (data *PacketSessionData) GetTrackLength() uint16 { return data.TrackLength }

// SetTrackLength stores [PacketSessionData.TrackLength]
func (data *PacketSessionData) SetTrackLength(v uint16) { data.TrackLength = v }

// GetSessionType returns [PacketSessionData.SessionType]
func (data *PacketSessionData) GetSessionType() f1common.SessionTypeID { return data.SessionType }

// SetSessionType stores [PacketSessionData.SessionType]
func (data *PacketSessionData) SetSessionType(v f1common.SessionTypeID) { data.SessionType = v }

// GetTrackId returns [PacketSessionData.TrackId]
func (data *PacketSessionData) GetTrackId() f1common.TrackID { return data.TrackId }

// SetTrackId stores [PacketSessionData.TrackId]
func (data *PacketSessionData) SetTrackId(v f1common.TrackID) { data.TrackId = v }

// GetFormula returns [PacketSessionData.Formula]
func (data *PacketSessionData) GetFormula() uint8 { return data.Formula }

// SetFormula stores [PacketSessionData.Formula]
func (data *PacketSessionData) SetFormula(v uint8) { data.Formula = v }

// GetSessionTimeLeft returns [PacketSessionData.SessionTimeLeft]
func (data *PacketSessionData) GetSessionTimeLeft() uint16 { return data.SessionTimeLeft }

// SetSessionTimeLeft stores [PacketSessionData.SessionTimeLeft]
func (data *PacketSessionData) SetSessionTimeLeft(v uint16) { data.SessionTimeLeft = v }

// GetSessionDuration returns [PacketSessionData.SessionDuration]
func (data *PacketSessionData) GetSessionDuration() uint16 { return data.SessionDuration }

// SetSessionDuration stores [PacketSessionData.SessionDuration]
func (data *PacketSessionData) SetSessionDuration(v uint16) { data.SessionDuration = v }

// GetPitSpeedLimit returns [PacketSessionData.PitSpeedLimit]
func (data *PacketSessionData) GetPitSpeedLimit() uint8 { return data.PitSpeedLimit }

// SetPitSpeedLimit stores [PacketSessionData.PitSpeedLimit]
func (data *PacketSessionData) SetPitSpeedLimit(v uint8) { data.PitSpeedLimit = v }

// GetGamePaused returns [PacketSessionData.GamePaused]
func (data *PacketSessionData) GetGamePaused() uint8 { return data.GamePaused }

// SetGamePaused stores [PacketSessionData.GamePaused]
func (data *PacketSessionData) SetGamePaused(v uint8) { data.GamePaused = v }

// GetIsSpectating returns [PacketSessionData.IsSpectating]
func (data *PacketSessionData) GetIsSpectating() uint8 { return data.IsSpectating }

// SetIsSpectating stores [PacketSessionData.IsSpectating]
func (data *PacketSessionData) SetIsSpectating(v uint8) { data.IsSpectating = v }

// GetSpectatorCarIndex returns [PacketSessionData.SpectatorCarIndex]
func (data *PacketSessionData) GetSpectatorCarIndex() uint8 { return data.SpectatorCarIndex }

// SetSpectatorCarIndex stores [PacketSessionData.SpectatorCarIndex]
func (data *PacketSessionData) SetSpectatorCarIndex(v uint8) { data.SpectatorCarIndex = v }

// GetSliProNativeSupport returns [PacketSessionData.SliProNativeSupport]
func (data *PacketSessionData) GetSliProNativeSupport() uint8 { return data.SliProNativeSupport }

// SetSliProNativeSupport stores [PacketSessionData.SliProNativeSupport]
func (data *PacketSessionData) SetSliProNativeSupport(v uint8) { data.SliProNativeSupport = v }

// GetNumMarshalZones returns [PacketSessionData.NumMarshalZones]
func (data *PacketSessionData) GetNumMarshalZones() uint8 { return data.NumMarshalZones }

// SetNumMarshalZones stores [PacketSessionData.NumMarshalZones]
func (data *PacketSessionData) SetNumMarshalZones(v uint8) { data.NumMarshalZones = v }

// GetSafetyCarStatus returns [PacketSessionData.SafetyCarStatus]
func (data *PacketSessionData) GetSafetyCarStatus() uint8 { return data.SafetyCarStatus }

// SetSafetyCarStatus stores [PacketSessionData.SafetyCarStatus]
func (data *PacketSessionData) SetSafetyCarStatus(v uint8) { data.SafetyCarStatus = v }

// GetNetworkGame returns [PacketSessionData.NetworkGame]
func (data *PacketSessionData) GetNetworkGame() uint8 { return data.NetworkGame }

// SetNetworkGame stores [PacketSessionData.NetworkGame]
func (data *PacketSessionData) SetNetworkGame(v uint8) { data.NetworkGame = v }

// GetNumWeatherForecastSamples returns [PacketSessionData.NumWeatherForecastSamples]
func (data *PacketSessionData) GetNumWeatherForecastSamples() uint8 {
	return data.NumWeatherForecastSamples
}

// SetNumWeatherForecastSamples stores [PacketSessionData.NumWeatherForecastSamples]
func (data *PacketSessionData) SetNumWeatherForecastSamples(v uint8) {
	data.NumWeatherForecastSamples = v
}

// GetForecastAccuracy returns [PacketSessionData.ForecastAccuracy]
func (data *PacketSessionData) GetForecastAccuracy() uint8 { return data.ForecastAccuracy }

// SetForecastAccuracy stores [PacketSessionData.ForecastAccuracy]
func (data *PacketSessionData) SetForecastAccuracy(v uint8) { data.ForecastAccuracy = v }

// GetAiDifficulty returns [PacketSessionData.AiDifficulty]
func (data *PacketSessionData) GetAiDifficulty() uint8 { return data.AiDifficulty }

// SetAiDifficulty stores [PacketSessionData.AiDifficulty]
func (data *PacketSessionData) SetAiDifficulty(v uint8) { data.AiDifficulty = v }

// GetSeasonLinkIdentifier returns [PacketSessionData.SeasonLinkIdentifier]
func (data *PacketSessionData) GetSeasonLinkIdentifier() uint32 { return data.SeasonLinkIdentifier }

// SetSeasonLinkIdentifier stores [PacketSessionData.SeasonLinkIdentifier]
func (data *PacketSessionData) SetSeasonLinkIdentifier(v uint32) { data.SeasonLinkIdentifier = v }

// GetWeekendLinkIdentifier returns [PacketSessionData.WeekendLinkIdentifier]
func (data *PacketSessionData) GetWeekendLinkIdentifier() uint32 { return data.WeekendLinkIdentifier }

// SetWeekendLinkIdentifier stores [PacketSessionData.WeekendLinkIdentifier]
func (data *PacketSessionData) SetWeekendLinkIdentifier(v uint32) { data.WeekendLinkIdentifier = v }

// GetSessionLinkIdentifier returns [PacketSessionData.SessionLinkIdentifier]
func (data *PacketSessionData) GetSessionLinkIdentifier() uint32 { return data.SessionLinkIdentifier }

// SetSessionLinkIdentifier stores [PacketSessionData.SessionLinkIdentifier]
func (data *PacketSessionData) SetSessionLinkIdentifier(v uint32) { data.SessionLinkIdentifier = v }

// GetPitStopWindowIdealLap returns [PacketSessionData.PitStopWindowIdealLap]
func (data *PacketSessionData) GetPitStopWindowIdealLap() uint8 { return data.PitStopWindowIdealLap }

// SetPitStopWindowIdealLap stores [PacketSessionData.PitStopWindowIdealLap]
func (data *PacketSessionData) SetPitStopWindowIdealLap(v uint8) { data.PitStopWindowIdealLap = v }

// GetPitStopWindowLatestLap returns [PacketSessionData.PitStopWindowLatestLap]
func (data *PacketSessionData) GetPitStopWindowLatestLap() uint8 { return data.PitStopWindowLatestLap }

// SetPitStopWindowLatestLap stores [PacketSessionData.PitStopWindowLatestLap]
func (data *PacketSessionData) SetPitStopWindowLatestLap(v uint8) { data.PitStopWindowLatestLap = v }

// GetPitStopRejoinPosition returns [PacketSessionData.PitStopRejoinPosition]
func (data *PacketSessionData) GetPitStopRejoinPosition() uint8 { return data.PitStopRejoinPosition }

// SetPitStopRejoinPosition stores [PacketSessionData.PitStopRejoinPosition]
func (data *PacketSessionData) SetPitStopRejoinPosition(v uint8) { data.PitStopRejoinPosition = v }

// GetSteeringAssist returns [PacketSessionData.SteeringAssist]
func (data *PacketSessionData) GetSteeringAssist() uint8 { return data.SteeringAssist }

// SetSteeringAssist stores [PacketSessionData.SteeringAssist]
func (data *PacketSessionData) SetSteeringAssist(v uint8) { data.SteeringAssist = v }

// GetBrakingAssist returns [PacketSessionData.BrakingAssist]
func (data *PacketSessionData) GetBrakingAssist() uint8 { return data.BrakingAssist }

// SetBrakingAssist stores [PacketSessionData.BrakingAssist]
func (data *PacketSessionData) SetBrakingAssist(v uint8) { data.BrakingAssist = v }

// GetGearboxAssist returns [PacketSessionData.GearboxAssist]
func (data *PacketSessionData) GetGearboxAssist() uint8 { return data.GearboxAssist }

// SetGearboxAssist stores [PacketSessionData.GearboxAssist]
func (data *PacketSessionData) SetGearboxAssist(v uint8) { data.GearboxAssist = v }

// GetPitAssist returns [PacketSessionData.PitAssist]
func (data *PacketSessionData) GetPitAssist() uint8 { return data.PitAssist }

// SetPitAssist stores [PacketSessionData.PitAssist]
func (data *PacketSessionData) SetPitAssist(v uint8) { data.PitAssist = v }

// GetPitReleaseAssist returns [PacketSessionData.PitReleaseAssist]
func (data *PacketSessionData) GetPitReleaseAssist() uint8 { return data.PitReleaseAssist }

// SetPitReleaseAssist stores [PacketSessionData.PitReleaseAssist]
func (data *PacketSessionData) SetPitReleaseAssist(v uint8) { data.PitReleaseAssist = v }

// GetERSAssist returns [PacketSessionData.ERSAssist]
func (data *PacketSessionData) GetERSAssist() uint8 { return data.ERSAssist }

// SetERSAssist stores [PacketSessionData.ERSAssist]
func (data *PacketSessionData) SetERSAssist(v uint8) { data.ERSAssist = v }

// GetDRSAssist returns [PacketSessionData.DRSAssist]
func (data *PacketSessionData) GetDRSAssist() uint8 { return data.DRSAssist }

// SetDRSAssist stores [PacketSessionData.DRSAssist]
func (data *PacketSessionData) SetDRSAssist(v uint8) { data.DRSAssist = v }

// GetDynamicRacingLine returns [PacketSessionData.DynamicRacingLine]
func (data *PacketSessionData) GetDynamicRacingLine() uint8 { return data.DynamicRacingLine }

// SetDynamicRacingLine stores [PacketSessionData.DynamicRacingLine]
func (data *PacketSessionData) SetDynamicRacingLine(v uint8) { data.DynamicRacingLine = v }

// GetDynamicRacingLineType returns [PacketSessionData.DynamicRacingLineType]
func (data *PacketSessionData) GetDynamicRacingLineType() uint8 { return data.DynamicRacingLineType }

// SetDynamicRacingLineType stores [PacketSessionData.DynamicRacingLineType]
func (data *PacketSessionData) SetDynamicRacingLineType(v uint8) { data.DynamicRacingLineType = v }

// GetGameMode returns [PacketSessionData.GameMode]
func (data *PacketSessionData) GetGameMode() f1common.GamemodeID { return data.GameMode }

// SetGameMode stores [PacketSessionData.GameMode]
func (data *PacketSessionData) SetGameMode(v f1common.GamemodeID) { data.GameMode = v }

// GetRuleSet returns [PacketSessionData.RuleSet]
func (data *PacketSessionData) GetRuleSet() f1common.RulesetID { return data.RuleSet }

// SetRuleSet stores [PacketSessionData.RuleSet]
func (data *PacketSessionData) SetRuleSet(v f1common.RulesetID) { data.RuleSet = v }

// GetTimeOfDay returns [PacketSessionData.TimeOfDay]
func (data *PacketSessionData) GetTimeOfDay() uint32 { return data.TimeOfDay }

// SetTimeOfDay stores [PacketSessionData.TimeOfDay]
func (data *PacketSessionData) SetTimeOfDay(v uint32) { data.TimeOfDay = v }

// GetSessionLength returns [PacketSessionData.SessionLength]
func (data *PacketSessionData) GetSessionLength() uint8 { return data.SessionLength }

// SetSessionLength stores [PacketSessionData.SessionLength]
func (data *PacketSessionData) SetSessionLength(v uint8) { data.SessionLength = v }

// GetSpeedUnitsLeadPlayer returns [PacketSessionData.SpeedUnitsLeadPlayer]
func (data *PacketSessionData) GetSpeedUnitsLeadPlayer() uint8 { return data.SpeedUnitsLeadPlayer }

// SetSpeedUnitsLeadPlayer stores [PacketSessionData.SpeedUnitsLeadPlayer]
func (data *PacketSessionData) SetSpeedUnitsLeadPlayer(v uint8) { data.SpeedUnitsLeadPlayer = v }

// GetTemperatureUnitsLeadPlayer returns [PacketSessionData.TemperatureUnitsLeadPlayer]
func (data *PacketSessionData) GetTemperatureUnitsLeadPlayer() uint8 {
	return data.TemperatureUnitsLeadPlayer
}

// SetTemperatureUnitsLeadPlayer stores [PacketSessionData.TemperatureUnitsLeadPlayer]
func (data *PacketSessionData) SetTemperatureUnitsLeadPlayer(v uint8) {
	data.TemperatureUnitsLeadPlayer = v
}

// GetSpeedUnitsSecondaryPlayer returns [PacketSessionData.SpeedUnitsSecondaryPlayer]
func (data *PacketSessionData) GetSpeedUnitsSecondaryPlayer() uint8 {
	return data.SpeedUnitsSecondaryPlayer
}

// SetSpeedUnitsSecondaryPlayer stores [PacketSessionData.SpeedUnitsSecondaryPlayer]
func (data *PacketSessionData) SetSpeedUnitsSecondaryPlayer(v uint8) {
	data.SpeedUnitsSecondaryPlayer = v
}

// GetTemperatureUnitsSecondaryPlayer returns [PacketSessionData.TemperatureUnitsSecondaryPlayer]
func (data *PacketSessionData) GetTemperatureUnitsSecondaryPlayer() uint8 {
	return data.TemperatureUnitsSecondaryPlayer
}

// SetTemperatureUnitsSecondaryPlayer stores [PacketSessionData.TemperatureUnitsSecondaryPlayer]
func (data *PacketSessionData) SetTemperatureUnitsSecondaryPlayer(v uint8) {
	data.TemperatureUnitsSecondaryPlayer = v
}

// GetNumSafetyCarPeriods returns [PacketSessionData.NumSafetyCarPeriods]
func (data *PacketSessionData) GetNumSafetyCarPeriods() uint8 { return data.NumSafetyCarPeriods }

// SetNumSafetyCarPeriods stores [PacketSessionData.NumSafetyCarPeriods]
func (data *PacketSessionData) SetNumSafetyCarPeriods(v uint8) { data.NumSafetyCarPeriods = v }

// GetNumVirtualSafetyCarPeriods returns [PacketSessionData.NumVirtualSafetyCarPeriods]
func (data *PacketSessionData) GetNumVirtualSafetyCarPeriods() uint8 {
	return data.NumVirtualSafetyCarPeriods
}

// SetNumVirtualSafetyCarPeriods stores [PacketSessionData.NumVirtualSafetyCarPeriods]
func (data *PacketSessionData) SetNumVirtualSafetyCarPeriods(v uint8) {
	data.NumVirtualSafetyCarPeriods = v
}

// GetNumRedFlagPeriods returns [PacketSessionData.NumRedFlagPeriods]
func (data *PacketSessionData) GetNumRedFlagPeriods() uint8 { return data.NumRedFlagPeriods }

// SetNumRedFlagPeriods stores [PacketSessionData.NumRedFlagPeriods]
func (data *PacketSessionData) SetNumRedFlagPeriods(v uint8) { data.NumRedFlagPeriods = v }

// GetEqualCarPerformance returns [PacketSessionData.EqualCarPerformance]
func (data *PacketSessionData) GetEqualCarPerformance() uint8 { return data.EqualCarPerformance }

// SetEqualCarPerformance stores [PacketSessionData.EqualCarPerformance]
func (data *PacketSessionData) SetEqualCarPerformance(v uint8) { data.EqualCarPerformance = v }

// GetRecoveryMode returns [PacketSessionData.RecoveryMode]
func (data *PacketSessionData) GetRecoveryMode() uint8 { return data.RecoveryMode }

// SetRecoveryMode stores [PacketSessionData.RecoveryMode]
func (data *PacketSessionData) SetRecoveryMode(v uint8) { data.RecoveryMode = v }

// GetFlashbackLimit returns [PacketSessionData.FlashbackLimit]
func (data *PacketSessionData) GetFlashbackLimit() uint8 { return data.FlashbackLimit }

// SetFlashbackLimit stores [PacketSessionData.FlashbackLimit]
func (data *PacketSessionData) SetFlashbackLimit(v uint8) { data.FlashbackLimit = v }

// GetSurfaceType returns [PacketSessionData.SurfaceType]
func (data *PacketSessionData) GetSurfaceType() uint8 { return data.SurfaceType }

// SetSurfaceType stores [PacketSessionData.SurfaceType]
func (data *PacketSessionData) SetSurfaceType(v uint8) { data.SurfaceType = v }

// GetLowFuelMode returns [PacketSessionData.LowFuelMode]
func (data *PacketSessionData) GetLowFuelMode() uint8 { return data.LowFuelMode }

// SetLowFuelMode stores [PacketSessionData.LowFuelMode]
func (data *PacketSessionData) SetLowFuelMode(v uint8) { data.LowFuelMode = v }

// GetRaceStarts returns [PacketSessionData.RaceStarts]
func (data *PacketSessionData) GetRaceStarts() uint8 { return data.RaceStarts }

// SetRaceStarts stores [PacketSessionData.RaceStarts]
func (data *PacketSessionData) SetRaceStarts(v uint8) { data.RaceStarts = v }

// GetTyreTemperature returns [PacketSessionData.TyreTemperature]
func (data *PacketSessionData) GetTyreTemperature() uint8 { return data.TyreTemperature }

// SetTyreTemperature stores [PacketSessionData.TyreTemperature]
func (data *PacketSessionData) SetTyreTemperature(v uint8) { data.TyreTemperature = v }

// GetPitLaneTyreSim returns [PacketSessionData.PitLaneTyreSim]
func (data *PacketSessionData) GetPitLaneTyreSim() uint8 { return data.PitLaneTyreSim }

// SetPitLaneTyreSim stores [PacketSessionData.PitLaneTyreSim]
func (data *PacketSessionData) SetPitLaneTyreSim(v uint8) { data.PitLaneTyreSim = v }

// GetCarDamage returns [PacketSessionData.CarDamage]
func (data *PacketSessionData) GetCarDamage() uint8 { return data.CarDamage }

// SetCarDamage stores [PacketSessionData.CarDamage]
func (data *PacketSessionData) SetCarDamage(v uint8) { data.CarDamage = v }

// GetCarDamageRate returns [PacketSessionData.CarDamageRate]
func (data *PacketSessionData) GetCarDamageRate() uint8 { return data.CarDamageRate }

// SetCarDamageRate stores [PacketSessionData.CarDamageRate]
func (data *PacketSessionData) SetCarDamageRate(v uint8) { data.CarDamageRate = v }

// GetCollisions returns [PacketSessionData.Collisions]
func (data *PacketSessionData) GetCollisions() uint8 { return data.Collisions }

// SetCollisions stores [PacketSessionData.Collisions]
func (data *PacketSessionData) SetCollisions(v uint8) { data.Collisions = v }

// GetCollisionsOffForFirstLapOnly returns [PacketSessionData.CollisionsOffForFirstLapOnly]
func (data *PacketSessionData) GetCollisionsOffForFirstLapOnly() uint8 {
	return data.CollisionsOffForFirstLapOnly
}

// SetCollisionsOffForFirstLapOnly stores [PacketSessionData.CollisionsOffForFirstLapOnly]
func (data *PacketSessionData) SetCollisionsOffForFirstLapOnly(v uint8) {
	data.CollisionsOffForFirstLapOnly = v
}

// GetMpUnsafePitRelease returns [PacketSessionData.MpUnsafePitRelease]
func (data *PacketSessionData) GetMpUnsafePitRelease() uint8 { return data.MpUnsafePitRelease }

// SetMpUnsafePitRelease stores [PacketSessionData.MpUnsafePitRelease]
func (data *PacketSessionData) SetMpUnsafePitRelease(v uint8) { data.MpUnsafePitRelease = v }

// GetMpOffForGriefing returns [PacketSessionData.MpOffForGriefing]
func (data *PacketSessionData) GetMpOffForGriefing() uint8 { return data.MpOffForGriefing }

// SetMpOffForGriefing stores [PacketSessionData.MpOffForGriefing]
func (data *PacketSessionData) SetMpOffForGriefing(v uint8) { data.MpOffForGriefing = v }

// GetCornerCuttingStringency returns [PacketSessionData.CornerCuttingStringency]
func (data *PacketSessionData) GetCornerCuttingStringency() uint8 {
	return data.CornerCuttingStringency
}

// SetCornerCuttingStringency stores [PacketSessionData.CornerCuttingStringency]
func (data *PacketSessionData) SetCornerCuttingStringency(v uint8) { data.CornerCuttingStringency = v }

// GetParcFermeRules returns [PacketSessionData.ParcFermeRules]
func (data *PacketSessionData) GetParcFermeRules() uint8 { return data.ParcFermeRules }

// SetParcFermeRules stores [PacketSessionData.ParcFermeRules]
func (data *PacketSessionData) SetParcFermeRules(v uint8) { data.ParcFermeRules = v }

// GetPitStopExperience returns [PacketSessionData.PitStopExperience]
func (data *PacketSessionData) GetPitStopExperience() uint8 { return data.PitStopExperience }

// SetPitStopExperience stores [PacketSessionData.PitStopExperience]
func (data *PacketSessionData) SetPitStopExperience(v uint8) { data.PitStopExperience = v }

// GetSafetyCar returns [PacketSessionData.SafetyCar]
func (data *PacketSessionData) GetSafetyCar() uint8 { return data.SafetyCar }

// SetSafetyCar stores [PacketSessionData.SafetyCar]
func (data *PacketSessionData) SetSafetyCar(v uint8) { data.SafetyCar = v }

// GetSafetyCarExperience returns [PacketSessionData.SafetyCarExperience]
func (data *PacketSessionData) GetSafetyCarExperience() uint8 { return data.SafetyCarExperience }

// SetSafetyCarExperience stores [PacketSessionData.SafetyCarExperience]
func (data *PacketSessionData) SetSafetyCarExperience(v uint8) { data.SafetyCarExperience = v }

// GetFormationLap returns [PacketSessionData.FormationLap]
func (data *PacketSessionData) GetFormationLap() uint8 { return data.FormationLap }

// SetFormationLap stores [PacketSessionData.FormationLap]
func (data *PacketSessionData) SetFormationLap(v uint8) { data.FormationLap = v }

// GetFormationLapExperience returns [PacketSessionData.FormationLapExperience]
func (data *PacketSessionData) GetFormationLapExperience() uint8 { return data.FormationLapExperience }

// SetFormationLapExperience stores [PacketSessionData.FormationLapExperience]
func (data *PacketSessionData) SetFormationLapExperience(v uint8) { data.FormationLapExperience = v }

// GetRedFlags returns [PacketSessionData.RedFlags]
func (data *PacketSessionData) GetRedFlags() uint8 { return data.RedFlags }

// SetRedFlags stores [PacketSessionData.RedFlags]
func (data *PacketSessionData) SetRedFlags(v uint8) { data.RedFlags = v }

// GetAffectsLicenceLevelSolo returns [PacketSessionData.AffectsLicenceLevelSolo]
func (data *PacketSessionData) GetAffectsLicenceLevelSolo() uint8 {
	return data.AffectsLicenceLevelSolo
}

// SetAffectsLicenceLevelSolo stores [PacketSessionData.AffectsLicenceLevelSolo]
func (data *PacketSessionData) SetAffectsLicenceLevelSolo(v uint8) { data.AffectsLicenceLevelSolo = v }

// GetAffectsLicenceLevelMP returns [PacketSessionData.AffectsLicenceLevelMP]
func (data *PacketSessionData) GetAffectsLicenceLevelMP() uint8 { return data.AffectsLicenceLevelMP }

// SetAffectsLicenceLevelMP stores [PacketSessionData.AffectsLicenceLevelMP]
func (data *PacketSessionData) SetAffectsLicenceLevelMP(v uint8) { data.AffectsLicenceLevelMP = v }

// GetNumSessionsInWeekend returns [PacketSessionData.NumSessionsInWeekend]
func (data *PacketSessionData) GetNumSessionsInWeekend() uint8 { return data.NumSessionsInWeekend }

// SetNumSessionsInWeekend stores [PacketSessionData.NumSessionsInWeekend]
func (data *PacketSessionData) SetNumSessionsInWeekend(v uint8) { data.NumSessionsInWeekend = v }

// GetWeekendStructure returns the element of [PacketSessionData.WeekendStructure] at index
func (data *PacketSessionData) GetWeekendStructure(index int) uint8 {
	return data.WeekendStructure[index]
}

// SetWeekendStructure stores the element of [PacketSessionData.WeekendStructure] at index
func (data *PacketSessionData) SetWeekendStructure(index int, v uint8) {
	data.WeekendStructure[index] = v
}

// GetSector2LapDistanceStart returns [PacketSessionData.Sector2LapDistanceStart]
func (data *PacketSessionData) GetSector2LapDistanceStart() float32 {
	return data.Sector2LapDistanceStart
}

// SetSector2LapDistanceStart stores [PacketSessionData.Sector2LapDistanceStart]
func (data *PacketSessionData) SetSector2LapDistanceStart(v float32) {
	data.Sector2LapDistanceStart = v
}

// GetSector3LapDistanceStart returns [PacketSessionData.Sector3LapDistanceStart]
func (data *PacketSessionData) GetSector3LapDistanceStart() float32 {
	return data.Sector3LapDistanceStart
}

// SetSector3LapDistanceStart stores [PacketSessionData.Sector3LapDistanceStart]
func (data *PacketSessionData) SetSector3LapDistanceStart(v float32) {
	data.Sector3LapDistanceStart = v
}

// GetActiveAeroTrackStatus returns [PacketSessionData.ActiveAeroTrackStatus]
func (data *PacketSessionData) GetActiveAeroTrackStatus() uint8 { return data.ActiveAeroTrackStatus }

// SetActiveAeroTrackStatus stores [PacketSessionData.ActiveAeroTrackStatus]
func (data *PacketSessionData) SetActiveAeroTrackStatus(v uint8) { data.ActiveAeroTrackStatus = v }

// GetNumActiveAeroZonesFull returns [PacketSessionData.NumActiveAeroZonesFull]
func (data *PacketSessionData) GetNumActiveAeroZonesFull() uint8 { return data.NumActiveAeroZonesFull }

// SetNumActiveAeroZonesFull stores [PacketSessionData.NumActiveAeroZonesFull]
func (data *PacketSessionData) SetNumActiveAeroZonesFull(v uint8) { data.NumActiveAeroZonesFull = v }

// GetActiveAeroZonesFull returns the element of [PacketSessionData.ActiveAeroZonesFull] at index
func (data *PacketSessionData) GetActiveAeroZonesFull(index int) ActiveAeroZone {
	return data.ActiveAeroZonesFull[index]
}

// SetActiveAeroZonesFull stores the element of [PacketSessionData.ActiveAeroZonesFull] at index
func (data *PacketSessionData) SetActiveAeroZonesFull(index int, v ActiveAeroZone) {
	data.ActiveAeroZonesFull[index] = v
}

// GetNumActiveAeroZonesPartial returns [PacketSessionData.NumActiveAeroZonesPartial]
func (data *PacketSessionData) GetNumActiveAeroZonesPartial() uint8 {
	return data.NumActiveAeroZonesPartial
}

// SetNumActiveAeroZonesPartial stores [PacketSessionData.NumActiveAeroZonesPartial]
func (data *PacketSessionData) SetNumActiveAeroZonesPartial(v uint8) {
	data.NumActiveAeroZonesPartial = v
}

// GetActiveAeroZonesPartial returns the element of [PacketSessionData.ActiveAeroZonesPartial] at index
func (data *PacketSessionData) GetActiveAeroZonesPartial(index int) ActiveAeroZone {
	return data.ActiveAeroZonesPartial[index]
}

// SetActiveAeroZonesPartial stores the element of [PacketSessionData.ActiveAeroZonesPartial] at index
func (data *PacketSessionData) SetActiveAeroZonesPartial(index int, v ActiveAeroZone) {
	data.ActiveAeroZonesPartial[index] = v
}

// GetNumDRSZones returns [PacketSessionData.NumDRSZones]
func (data *PacketSessionData) GetNumDRSZones() uint8 { return data.NumDRSZones }

// SetNumDRSZones stores [PacketSessionData.NumDRSZones]
func (data *PacketSessionData) SetNumDRSZones(v uint8) { data.NumDRSZones = v }

// GetDrsZones returns the element of [PacketSessionData.DrsZones] at index
func (data *PacketSessionData) GetDrsZones(index int) DRSZone { return data.DrsZones[index] }

// SetDrsZones stores the element of [PacketSessionData.DrsZones] at index
func (data *PacketSessionData) SetDrsZones(index int, v DRSZone) { data.DrsZones[index] = v }

// GetStartReactionTime returns [PacketSessionData.StartReactionTime]
func (data *PacketSessionData) GetStartReactionTime() float32 { return data.StartReactionTime }

// SetStartReactionTime stores [PacketSessionData.StartReactionTime]
func (data *PacketSessionData) SetStartReactionTime(v float32) { data.StartReactionTime = v }

// GetAntiLockBrakesAssist returns [PacketSessionData.AntiLockBrakesAssist]
func (data *PacketSessionData) GetAntiLockBrakesAssist() uint8 { return data.AntiLockBrakesAssist }

// SetAntiLockBrakesAssist stores [PacketSessionData.AntiLockBrakesAssist]
func (data *PacketSessionData) SetAntiLockBrakesAssist(v uint8) { data.AntiLockBrakesAssist = v }

// GetTractionControlAssist returns [PacketSessionData.TractionControlAssist]
func (data *PacketSessionData) GetTractionControlAssist() uint8 { return data.TractionControlAssist }

// SetTractionControlAssist stores [PacketSessionData.TractionControlAssist]
func (data *PacketSessionData) SetTractionControlAssist(v uint8) { data.TractionControlAssist = v }

// GetDynamicRacingLineHiVis returns [PacketSessionData.DynamicRacingLineHiVis]
func (data *PacketSessionData) GetDynamicRacingLineHiVis() uint8 { return data.DynamicRacingLineHiVis }

// SetDynamicRacingLineHiVis stores [PacketSessionData.DynamicRacingLineHiVis]
func (data *PacketSessionData) SetDynamicRacingLineHiVis(v uint8) { data.DynamicRacingLineHiVis = v }

// GetDynamicRacingLineColourBlind returns [PacketSessionData.DynamicRacingLineColourBlind]
func (data *PacketSessionData) GetDynamicRacingLineColourBlind() uint8 {
	return data.DynamicRacingLineColourBlind
}

// SetDynamicRacingLineColourBlind stores [PacketSessionData.DynamicRacingLineColourBlind]
func (data *PacketSessionData) SetDynamicRacingLineColourBlind(v uint8) {
	data.DynamicRacingLineColourBlind = v
}

// GetRecurringRewindPrompt returns [PacketSessionData.RecurringRewindPrompt]
func (data *PacketSessionData) GetRecurringRewindPrompt() uint8 { return data.RecurringRewindPrompt }

// SetRecurringRewindPrompt stores [PacketSessionData.RecurringRewindPrompt]
func (data *PacketSessionData) SetRecurringRewindPrompt(v uint8) { data.RecurringRewindPrompt = v }
