// Code generated by tools/gen/accessors from packet_car_telemetry_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns the Header of [PacketCarTelemetryData]
func (data *PacketCarTelemetryData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketCarTelemetryData]
func (data *PacketCarTelemetryData) SetHeader(v PacketHeader) { data.Header = v }

// GetMfdPanelIndex returns the MfdPanelIndex of [PacketCarTelemetryData]
func (data *PacketCarTelemetryData) GetMfdPanelIndex() uint8 { return data.MfdPanelIndex }

// SetMfdPanelIndex stores the MfdPanelIndex of [PacketCarTelemetryData]
func (data *PacketCarTelemetryData) SetMfdPanelIndex(v uint8) { data.MfdPanelIndex = v }

// GetMfdPanelIndexSecondaryPlayer returns the MfdPanelIndexSecondaryPlayer of [PacketCarTelemetryData]
func (data *PacketCarTelemetryData) GetMfdPanelIndexSecondaryPlayer() uint8 {
	return data.MfdPanelIndexSecondaryPlayer
}

// SetMfdPanelIndexSecondaryPlayer stores the MfdPanelIndexSecondaryPlayer of [PacketCarTelemetryData]
func (data *PacketCarTelemetryData) SetMfdPanelIndexSecondaryPlayer(v uint8) {
	data.MfdPanelIndexSecondaryPlayer = v
}

// GetSuggestedGear returns the SuggestedGear of [PacketCarTelemetryData]
func (data *PacketCarTelemetryData) GetSuggestedGear() int8 { return data.SuggestedGear }

// SetSuggestedGear stores the SuggestedGear of [PacketCarTelemetryData]
func (data *PacketCarTelemetryData) SetSuggestedGear(v int8) { data.SuggestedGear = v }
