// Code generated by tools/gen/accessors from packet_lobby_info_data.go. DO NOT EDIT.

package f12026s

// GetHeader returns the Header of [PacketLobbyInfoData]
func (data *PacketLobbyInfoData) GetHeader() PacketHeader { return data.Header }

// SetHeader stores the Header of [PacketLobbyInfoData]
func (data *PacketLobbyInfoData) SetHeader(v PacketHeader) { data.Header = v }

// GetNumPlayers returns the NumPlayers of [PacketLobbyInfoData]
func (data *PacketLobbyInfoData) GetNumPlayers() uint8 { return data.NumPlayers }

// SetNumPlayers stores the NumPlayers of [PacketLobbyInfoData]
func (data *PacketLobbyInfoData) SetNumPlayers(v uint8) { data.NumPlayers = v }
