// Code generated by tools/gen/accessors from time_trial_data_set.go. DO NOT EDIT.

package f12026s

import (
	"github.com/daanv2/race-game-dashboard/pkg/f1game/f1common"
)

// GetCarIdx returns [TimeTrialDataSet.CarIdx]
func (data *TimeTrialDataSet) GetCarIdx() uint8 { return data.CarIdx }

// SetCarIdx stores [TimeTrialDataSet.CarIdx]
func (data *TimeTrialDataSet) SetCarIdx(v uint8) { data.CarIdx = v }

// GetTeamId returns [TimeTrialDataSet.TeamId]
func (data *TimeTrialDataSet) GetTeamId() f1common.TeamID { return data.TeamId }

// SetTeamId stores [TimeTrialDataSet.TeamId]
func (data *TimeTrialDataSet) SetTeamId(v f1common.TeamID) { data.TeamId = v }

// GetLapTimeInMS returns [TimeTrialDataSet.LapTimeInMS]
func (data *TimeTrialDataSet) GetLapTimeInMS() uint32 { return data.LapTimeInMS }

// SetLapTimeInMS stores [TimeTrialDataSet.LapTimeInMS]
func (data *TimeTrialDataSet) SetLapTimeInMS(v uint32) { data.LapTimeInMS = v }

// GetSector1TimeInMS returns [TimeTrialDataSet.Sector1TimeInMS]
func (data *TimeTrialDataSet) GetSector1TimeInMS() uint32 { return data.Sector1TimeInMS }

// SetSector1TimeInMS stores [TimeTrialDataSet.Sector1TimeInMS]
func (data *TimeTrialDataSet) SetSector1TimeInMS(v uint32) { data.Sector1TimeInMS = v }

// GetSector2TimeInMS returns [TimeTrialDataSet.Sector2TimeInMS]
func (data *TimeTrialDataSet) GetSector2TimeInMS() uint32 { return data.Sector2TimeInMS }

// SetSector2TimeInMS stores [TimeTrialDataSet.Sector2TimeInMS]
func (data *TimeTrialDataSet) SetSector2TimeInMS(v uint32) { data.Sector2TimeInMS = v }

// GetSector3TimeInMS returns [TimeTrialDataSet.Sector3TimeInMS]
func (data *TimeTrialDataSet) GetSector3TimeInMS() uint32 { return data.Sector3TimeInMS }

// SetSector3TimeInMS stores [TimeTrialDataSet.Sector3TimeInMS]
func (data *TimeTrialDataSet) SetSector3TimeInMS(v uint32) { data.Sector3TimeInMS = v }

// GetTractionControl returns [TimeTrialDataSet.TractionControl]
func (data *TimeTrialDataSet) GetTractionControl() uint8 { return data.TractionControl }

// SetTractionControl stores [TimeTrialDataSet.TractionControl]
func (data *TimeTrialDataSet) SetTractionControl(v uint8) { data.TractionControl = v }

// GetGearboxAssist returns [TimeTrialDataSet.GearboxAssist]
func (data *TimeTrialDataSet) GetGearboxAssist() uint8 { return data.GearboxAssist }

// SetGearboxAssist stores [TimeTrialDataSet.GearboxAssist]
func (data *TimeTrialDataSet) SetGearboxAssist(v uint8) { data.GearboxAssist = v }

// GetAntiLockBrakes returns [TimeTrialDataSet.AntiLockBrakes]
func (data *TimeTrialDataSet) GetAntiLockBrakes() uint8 { return data.AntiLockBrakes }

// SetAntiLockBrakes stores [TimeTrialDataSet.AntiLockBrakes]
func (data *TimeTrialDataSet) SetAntiLockBrakes(v uint8) { data.AntiLockBrakes = v }

// GetEqualCarPerformance returns [TimeTrialDataSet.EqualCarPerformance]
func (data *TimeTrialDataSet) GetEqualCarPerformance() uint8 { return data.EqualCarPerformance }

// SetEqualCarPerformance stores [TimeTrialDataSet.EqualCarPerformance]
func (data *TimeTrialDataSet) SetEqualCarPerformance(v uint8) { data.EqualCarPerformance = v }

// GetCustomSetup returns [TimeTrialDataSet.CustomSetup]
func (data *TimeTrialDataSet) GetCustomSetup() uint8 { return data.CustomSetup }

// SetCustomSetup stores [TimeTrialDataSet.CustomSetup]
func (data *TimeTrialDataSet) SetCustomSetup(v uint8) { data.CustomSetup = v }

// GetValid returns [TimeTrialDataSet.Valid]
func (data *TimeTrialDataSet) GetValid() uint8 { return data.Valid }

// SetValid stores [TimeTrialDataSet.Valid]
func (data *TimeTrialDataSet) SetValid(v uint8) { data.Valid = v }
