// Code generated by tools/gen/accessors from tyre_stint_history_data.go. DO NOT EDIT.

package f12026s

// GetEndLap returns the EndLap of [TyreStintHistoryData]
func (data *TyreStintHistoryData) GetEndLap() uint8 { return data.EndLap }

// SetEndLap stores the EndLap of [TyreStintHistoryData]
func (data *TyreStintHistoryData) SetEndLap(v uint8) { data.EndLap = v }

// GetTyreActualCompound returns the TyreActualCompound of [TyreStintHistoryData]
func (data *TyreStintHistoryData) GetTyreActualCompound() uint8 { return data.TyreActualCompound }

// SetTyreActualCompound stores the TyreActualCompound of [TyreStintHistoryData]
func (data *TyreStintHistoryData) SetTyreActualCompound(v uint8) { data.TyreActualCompound = v }

// GetTyreVisualCompound returns the TyreVisualCompound of [TyreStintHistoryData]
func (data *TyreStintHistoryData) GetTyreVisualCompound() uint8 { return data.TyreVisualCompound }

// SetTyreVisualCompound stores the TyreVisualCompound of [TyreStintHistoryData]
func (data *TyreStintHistoryData) SetTyreVisualCompound(v uint8) { data.TyreVisualCompound = v }
