name: 🐹 Golang
env:
  FORCE_COLOR: true

on:
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    name: 📋 Checks ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v7

      - name: 🏗️ Setup Golang
        uses: actions/setup-go@v7
        with:
          go-version-file: ./go.mod

      - name: 🛠️ Build
        run: go build ./...

      - name: 🧪 Run Tests
        run: go test ./... --cover -coverprofile=reports/coverage

      - name: 🔍 Run linting
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
